/// MakanMana V4 - taksonomi luas (mood/diet/allergy/cuisine).
/// Disimpan sebagai data statik dikumpul ikut kategori. Home kekal
/// bersih - senarai penuh hanya dalam sheet carian + onboarding + profil.
library;

class TaxItem {
  const TaxItem(this.key, this.label, {this.planLevel = 'free'});
  final String key;
  final String label;
  final String planLevel;
}

class TaxGroup {
  const TaxGroup(this.title, this.items);
  final String title;
  final List<TaxItem> items;
}

/// ---------------- MOOD ----------------
const List<TaxGroup> kMoodTaxonomy = [
  TaxGroup('Mood Asas', [
    TaxItem('lapar', 'Lapar'),
    TaxItem('laparGila', 'Lapar gila'),
    TaxItem('nakJimat', 'Nak jimat'),
    TaxItem('nakKenyang', 'Nak kenyang'),
    TaxItem('nakCepat', 'Nak cepat'),
    TaxItem('nakDekat', 'Nak dekat'),
    TaxItem('takKisah', 'Tak kisah apa'),
    TaxItem('surpriseMe', 'Surprise me'),
    TaxItem('pilihkanAku', 'Pilihkan aku'),
    TaxItem('akuBlur', 'Aku blur'),
  ]),
  TaxGroup('Rasa', [
    TaxItem('pedas', 'Pedas'),
    TaxItem('manis', 'Manis'),
    TaxItem('masam', 'Masam'),
    TaxItem('masin', 'Masin'),
    TaxItem('creamy', 'Creamy'),
    TaxItem('berkuah', 'Berkuah'),
    TaxItem('kering', 'Kering'),
    TaxItem('crispy', 'Crispy'),
    TaxItem('smoky', 'Smoky'),
    TaxItem('cheesy', 'Cheesy'),
    TaxItem('buttery', 'Buttery'),
    TaxItem('herbal', 'Herbal'),
    TaxItem('umami', 'Umami'),
  ]),
  TaxGroup('Situasi', [
    TaxItem('breakfast', 'Breakfast'),
    TaxItem('brunch', 'Brunch'),
    TaxItem('lunch', 'Lunch'),
    TaxItem('dinner', 'Dinner'),
    TaxItem('supper', 'Supper'),
    TaxItem('teaTime', 'Tea time'),
    TaxItem('afterWork', 'After work'),
    TaxItem('lateNight', 'Late night'),
    TaxItem('beforeWorkout', 'Before workout'),
    TaxItem('afterWorkout', 'After workout'),
    TaxItem('cheatDay', 'Cheat day'),
    TaxItem('cleanEating', 'Clean eating'),
  ]),
  TaxGroup('Bajet', [
    TaxItem('bawah5', 'Bawah RM5'),
    TaxItem('bawah10', 'Bawah RM10'),
    TaxItem('bawah15', 'Bawah RM15'),
    TaxItem('bawah20', 'Bawah RM20'),
    TaxItem('bajetStudent', 'Bajet student'),
    TaxItem('gajiBelumMasuk', 'Gaji belum masuk'),
    TaxItem('rewardDiri', 'Reward diri'),
    TaxItem('premiumSikit', 'Premium sikit'),
    TaxItem('worthIt', 'Worth it'),
    TaxItem('portionBesar', 'Portion besar'),
  ]),
  TaxGroup('Kesihatan', [
    TaxItem('healthy', 'Healthy'),
    TaxItem('highProtein', 'High protein'),
    TaxItem('lowCalorie', 'Low calorie'),
    TaxItem('lowCarb', 'Low carb'),
    TaxItem('lessOily', 'Less oily'),
    TaxItem('lessSugar', 'Less sugar'),
    TaxItem('noSugaryDrinks', 'No sugary drinks'),
    TaxItem('lightMeal', 'Light meal'),
    TaxItem('balancedMeal', 'Balanced meal'),
    TaxItem('proteinFirst', 'Protein first'),
    TaxItem('fiberFocus', 'Fiber focus'),
    TaxItem('gutFriendly', 'Gut friendly'),
  ]),
  TaxGroup('Cuaca', [
    TaxItem('hujanHujan', 'Hujan-hujan'),
    TaxItem('panasTerik', 'Panas terik'),
    TaxItem('sejukMalam', 'Sejuk malam'),
    TaxItem('lepasHujan', 'Lepas hujan'),
    TaxItem('cuacaMalas', 'Cuaca malas'),
    TaxItem('comfortFood', 'Need comfort food'),
    TaxItem('soupDay', 'Soup day'),
    TaxItem('icedDrinkDay', 'Iced drink day'),
  ]),
  TaxGroup('Sosial', [
    TaxItem('dating', 'Dating'),
    TaxItem('familyMeal', 'Family meal'),
    TaxItem('lepakKawan', 'Lepak kawan'),
    TaxItem('meetingSantai', 'Meeting santai'),
    TaxItem('makanSorang', 'Makan sorang'),
    TaxItem('officeLunch', 'Office lunch'),
    TaxItem('birthday', 'Birthday'),
    TaxItem('celebration', 'Celebration'),
    TaxItem('healingMakan', 'Healing makan'),
    TaxItem('studySession', 'Study session'),
  ]),
  TaxGroup('Tempat', [
    TaxItem('mamak', 'Mamak'),
    TaxItem('cafeChill', 'Cafe chill'),
    TaxItem('kopitiam', 'Kopitiam'),
    TaxItem('foodCourt', 'Food court'),
    TaxItem('warung', 'Warung'),
    TaxItem('driveThru', 'Drive-thru'),
    TaxItem('mallFood', 'Mall food'),
    TaxItem('streetFood', 'Street food'),
    TaxItem('openAir', 'Open air'),
    TaxItem('aircond', 'Aircond'),
    TaxItem('parkingSenang', 'Parking senang'),
  ]),
  TaxGroup('Pro AI', [
    TaxItem('dietGoal', 'Diet Goal', planLevel: 'pro'),
    TaxItem('aiFoodCoach', 'AI Food Coach', planLevel: 'pro'),
    TaxItem('calorieSmart', 'Calorie Smart', planLevel: 'pro'),
    TaxItem('budgetCoach', 'Budget Coach', planLevel: 'pro'),
    TaxItem('mealPlan', 'Meal Plan', planLevel: 'pro'),
    TaxItem('weeklyReport', 'Weekly Report', planLevel: 'pro'),
    TaxItem('bodyGoal', 'Body Goal', planLevel: 'pro'),
    TaxItem('sportFuel', 'Sport Fuel', planLevel: 'pro'),
    TaxItem('recoveryMeal', 'Recovery Meal', planLevel: 'pro'),
    TaxItem('antiBloat', 'Anti-bloat', planLevel: 'pro'),
  ]),
];

/// ---------------- DIET ----------------
const List<TaxGroup> kDietTaxonomy = [
  TaxGroup('Agama / Sekatan', [
    TaxItem('halal', 'Halal'),
    TaxItem('halalStrict', 'Halal strict'),
    TaxItem('halalPreferred', 'Halal preferred'),
    TaxItem('muslimFriendly', 'Muslim-friendly'),
    TaxItem('noPork', 'No pork'),
    TaxItem('noAlcohol', 'No alcohol'),
    TaxItem('vegetarian', 'Vegetarian'),
    TaxItem('vegan', 'Vegan'),
    TaxItem('pescatarian', 'Pescatarian'),
    TaxItem('eggetarian', 'Eggetarian'),
    TaxItem('hinduVegetarian', 'Hindu vegetarian'),
    TaxItem('buddhistVegetarian', 'Buddhist vegetarian'),
  ]),
  TaxGroup('Kesihatan / Badan', [
    TaxItem('balanced', 'Balanced'),
    TaxItem('highProtein', 'High protein'),
    TaxItem('lowCalorie', 'Low calorie'),
    TaxItem('lowCarb', 'Low carb'),
    TaxItem('keto', 'Keto'),
    TaxItem('lowFat', 'Low fat'),
    TaxItem('lowSugar', 'Low sugar'),
    TaxItem('diabeticFriendly', 'Diabetic-friendly'),
    TaxItem('heartFriendly', 'Heart-friendly'),
    TaxItem('lowSodium', 'Low sodium'),
    TaxItem('highFiber', 'High fiber'),
    TaxItem('glutenFree', 'Gluten-free'),
    TaxItem('dairyFree', 'Dairy-free'),
    TaxItem('cleanEating', 'Clean eating'),
    TaxItem('antiInflammatory', 'Anti-inflammatory'),
    TaxItem('gutFriendly', 'Gut-friendly'),
  ]),
  TaxGroup('Fitness', [
    TaxItem('leanBulk', 'Lean bulk'),
    TaxItem('muscleGain', 'Muscle gain'),
    TaxItem('fatLoss', 'Fat loss'),
    TaxItem('bodyRecomp', 'Body recomp'),
    TaxItem('runnerFuel', 'Runner fuel'),
    TaxItem('fighterFuel', 'Fighter fuel'),
    TaxItem('enduranceDiet', 'Endurance diet'),
    TaxItem('strengthDiet', 'Strength training diet'),
    TaxItem('recoveryDiet', 'Recovery diet'),
    TaxItem('restDayDiet', 'Rest day diet'),
  ]),
  TaxGroup('Gaya Hidup', [
    TaxItem('budgetDiet', 'Budget diet'),
    TaxItem('studentDiet', 'Student diet'),
    TaxItem('busyWorkerDiet', 'Busy worker diet'),
    TaxItem('familyFriendly', 'Family-friendly'),
    TaxItem('lightEater', 'Light eater'),
    TaxItem('bigPortion', 'Big portion'),
    TaxItem('homeStyle', 'Home-style meal'),
    TaxItem('noSpicy', 'No spicy'),
    TaxItem('lessOily', 'Less oily'),
    TaxItem('noFriedFood', 'No fried food'),
  ]),
];

/// ---------------- ALLERGY ----------------
const List<TaxGroup> kAllergyTaxonomy = [
  TaxGroup('Alahan Biasa', [
    TaxItem('peanut', 'Peanut'),
    TaxItem('treeNuts', 'Tree nuts'),
    TaxItem('milk', 'Milk / dairy'),
    TaxItem('egg', 'Egg'),
    TaxItem('fish', 'Fish'),
    TaxItem('shellfish', 'Shellfish'),
    TaxItem('soy', 'Soy'),
    TaxItem('wheat', 'Wheat'),
    TaxItem('gluten', 'Gluten'),
    TaxItem('sesame', 'Sesame'),
    TaxItem('mustard', 'Mustard'),
    TaxItem('celery', 'Celery'),
    TaxItem('lupin', 'Lupin'),
    TaxItem('sulfites', 'Sulfites'),
  ]),
  TaxGroup('Seafood', [
    TaxItem('shrimp', 'Shrimp'),
    TaxItem('crab', 'Crab'),
    TaxItem('squid', 'Squid'),
    TaxItem('clam', 'Clam'),
    TaxItem('mussel', 'Mussel'),
    TaxItem('oyster', 'Oyster'),
    TaxItem('anchovy', 'Anchovy'),
    TaxItem('fishSauce', 'Fish sauce'),
    TaxItem('belacanSf', 'Belacan'),
  ]),
  TaxGroup('Sensitiviti Malaysia', [
    TaxItem('santan', 'Santan'),
    TaxItem('cili', 'Cili'),
    TaxItem('pedasTinggi', 'Pedas tinggi'),
    TaxItem('belacan', 'Belacan'),
    TaxItem('ikanBilis', 'Ikan bilis'),
    TaxItem('petai', 'Petai'),
    TaxItem('jering', 'Jering'),
    TaxItem('tempoyak', 'Tempoyak'),
    TaxItem('cincaluk', 'Cincaluk'),
    TaxItem('budu', 'Budu'),
    TaxItem('durian', 'Durian'),
  ]),
  TaxGroup('Bahan / Aditif', [
    TaxItem('msg', 'MSG'),
    TaxItem('artificialColoring', 'Artificial coloring'),
    TaxItem('artificialSweetener', 'Artificial sweetener'),
    TaxItem('preservatives', 'Preservatives'),
    TaxItem('caffeine', 'Caffeine'),
    TaxItem('alcohol', 'Alcohol'),
    TaxItem('gelatin', 'Gelatin'),
  ]),
];

/// ---------------- CUISINE ----------------
const List<TaxGroup> kCuisineTaxonomy = [
  TaxGroup('Malaysia', [
    TaxItem('malay', 'Malay'),
    TaxItem('mamak', 'Mamak'),
    TaxItem('indianMuslim', 'Indian Muslim'),
    TaxItem('chinese', 'Chinese'),
    TaxItem('indian', 'Indian'),
    TaxItem('nyonya', 'Nyonya'),
    TaxItem('sabah', 'Sabah'),
    TaxItem('sarawak', 'Sarawak'),
    TaxItem('kelantanese', 'Kelantanese'),
    TaxItem('terengganu', 'Terengganu'),
    TaxItem('penang', 'Penang'),
    TaxItem('johor', 'Johor'),
    TaxItem('minang', 'Minang'),
    TaxItem('indonesianMalay', 'Indonesian-Malay'),
    TaxItem('thaiMalay', 'Thai-Malay'),
  ]),
  TaxGroup('Asia', [
    TaxItem('thai', 'Thai'),
    TaxItem('indonesian', 'Indonesian'),
    TaxItem('korean', 'Korean'),
    TaxItem('japanese', 'Japanese'),
    TaxItem('vietnamese', 'Vietnamese'),
    TaxItem('taiwanese', 'Taiwanese'),
    TaxItem('hongKong', 'Hong Kong'),
    TaxItem('dimSum', 'Dim Sum'),
    TaxItem('sichuan', 'Sichuan'),
    TaxItem('cantonese', 'Cantonese'),
    TaxItem('hainanese', 'Hainanese'),
    TaxItem('filipino', 'Filipino'),
    TaxItem('singaporean', 'Singaporean'),
    TaxItem('middleEastern', 'Middle Eastern'),
    TaxItem('arab', 'Arab'),
    TaxItem('turkish', 'Turkish'),
    TaxItem('pakistani', 'Pakistani'),
    TaxItem('bangladeshi', 'Bangladeshi'),
  ]),
  TaxGroup('Barat / Global', [
    TaxItem('western', 'Western'),
    TaxItem('italian', 'Italian'),
    TaxItem('french', 'French'),
    TaxItem('mexican', 'Mexican'),
    TaxItem('mediterranean', 'Mediterranean'),
    TaxItem('american', 'American'),
    TaxItem('british', 'British'),
    TaxItem('spanish', 'Spanish'),
    TaxItem('german', 'German'),
    TaxItem('greek', 'Greek'),
    TaxItem('australianCafe', 'Australian cafe'),
    TaxItem('fusion', 'Fusion'),
  ]),
  TaxGroup('Jenis Makanan', [
    TaxItem('nasiCampur', 'Nasi campur'),
    TaxItem('nasiLemak', 'Nasi lemak'),
    TaxItem('nasiKandar', 'Nasi kandar'),
    TaxItem('nasiAyam', 'Nasi ayam'),
    TaxItem('ayamGepuk', 'Ayam gepuk'),
    TaxItem('ayamPenyet', 'Ayam penyet'),
    TaxItem('mee', 'Mee'),
    TaxItem('laksa', 'Laksa'),
    TaxItem('soup', 'Soup'),
    TaxItem('satay', 'Satay'),
    TaxItem('burger', 'Burger'),
    TaxItem('pizza', 'Pizza'),
    TaxItem('pasta', 'Pasta'),
    TaxItem('steak', 'Steak'),
    TaxItem('cafeFood', 'Cafe food'),
    TaxItem('dessert', 'Dessert'),
    TaxItem('bakery', 'Bakery'),
    TaxItem('vegetarianFood', 'Vegetarian'),
    TaxItem('healthyBowl', 'Healthy bowl'),
    TaxItem('salad', 'Salad'),
    TaxItem('seafood', 'Seafood'),
    TaxItem('bbq', 'BBQ'),
    TaxItem('steamboat', 'Steamboat'),
    TaxItem('hotpot', 'Hotpot'),
  ]),
];

enum TaxonomyType { mood, diet, allergy, cuisine }

List<TaxGroup> taxonomyFor(TaxonomyType type) => switch (type) {
      TaxonomyType.mood => kMoodTaxonomy,
      TaxonomyType.diet => kDietTaxonomy,
      TaxonomyType.allergy => kAllergyTaxonomy,
      TaxonomyType.cuisine => kCuisineTaxonomy,
    };

/// Nota keselamatan untuk setiap jenis (tiada nasihat perubatan).
String? taxonomySafetyNote(TaxonomyType type) => switch (type) {
      TaxonomyType.allergy =>
        'MakanMana boleh membantu kurangkan risiko, tetapi sila sahkan '
            'dengan restoran kerana bahan mungkin berubah.',
      TaxonomyType.diet =>
        'Label diet perubatan adalah keutamaan, bukan nasihat perubatan.',
      _ => null,
    };
