// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'core/security/ios_firebase_configuration.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return productionIosFirebaseOptions(
          apiKey: const String.fromEnvironment('IOS_FIREBASE_API_KEY'),
          appId: const String.fromEnvironment('IOS_FIREBASE_APP_ID'),
          messagingSenderId:
              const String.fromEnvironment('IOS_FIREBASE_SENDER_ID'),
          projectId: const String.fromEnvironment('IOS_FIREBASE_PROJECT_ID'),
          bundleId: const String.fromEnvironment('IOS_FIREBASE_BUNDLE_ID'),
          storageBucket:
              const String.fromEnvironment('IOS_FIREBASE_STORAGE_BUCKET'),
          clientId: const String.fromEnvironment('IOS_GOOGLE_CLIENT_ID'),
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_xtQQsF4eIDZILzRf-Xbm1xX76JPWs28',
    appId: '1:1097613804556:android:e7bf74d97b21e0c1601a29',
    messagingSenderId: '1097613804556',
    projectId: 'makanmana-c59f3',
    storageBucket: 'makanmana-c59f3.firebasestorage.app',
  );
}
