import 'package:flutter/material.dart';

/// Localization ringkas berasaskan map untuk ms / en / zh / ta.
/// Guna: AppLocalizations.of(context).t('kunci')
class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static AppLocalizations of(BuildContext context) =>
      Localizations.of<AppLocalizations>(context, AppLocalizations)!;

  static const supportedLocales = [
    Locale('ms'),
    Locale('en'),
    Locale('zh'),
    Locale('ta'),
  ];

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  String t(String key) =>
      _values[locale.languageCode]?[key] ?? _values['ms']![key] ?? key;

  static const Map<String, Map<String, String>> _values = {
    'ms': {
      // V4 Tong-Tong Bill
      'ttBillNew': 'Bil Baru',
      'ttListIntro':
          'Kongsi bil makan ramai-ramai. Tolak siapa makan apa, siapa dah '
              'bayar, siapa belum — tanpa drama.',
      'ttNoBills': 'Belum ada bil Tong-Tong',
      'ttEmptyDesc':
          'Buat bil pertama untuk split makan mamak, lepak kafe, atau dinner kumpulan.',
      'ttMakeBill': 'Buat Bil',
      'ttBillFallback': 'Bil makan',
      'ttPeople': 'orang',
      'ttUnpaidSuffix': 'belum bayar',
      'ttAllDone': 'semua selesai',
      'ttStatusCancelled': 'Batal',
      'ttAddParticipant': 'Tambah peserta',
      'ttFriendName': 'Nama kawan',
      'ttItemName': 'Nama item',
      'ttWhoEats': 'Siapa makan? (kosong = semua)',
      'ttNeedTotal2': 'Perlu total + sekurang-kurangnya 2 peserta',
      'ttPlaceEat': 'Tempat makan',
      'ttTotalBill': 'Total bil (RM)',
      'ttSplitWay': 'Cara bahagi',
      'ttSplitByItem': 'Ikut item',
      'ttSplitCustom': 'Custom',
      'ttParticipantsLabel': 'Peserta',
      'ttPayFirstLower': 'bayar dulu',
      'ttAddItemHint': 'Tambah item + tanda siapa makan.',
      'ttCalcMake': 'Kira & Buat Bil',
      'ttNotFound': 'Bil tidak dijumpai',
      'ttBillShort': 'Bil',
      'ttTotalWord': 'Total',
      'ttWhoPaysWho': 'Siapa bayar siapa',
      'ttShareWhatsapp': 'Kongsi ke WhatsApp',
      'ttPaid': 'Dah bayar',
      'ttPending': 'Menunggu sah',
      'ttWaived': 'Dilepaskan',
      'ttUnpaid': 'Belum bayar',
      'ttPayFirst': 'Bayar dulu',
      'ttOwes': 'Hutang',
      'ttNoDebt': 'Tiada hutang',
      'ttMarkPaid': 'Tanda bayar',
      'taxSearch': 'Cari...',
      'taxSelected': 'dipilih',
      // V4 Meal Wallet
      'walletBudgetTip': 'Tetapan bajet',
      'walletLogMeal': 'Log Makan',
      'walletTotalToday': 'Total makan hari ini',
      'walletThisWeek': 'Minggu ini',
      'walletThisMonth': 'Bulan ini',
      'walletBudgetSample':
          'Budget Coach: Minuman manis 18% dari belanja minggu ini. '
              'Baki bajet RM58 — sasarkan makan bawah RM14 untuk 4 hidangan seterusnya.',
      'walletRemaining': 'Baki budget',
      'walletToday': 'Hari ini',
      'walletWeek': 'Minggu',
      'walletMonth': 'Bulan',
      'walletLogCount': 'Log bulan ini',
      'walletDrinkSpend': 'Belanja minuman',
      'walletAvgMeal': 'Purata / hidangan',
      'walletTopPlace': 'Tempat paling kerap',
      'walletRecentLog': 'Log terkini',
      'walletNoLog': 'Belum ada log. Tekan "Log Makan" untuk mula.',
      'walletMealFallback': 'Makan',
      'walletLogFallback': 'Log makan',
      'walletDelete': 'Padam',
      'walletBudgetLimit': 'Had bajet (RM)',
      'walletDaily': 'Harian',
      'walletWeekly': 'Mingguan',
      'walletMonthly': 'Bulanan',
      'walletBudgetStyle': 'Gaya bajet',
      'walletModeRelaxed': 'Santai',
      'walletModeBalanced': 'Seimbang',
      'walletModeStrict': 'Ketat',
      'walletBudgetSaved': 'Bajet disimpan',
      'walletSaveBudget': 'Simpan bajet',
      'walletPlaceOptional': 'Tempat / kedai (pilihan)',
      'walletTotalRequired': 'Total makan (RM) *',
      'walletItemOptional': 'Item (pilihan)',
      'walletItemHint':
          'Cth: Nasi ayam RM9 • Teh ais RM2.50. Total dikira automatik.',
      'walletAddItem': 'Tambah item',
      'walletItemNameHint': 'Cth: Nasi ayam / Teh ais',
      'walletPriceHint': 'Harga (RM)',
      'itemFood': 'Makanan',
      'itemDrink': 'Minuman',
      'itemDessert': 'Pencuci mulut',
      'itemAddon': 'Tambahan',
      'itemService': 'Servis/Cukai',
      'itemDelivery': 'Penghantaran',
      'walletAdd': 'Tambah',
      'walletItem': 'Item',
      'walletDetails': 'Butiran',
      'walletPhotoTitle': 'Foto makanan & resit',
      'walletPhotoUpsell': 'Naik taraf Plus untuk simpan foto makanan & resit.',
      'walletReceipt': 'Resit',
      'walletNoteOptional': 'Nota (pilihan)',
      'walletSaving': 'Menyimpan...',
      'walletSaveToWallet': 'Simpan ke Meal Wallet',
      'walletRecorded': 'direkod ke Meal Wallet',
      // V4 Social + Group Hub
      'feedForYou': 'Untuk Anda',
      'feedFollowing': 'Mengikuti',
      'feedNearby': 'Berdekatan',
      'feedTrending': 'Trending',
      'followingEmpty': 'Ikut orang untuk lihat siaran mereka',
      'nearbyEmpty': 'Tiada siaran berdekatan lagi',
      'trendingEmpty': 'Belum ada yang trending',
      'foodProfileTitle': 'Profil Makanan',
      'myFoodProfile': 'Profil Makanan Saya',
      'editFoodProfile': 'Edit profil makanan',
      'publicPostsTitle': 'Siaran awam',
      'noPublicPosts': 'Belum ada siaran awam',
      'follow': 'Ikut',
      'following': 'Mengikuti',
      'statPosts': 'Siaran',
      'statFollowers': 'Pengikut',
      'statFollowing': 'Mengikuti',
      'statReviews': 'Ulasan',
      'emptyFollowList': 'Belum ada sesiapa lagi',
      'mute': 'Senyapkan',
      'unmute': 'Nyahsenyap',
      'block': 'Blok',
      'unblock': 'Nyahblok',
      'report': 'Lapor',
      'reportSent': 'Laporan dihantar. Terima kasih.',
      'bioLabel': 'Bio',
      'bioHint': 'Ceritakan pasal selera makan kau...',
      'favFoodLabel': 'Makanan kegemaran',
      'favCuisineLabel': 'Masakan kegemaran',
      'foodMoodLabel': 'Mood makanan',
      'dietPrefLabel': 'Keutamaan diet',
      'budgetRangeLabel': 'Julat bajet',
      'showDietPublic': 'Tunjuk diet di profil',
      'showBudgetPublic': 'Tunjuk bajet di profil',
      'optionalPrivacyNote': 'Maklumat pilihan — kongsi jika kau nak sahaja.',
      'privateNote': 'Lokasi & status kesihatan sentiasa peribadi.',
      'chooseVisibility': 'Siapa boleh lihat?',
      'visPublic': 'Awam',
      'visPublicDesc': 'Semua orang boleh nampak',
      'visFollowers': 'Pengikut sahaja',
      'visFollowersDesc': 'Hanya pengikut kau nampak',
      'visGroup': 'Grup sahaja',
      'visGroupDesc': 'Ahli grup sahaja',
      'visPrivate': 'Peribadi',
      'visPrivateDesc': 'Kau sahaja yang nampak',
      'visUnlisted': 'Tak tersenarai',
      'visUnlistedDesc': 'Hanya melalui pautan',
      'shareAction': 'Kongsi',
      'sharedOk': 'Dikongsi!',
      'shareToGroup': 'Kongsi ke grup',
      'shareCardSuggestion': 'Cadangan AI',
      'shareCardBudget': 'Insight Bajet',
      'shareCardGroupResult': 'Keputusan Grup',
      'shareCardPoll': 'Undian',
      'shareCardWallet': 'Kongsi Belanja',
      'myActivityTitle': 'Aktiviti Saya',
      'mealWalletTitle': 'Meal Wallet',
      'tongTongTitle': 'Tong-Tong Bill',
      // Group Hub
      'myGroups': 'Grup Saya',
      'discoverGroups': 'Teroka grup',
      'membersLabel': 'ahli',
      'joinGroup': 'Sertai grup',
      'groupTabFeed': 'Feed',
      'groupTabPolls': 'Undian',
      'groupTabBills': 'Bil',
      'groupTabMembers': 'Ahli',
      'groupSettings': 'Tetapan grup',
      'groupInfo': 'Maklumat grup',
      'groupDesc': 'Penerangan grup',
      'groupStatusTitle': 'Status ahli',
      'pinnedAnnouncement': 'Pengumuman disemat',
      'pinAnnouncement': 'Sematkan pengumuman',
      'announcementHint': 'Tulis pengumuman grup...',
      'savedOk': 'Disimpan',
      'roleOwner': 'Owner',
      'roleAdmin': 'Admin',
      'roleMember': 'Ahli',
      'roleViewer': 'Pemerhati',
      'removeMember': 'Buang ahli',
      'ownerCantLeave': 'Owner tak boleh tinggalkan grup.',
      // Poll
      'createPoll': 'Cipta undian',
      'pollQuestionHint': 'Soalan undian...',
      'pollType': 'Jenis undian',
      'pollOptions': 'Pilihan undian',
      'pollOption': 'Pilihan',
      'addOption': 'Tambah pilihan',
      'pollClosed': 'Ditutup',
      'noPolls': 'Belum ada undian',
      'pollRestaurant': 'Restoran',
      'pollCuisine': 'Masakan',
      'pollTime': 'Masa',
      'pollBudget': 'Bajet',
      'pollMenu': 'Menu',
      'pollLocation': 'Lokasi',
      'pollHealth': 'Sihat',
      // Shared status
      'shareStatus': 'Kongsi status',
      'shareStatusDesc': 'Beritahu geng mood makan kau.',
      'hungerLevel': 'Tahap lapar',
      'allergyWarning': 'Amaran alahan',
      'locationArea': 'Kawasan lokasi',
      'shareFitnessGoal': 'Kongsi matlamat kecergasan',
      'fitnessPrivateNote': 'Peribadi secara lalai.',
      'fitnessGoalLabel': 'Matlamat kecergasan',
      'statusMoodHint': 'cth: Nak pedas',
      'statusCuisineHint': 'cth: Mamak',
      'statusAllergyHint': 'cth: Alah kacang',
      'statusAreaHint': 'cth: Bangi',
      'statusFitnessHint': 'cth: Bulking',
      // Group bills
      'newBill': 'Bil baharu',
      'noBills': 'Belum ada bil',
      'billActive': 'Aktif',
      'billSettled': 'Selesai',
      'billPlace': 'Nama tempat',
      'billTotal': 'Jumlah bil',
      'splitMethod': 'Kaedah bahagi',
      'splitEqual': 'Sama rata',
      'splitSponsor': 'Belanja',
      'whoJoins': 'Siapa join?',
      'payerLabel': 'Pembayar',
      'setPayer': 'Jadi pembayar',
      'createBill': 'Cipta bil',
      'fillBillFields': 'Isi nama tempat, jumlah & peserta.',
      'appName': 'MakanMana',
      'tagline': 'Nak makan apa hari ni?',
      'chooseLanguage': 'Pilih bahasa anda',
      'continueLabel': 'Teruskan',
      'login': 'Log Masuk',
      'email': 'Emel',
      'password': 'Kata laluan',
      'signIn': 'Log Masuk',
      'createAccount': 'Daftar Akaun',
      'haveAccount': 'Dah ada akaun? Log masuk',
      'noAccount': 'Belum ada akaun? Daftar',
      'signInGoogle': 'Log masuk dengan Google',
      'devMode': 'Firebase belum disambung. Mod dev tersedia.',
      'devContinue': 'Teruskan (Mod Dev)',
      'authError': 'Log masuk gagal. Semak emel dan kata laluan.',
      'onbTitle': 'Jom kenal selera kau',
      'onbDiet': 'Jenis diet kau?',
      'onbHalal': 'Keutamaan halal?',
      'onbAllergies': 'Ada alahan?',
      'onbBudget': 'Bajet biasa semakan (RM)',
      'onbCuisine': 'Masakan kegemaran?',
      'onbSpicy': 'Tahap pedas kau?',
      'onbMealTimes': 'Waktu makan biasa?',
      'next': 'Seterusnya',
      'back': 'Kembali',
      'finish': 'Siap!',
      'dietNone': 'Semua jenis',
      'dietVegetarian': 'Vegetarian',
      'dietVegan': 'Vegan',
      'dietPescatarian': 'Pescatarian',
      'halalYes': 'Halal sahaja',
      'halalAny': 'Tak kisah',
      'greetingMorning': 'Selamat pagi',
      'greetingAfternoon': 'Selamat tengah hari',
      'greetingEvening': 'Selamat petang',
      'greetingNight': 'Selamat malam',
      'searchHint': 'Cari makanan atau tempat...',
      'yourArea': 'Sekitar lokasi anda',
      'moodTitle': 'Mood kau hari ni?',
      'moodPedas': 'Pedas',
      'moodJimat': 'Jimat',
      'moodLapar': 'Lapar',
      'moodSurprise': 'Surprise',
      'moodCafe': 'Cafe Chill',
      'moodHujan': 'Hujan-hujan',
      'moodSupper': 'Supper',
      'moodHighRating': 'High Rating',
      'moodNearby': 'Nearby Only',
      'moodHealthy': 'Healthy Mode',
      'aiPickTitle': 'Pilihan AI untuk kau',
      'matchLabel': 'padan',
      'spinNow': 'Spin Sekarang',
      'categories': 'Kategori',
      'nearbyTitle': 'Berdekatan dengan kau',
      'aiInsight': 'MakanMana belajar dari pilihan kau',
      'navHome': 'Utama',
      'navExplore': 'Explore',
      'navHistory': 'Sejarah',
      'navProfile': 'Profil',
      'letsEatHere': 'Jom makan sini',
      'notFeeling': 'Tak rasa nak',
      'viewDetails': 'Lihat detail',
      'whyPicked': 'Kenapa MakanMana pilih',
      'withinBudget': 'Dalam bajet biasa kau',
      'nearLocation': 'Dekat dengan lokasi sekarang',
      'fitsMood': 'Sesuai dengan mood kau',
      'highRating': 'Rating tinggi & ramai suka',
      'openNow': 'Buka sekarang',
      'closedNow': 'Tutup',
      'rejectTitle': 'Kenapa tak rasa nak?',
      'rejectTooFar': 'Jauh sangat',
      'rejectTooPricey': 'Mahal sangat',
      'rejectNotMood': 'Bukan mood ni',
      'rejectAteRecently': 'Baru makan ni',
      'rejectOther': 'Lain-lain',
      'rejectThanks': 'Noted! MakanMana akan belajar dari ni.',
      'accepted': 'Sedap! Selera kau direkod.',
      'historyTitle': 'Sejarah Makan',
      'historyEmpty':
          'Belum ada rekod makan lagi.\nSpin dan terima cadangan untuk mula!',
      'weeklySummary': 'Ringkasan minggu ini',
      'profileTitle': 'Profil',
      'tasteProfile': 'Taste Profile',
      'foodMemory': 'Food Memory',
      'dietBudget': 'Diet & Bajet',
      'languageLabel': 'Bahasa',
      'appStyle': 'App Style',
      'planLabel': 'Pelan',
      'privacyLabel': 'Privasi',
      'helpLabel': 'Bantuan',
      'settingsLabel': 'Tetapan',
      'logout': 'Log Keluar',
      'paywallTitle': 'Naik taraf MakanMana',
      'planFree': 'Free',
      'planPlus': 'Plus',
      'planPro': 'Pro',
      'perMonth': '/bulan',
      'currentPlan': 'Pelan semasa',
      'upgradeNow': 'Naik taraf sekarang',
      'mockNotice': 'Pembelian sebenar akan diaktifkan kemudian.',
      'spinThemeTitle': 'Spin Theme',
      'themeMagicPlate': 'Magic Plate',
      'themeRodaMisteri': 'Roda Misteri',
      'themeShuffleCard': 'Shuffle Card',
      'themeNearbyRadar': 'Nearby Radar',
      'lockedPlus': 'Perlu Plus',
      'comingSoon': 'Akan datang!',
      'openMap': 'Buka Peta',
      'share': 'Kongsi',
      'save': 'Simpan',
      'quickInfo': 'Info ringkas',
      'whyFits': 'Kenapa sesuai untuk kau',
      'mapPlaceholder': 'Peta akan datang',
      'spinning': 'Tengah pilih untuk kau...',
      'proBadge': 'PRO',
      'plusBadge': 'PLUS',
      'previewNotice': 'Ini preview. Buka penuh dengan naik taraf.',
      'spinToday': 'Spin hari ni',
      'spinLimitReached':
          'Spin percuma hari ni dah habis! Naik taraf Plus untuk spin tanpa had.',
      'statMeals': 'Makan',
      'statSpend': 'Belanja',
      'statPlaces': 'Tempat',
      'noResults': 'Tiada hasil dijumpai',
      'feedTitle': 'Feed Makan',
      'feedAteAt': 'makan kat',
      'feedEmpty':
          'Belum ada siaran lagi. Jadi yang pertama — spin dan jom makan!',
      'justNow': 'baru tadi',
      'minAgo': 'min lepas',
      'hourAgo': 'jam lepas',
      'dayAgo': 'hari lepas',
      'composeHint': 'Apa kau makan hari ni?',
      'postAction': 'Post',
      'feedTab': 'Feed',
      'groupsTab': 'Grup',
      'camera': 'Kamera',
      'gallery': 'Galeri',
      'createGroup': 'Buat Grup',
      'groupName': 'Nama grup',
      'join': 'Sertai',
      'leaveGroup': 'Keluar grup',
      'deletePost': 'Padam post ni?',
      'cancelAction': 'Batal',
      'deleteAction': 'Padam',
      'postSent': 'Post dihantar.',
      'postFailed': 'Tak dapat hantar. Semak internet dan cuba lagi.',
      'adminTitle': 'Semakan Admin',
      'approveAction': 'Luluskan',
      'rejectAction': 'Tolak',
      'noPending': 'Tiada ulasan menunggu semakan.',
      'editProfileTitle': 'Edit Profil',
      'displayNameLabel': 'Nama paparan',
      'displayNameHint': 'Nama kau',
      'usernameLabel': 'Username',
      'usernameHint': 'username_kau',
      'saveAction': 'Simpan',
      'profileSaved': 'Profil dikemaskini!',
      'usernameTaken': 'Username ini sudah diambil. Cuba yang lain.',
      'favoritesTitle': 'Kegemaran',
      'favoritesEmpty':
          'Belum ada kegemaran. Tekan 🔖 pada mana-mana kedai untuk simpan!',
      'favoriteAdded': 'Disimpan ke Kegemaran!',
      'editTaste': 'Ubah citarasa',
      'memoryIntro': 'MakanMana dah belajar dari',
      'faq1Q': 'Macam mana MakanMana pilih kedai untuk saya?',
      'faq1A':
          'Kami ambil kira lokasi, bajet, mood, citarasa, sejarah makan dan rating kau — semakin kerap guna, semakin tepat.',
      'faq2Q': 'Apa beza Free, Plus dan Pro?',
      'faq2A':
          'Free: 3 spin/hari & ciri asas. Plus: spin tanpa had, semua mood & tema, kegemaran. Pro: semua + Laporan Mingguan, AI Coach, Diet Goal, Meal Plan, Calorie Scan, Group Decision.',
      'faq3Q': 'Macam mana nak bagi rating kedai?',
      'faq3A':
          'Dari Sejarah (selepas makan via app), atau Check-in 5 minit di kedai, atau pilih "Order delivery?" (disemak admin).',
      'faq4Q': 'Adakah data saya selamat?',
      'faq4A':
          'Ya. Data peribadi kau hanya boleh diakses akaun kau sendiri. Feed hanya papar nama & gambar profil yang kau pilih.',
      'faq5Q': 'Macam mana nak batalkan langganan?',
      'faq5A':
          'Melalui Google Play > Langganan. Pelan kekal aktif sehingga tarikh pembaharuan.',
      'scanIntro': 'Snap gambar makanan kau — AI akan analisis kalori.',
      'scanning': 'AI sedang analisis makanan kau...',
      'scanFailed': 'Analisis gagal. Semak internet dan cuba lagi.',
      'groupIntro':
          'Buat sesi undian, kongsi kod ke grup WhatsApp, semua undi — keputusan keluar live. Tiada lagi "entah, kau pilih la"!',
      'createSession': 'Buat Sesi Undian',
      'joinSession': 'Sertai Dengan Kod',
      'sessionNotFound': 'Sesi tidak dijumpai. Semak kod.',
      'sessionCode': 'KOD SESI',
      'shareCode': 'Kongsi',
      'votesLabel': 'undian setakat ini',
      'voteTitle': 'Undi Makan',
      'voteHint': 'Tekan pilihan untuk undi. Boleh tukar bila-bila.',
      'orLabel': 'ATAU',
      'commentsTitle': 'Komen',
      'commentHint': 'Tulis komen...',
      'noComments': 'Belum ada komen. Mulakan perbualan!',
      'proHubTitle': 'Pro Tools',
      'proHubTeaser':
          'Semua alat AI Food Coach di sini. Naik taraf Pro untuk buka penuh!',
      'lockedPro': 'Ciri Pro —naik taraf untuk buka.',
      'soonBadge': 'AKAN DATANG',
      'proReportTitle': 'Laporan Mingguan',
      'proReportDesc': 'Analisis 7 hari: makan, belanja, kesihatan, corak.',
      'proCoachTitle': 'AI Food Coach',
      'proCoachDesc': 'Tips peribadi dari corak makan sebenar kau.',
      'proGoalTitle': 'Diet Goal',
      'proGoalDesc': 'Matlamat kau mengubah setiap cadangan.',
      'proPlanTitle': 'Meal Plan',
      'proPlanDesc': 'Pelan makan 3 hari dari tempat berdekatan.',
      'proScanTitle': 'Calorie Scan',
      'proScanDesc': 'Snap gambar makanan, dapat anggaran kalori.',
      'proGroupTitle': 'Group Decision',
      'proGroupDesc': 'Undian makan ramai-ramai tanpa drama.',
      'healthyLabel': 'Sihat',
      'varietyLabel': 'Variasi',
      'satisfactionLabel': 'Kepuasan',
      'favoritePlaceLabel': 'Tempat kegemaran',
      'topCuisinesLabel': 'Cuisine paling kerap',
      'coachIntro':
          'Hai! Aku dah analisis corak makan kau minggu ini. Ini pemerhatian aku:',
      'coachNoData': 'Belum cukup data. Spin dan makan dulu, jumpa lagi!',
      'goalIntro':
          'Pilih matlamat kau — setiap cadangan MakanMana akan menyokongnya secara automatik.',
      'goalSihat': 'Sihat',
      'goalSihatDesc': 'Utamakan pilihan sihat & seimbang setiap cadangan.',
      'goalJimat': 'Jimat',
      'goalJimatDesc': 'Utamakan tempat bajet mesra poket.',
      'goalSeimbang': 'Seimbang',
      'goalSeimbangDesc': 'Campuran sihat, sedap dan berpatutan.',
      'goalSaved': 'Diet Goal disimpan! Cadangan seterusnya akan ikut.',
      'regeneratePlan': 'Jana semula',
      'slotBreakfast': 'Sarapan',
      'slotLunch': 'Makan tengah hari',
      'slotDinner': 'Makan malam',
      'dayToday': 'Hari ini',
      'dayTomorrow': 'Esok',
      'dayAfter': 'Lusa',
      'confirmPurchase': 'Naik taraf ke',
      'planUpdated': 'Plan dikemaskini.',
      'downgradeFree': 'Tukar ke Free',
      'unlockWithPlus': 'Buka dengan Plus',
      'unlockWithPro': 'Buka dengan Pro',
      'rateTitle': 'Bagi Rating',
      'rateShort': 'Rating',
      'rateAction': 'Bagi rating',
      'reviewHint': 'Kongsi pengalaman kau... (pilihan)',
      'submitReview': 'Hantar Rating',
      'shareToFeed': 'Kongsi ke Feed Makan',
      'reviewSent': 'Rating dihantar. Terima kasih!',
      'reviewPending': 'Rating dihantar — menunggu semakan admin',
      'reviewNotEligible':
          'Belum layak — pastikan dah 5 minit di kedai dan masih di lokasi.',
      'deliveryPendingNote':
          'Rating delivery akan disemak dahulu sebelum dipaparkan.',
      'checkinAction': 'Check-in',
      'checkinDone':
          'Check-in berjaya! Boleh bagi rating selepas 5 minit di sini.',
      'rateWaitPrefix': 'Rating dalam',
      'communityRatingLabel': 'Komuniti MakanMana',
      'reviewsTitle': 'Ulasan komuniti',
      'noReviews': 'Belum ada ulasan. Jadi yang pertama!',
      'deliveryRate': 'Order delivery?',
      'howWasMeal': 'Macam mana makan kat',
      'fitCoachTitle': 'Fit Coach',
      'fitCoachTeaser': 'Score harian, workout dan menu sihat peribadi.',
      'fitSetupPrompt': 'Lengkapkan profil Fit untuk mula.',
      'fitWorkoutDone': 'Workout siap',
      'fitWorkoutPending': 'Workout belum siap',
      'fitStepsUnit': 'langkah',
      'fitLockedTitle': 'Fit Coach ialah ciri Pro',
      'fitLockedBody':
          'Preview ini tunjuk score, workout dan cadangan menu yang akan dibuka dengan Pro.',
      'fitUpgradeCta': 'Naik taraf Pro',
      'fitLogThis': 'Log ini',
      'fitLogged': 'direkod',
      'fitLogMealTitle': 'Log makanan',
      'fitQuickLog': 'Quick Log',
      'fitManualLog': 'Manual',
      'fitMealName': 'Nama makanan',
      'fitSaveLog': 'Simpan log',
      'fitFbDone': 'Siap',
      'fitFbEasy': 'Terlalu mudah',
      'fitFbHard': 'Terlalu susah',
      'fitFbNoTime': 'Tiada masa',
      'fitFbPain': 'Rasa sakit',
      'fitFbTitle': 'Macam mana workout tadi?',
      'fitPainWarning':
          'Workout direkod. Jika sakit berlarutan, rujuk profesional bertauliah.',
      'fitFbThanks': 'Maklum balas direkod.',
      'fitSetupTitle': 'Setup Fit Coach',
      'fitSetupBody':
          'Isi asas badan, matlamat dan gaya latihan supaya MakanMana boleh kira target selamat.',
      'fitBodyBasics': 'Asas badan',
      'fitHeight': 'Tinggi',
      'fitWeight': 'Berat',
      'fitAge': 'Umur',
      'fitGender': 'Jantina',
      'fitMale': 'Lelaki',
      'fitFemale': 'Perempuan',
      'fitGoalTitle': 'Matlamat Fit',
      'fitGoalHealthy': 'Hidup sihat',
      'fitGoalFatLoss': 'Turun lemak',
      'fitGoalLean': 'Lean body',
      'fitGoalRecomp': 'Body recomp',
      'fitGoalMuscle': 'Naik otot',
      'fitGoalSport': 'Prestasi sukan',
      'fitLevel': 'Tahap',
      'fitLevelBeginner': 'Beginner',
      'fitLevelIntermediate': 'Intermediate',
      'fitLevelAdvanced': 'Advanced',
      'fitLevelAthlete': 'Athlete',
      'fitTrainingPref': 'Latihan',
      'fitDaysPerWeek': 'Hari latihan seminggu',
      'fitSessionDuration': 'Tempoh sesi',
      'fitTargets': 'Target harian',
      'fitBudgetMin': 'Bajet min',
      'fitBudgetMax': 'Bajet max',
      'fitStepTarget': 'Target langkah',
      'fitSaveProfile': 'Simpan profil Fit',
      'fitStartSetup': 'Mula setup',
      'fitEditProfile': 'Edit profil Fit',
      'fitTodayTitle': 'Fit Hari Ini',
      'fitNutritionTargets': 'Target nutrisi',
      'fitWater': 'Air',
      'fitLogWater': 'Log air',
      'fitLogSteps': 'Log langkah',
      'fitLogWeight': 'Log berat',
      'fitWorkoutToday': 'Workout hari ini',
      'fitChangeMood': 'Tukar mood',
      'fitFinishWorkout': 'Selesai workout',
      'fitMenuSuggestions': 'Menu sesuai hari ini',
      'fitMonitorTitle': 'Monitor Fit',
      'fitWeeklyScore': 'Fit Score minggu ini',
      'fitStepsTrend': 'Trend langkah',
      'fitCaloriesTrend': 'Trend kalori',
      'fitBodyTrend': 'Trend badan',
      'fitBodyTrendEmpty': 'Belum cukup ukuran badan untuk carta.',
      'fitWeeklyReport': 'Laporan mingguan',
      'fitRecentWorkouts': 'Workout terkini',
      'fitNoWorkoutYet': 'Belum ada workout direkod.',
      'fitSampleReport':
          'Minggu ini nampak konsisten. Kekalkan protein dan tambah langkah sedikit.',
      'fitSampleRecProtein': 'Tambah protein sarapan untuk bantu pemulihan.',
      'fitSampleRecSteps': 'Jalan 10 minit selepas makan tengah hari.',
      'fitSportMoodTitle': 'Sport Mood',
      'fitSportMoodIntro':
          'Pilih gaya latihan hari ini. MakanMana akan laraskan workout dan fokus makanan.',
      'historyTabMeals': 'Makanan',
      'historyTabFitness': 'Fitness',
      'historyTabMonitor': 'Monitor',
      'historyTabReports': 'Laporan',
      'fitTodayLogs': 'Log hari ini',
      'fitNoLogsToday': 'Belum ada log hari ini. Mula dengan makanan pertama anda.',
      'fitOpenMonitor': 'Buka Monitor penuh',
      'fitReportTitle': 'Laporan Makanan & Kecergasan Mingguan',
      'fitReportTeaser':
          'Setiap Ahad, coach anda merumuskan latihan, langkah, protein dan corak makan minggu itu.',
      'fitTrainingDone': 'Latihan siap',
      'fitAvgSteps': 'Purata langkah',
      'fitAvgCalories': 'Purata kalori',
      'fitProteinHit': 'Capaian protein',
      'fitViewFullReport': 'Lihat laporan penuh',
      'fitWeekStats': 'Statistik minggu ini',
      'fitHealthyMeals': 'Hidangan seimbang',
      'fitHeavyMeals': 'Hidangan berat',
      'fitSugaryDrinks': 'Minuman manis',
      'fitNextWeek': 'Fokus minggu depan',
      'fitNoDataYet': 'Belum cukup data. Log makanan & latihan untuk mula.',
      'fitWearable': 'Sambungan Wearable',
      'fitWearableSoon':
          'Akan datang: sync langkah, workout, kadar jantung dan tidur dari jam pintar anda.',
      'fitWearableView': 'Lihat peranti',
      'fitHealthPermTitle': 'Kebenaran Kesihatan',
      'fitPermSteps': 'Langkah',
      'fitPermWorkout': 'Workout',
      'fitPermCalories': 'Kalori terbakar',
      'fitPermDistance': 'Jarak',
      'fitPermHeart': 'Kadar jantung',
      'fitPermSleep': 'Tidur',
      'fitPermNote':
          'Anda mengawal sepenuhnya data kesihatan anda. Matikan mana-mana kebenaran pada bila-bila masa dan data berkaitan tidak lagi disegerakkan.',
      'fitLogScan': 'Log ke Fit Coach',
      'fitStreakDays': 'hari streak',
      'noGroups': 'Belum ada grup. Buat grup makan pertama kau!',
    },
    'en': {
      // V4 Tong-Tong Bill
      'ttBillNew': 'New Bill',
      'ttListIntro':
          'Split a group meal. Track who ate what, who paid, who hasn\'t — no drama.',
      'ttNoBills': 'No Tong-Tong bills yet',
      'ttEmptyDesc':
          'Create your first bill to split a mamak meal, cafe hangout, or group dinner.',
      'ttMakeBill': 'Create Bill',
      'ttBillFallback': 'Meal bill',
      'ttPeople': 'people',
      'ttUnpaidSuffix': 'unpaid',
      'ttAllDone': 'all settled',
      'ttStatusCancelled': 'Cancelled',
      'ttAddParticipant': 'Add participant',
      'ttFriendName': "Friend's name",
      'ttItemName': 'Item name',
      'ttWhoEats': 'Who ate this? (empty = everyone)',
      'ttNeedTotal2': 'Need a total + at least 2 participants',
      'ttPlaceEat': 'Place',
      'ttTotalBill': 'Bill total (RM)',
      'ttSplitWay': 'Split method',
      'ttSplitByItem': 'By item',
      'ttSplitCustom': 'Custom',
      'ttParticipantsLabel': 'Participants',
      'ttPayFirstLower': 'pays first',
      'ttAddItemHint': 'Add items + mark who ate.',
      'ttCalcMake': 'Calculate & Create',
      'ttNotFound': 'Bill not found',
      'ttBillShort': 'Bill',
      'ttTotalWord': 'Total',
      'ttWhoPaysWho': 'Who pays whom',
      'ttShareWhatsapp': 'Share to WhatsApp',
      'ttPaid': 'Paid',
      'ttPending': 'Pending confirm',
      'ttWaived': 'Waived',
      'ttUnpaid': 'Unpaid',
      'ttPayFirst': 'Pays first',
      'ttOwes': 'Owes',
      'ttNoDebt': 'No debt',
      'ttMarkPaid': 'Mark paid',
      'taxSearch': 'Search...',
      'taxSelected': 'selected',
      // V4 Meal Wallet
      'walletBudgetTip': 'Budget settings',
      'walletLogMeal': 'Log Meal',
      'walletTotalToday': "Today's food total",
      'walletThisWeek': 'This week',
      'walletThisMonth': 'This month',
      'walletBudgetSample':
          'Budget Coach: Sweet drinks are 18% of this week\'s spend. '
              'RM58 budget left — aim to eat under RM14 for the next 4 meals.',
      'walletRemaining': 'Budget left',
      'walletToday': 'Today',
      'walletWeek': 'Week',
      'walletMonth': 'Month',
      'walletLogCount': 'Logs this month',
      'walletDrinkSpend': 'Drink spend',
      'walletAvgMeal': 'Avg / meal',
      'walletTopPlace': 'Most frequent place',
      'walletRecentLog': 'Recent logs',
      'walletNoLog': 'No logs yet. Tap "Log Meal" to start.',
      'walletMealFallback': 'Meal',
      'walletLogFallback': 'Meal log',
      'walletDelete': 'Delete',
      'walletBudgetLimit': 'Budget limit (RM)',
      'walletDaily': 'Daily',
      'walletWeekly': 'Weekly',
      'walletMonthly': 'Monthly',
      'walletBudgetStyle': 'Budget style',
      'walletModeRelaxed': 'Relaxed',
      'walletModeBalanced': 'Balanced',
      'walletModeStrict': 'Strict',
      'walletBudgetSaved': 'Budget saved',
      'walletSaveBudget': 'Save budget',
      'walletPlaceOptional': 'Place / shop (optional)',
      'walletTotalRequired': 'Meal total (RM) *',
      'walletItemOptional': 'Items (optional)',
      'walletItemHint':
          'e.g. Chicken rice RM9 • Iced tea RM2.50. Total auto-calculated.',
      'walletAddItem': 'Add item',
      'walletItemNameHint': 'e.g. Chicken rice / Iced tea',
      'walletPriceHint': 'Price (RM)',
      'itemFood': 'Food',
      'itemDrink': 'Drink',
      'itemDessert': 'Dessert',
      'itemAddon': 'Add-on',
      'itemService': 'Service/Tax',
      'itemDelivery': 'Delivery',
      'walletAdd': 'Add',
      'walletItem': 'Item',
      'walletDetails': 'Details',
      'walletPhotoTitle': 'Food & receipt photos',
      'walletPhotoUpsell': 'Upgrade to Plus to save food & receipt photos.',
      'walletReceipt': 'Receipt',
      'walletNoteOptional': 'Note (optional)',
      'walletSaving': 'Saving...',
      'walletSaveToWallet': 'Save to Meal Wallet',
      'walletRecorded': 'recorded to Meal Wallet',
      // V4 Social + Group Hub
      'feedForYou': 'For You',
      'feedFollowing': 'Following',
      'feedNearby': 'Nearby',
      'feedTrending': 'Trending',
      'followingEmpty': 'Follow people to see their posts',
      'nearbyEmpty': 'No nearby posts yet',
      'trendingEmpty': 'Nothing trending yet',
      'foodProfileTitle': 'Food Profile',
      'myFoodProfile': 'My Food Profile',
      'editFoodProfile': 'Edit food profile',
      'publicPostsTitle': 'Public posts',
      'noPublicPosts': 'No public posts yet',
      'follow': 'Follow',
      'following': 'Following',
      'statPosts': 'Posts',
      'statFollowers': 'Followers',
      'statFollowing': 'Following',
      'statReviews': 'Reviews',
      'emptyFollowList': 'Nobody here yet',
      'mute': 'Mute',
      'unmute': 'Unmute',
      'block': 'Block',
      'unblock': 'Unblock',
      'report': 'Report',
      'reportSent': 'Report sent. Thank you.',
      'bioLabel': 'Bio',
      'bioHint': 'Tell us about your food taste...',
      'favFoodLabel': 'Favourite food',
      'favCuisineLabel': 'Favourite cuisine',
      'foodMoodLabel': 'Food mood',
      'dietPrefLabel': 'Diet preference',
      'budgetRangeLabel': 'Budget range',
      'showDietPublic': 'Show diet on profile',
      'showBudgetPublic': 'Show budget on profile',
      'optionalPrivacyNote': 'Optional info — share only if you want.',
      'privateNote': 'Location & health status are always private.',
      'chooseVisibility': 'Who can see this?',
      'visPublic': 'Public',
      'visPublicDesc': 'Anyone can see',
      'visFollowers': 'Followers only',
      'visFollowersDesc': 'Only your followers can see',
      'visGroup': 'Group only',
      'visGroupDesc': 'Only group members',
      'visPrivate': 'Private',
      'visPrivateDesc': 'Only you can see',
      'visUnlisted': 'Unlisted',
      'visUnlistedDesc': 'Only via link',
      'shareAction': 'Share',
      'sharedOk': 'Shared!',
      'shareToGroup': 'Share to group',
      'shareCardSuggestion': 'AI Suggestion',
      'shareCardBudget': 'Budget Insight',
      'shareCardGroupResult': 'Group Result',
      'shareCardPoll': 'Poll',
      'shareCardWallet': 'Spending Share',
      'myActivityTitle': 'My Activity',
      'mealWalletTitle': 'Meal Wallet',
      'tongTongTitle': 'Tong-Tong Bill',
      'myGroups': 'My Groups',
      'discoverGroups': 'Discover groups',
      'membersLabel': 'members',
      'joinGroup': 'Join group',
      'groupTabFeed': 'Feed',
      'groupTabPolls': 'Polls',
      'groupTabBills': 'Bills',
      'groupTabMembers': 'Members',
      'groupSettings': 'Group settings',
      'groupInfo': 'Group info',
      'groupDesc': 'Group description',
      'groupStatusTitle': 'Member status',
      'pinnedAnnouncement': 'Pinned announcement',
      'pinAnnouncement': 'Pin announcement',
      'announcementHint': 'Write a group announcement...',
      'savedOk': 'Saved',
      'roleOwner': 'Owner',
      'roleAdmin': 'Admin',
      'roleMember': 'Member',
      'roleViewer': 'Viewer',
      'removeMember': 'Remove member',
      'ownerCantLeave': 'Owner cannot leave the group.',
      'createPoll': 'Create poll',
      'pollQuestionHint': 'Poll question...',
      'pollType': 'Poll type',
      'pollOptions': 'Poll options',
      'pollOption': 'Option',
      'addOption': 'Add option',
      'pollClosed': 'Closed',
      'noPolls': 'No polls yet',
      'pollRestaurant': 'Restaurant',
      'pollCuisine': 'Cuisine',
      'pollTime': 'Time',
      'pollBudget': 'Budget',
      'pollMenu': 'Menu',
      'pollLocation': 'Location',
      'pollHealth': 'Healthy',
      'shareStatus': 'Share status',
      'shareStatusDesc': 'Let the crew know your food mood.',
      'hungerLevel': 'Hunger level',
      'allergyWarning': 'Allergy warning',
      'locationArea': 'Location area',
      'shareFitnessGoal': 'Share fitness goal',
      'fitnessPrivateNote': 'Private by default.',
      'fitnessGoalLabel': 'Fitness goal',
      'statusMoodHint': 'e.g. Craving spicy',
      'statusCuisineHint': 'e.g. Mamak',
      'statusAllergyHint': 'e.g. Nut allergy',
      'statusAreaHint': 'e.g. Bangi',
      'statusFitnessHint': 'e.g. Bulking',
      'newBill': 'New bill',
      'noBills': 'No bills yet',
      'billActive': 'Active',
      'billSettled': 'Settled',
      'billPlace': 'Place name',
      'billTotal': 'Bill total',
      'splitMethod': 'Split method',
      'splitEqual': 'Split equal',
      'splitSponsor': 'Treat',
      'whoJoins': "Who's joining?",
      'payerLabel': 'Payer',
      'setPayer': 'Set payer',
      'createBill': 'Create bill',
      'fillBillFields': 'Fill in place, total & members.',
      'appName': 'MakanMana',
      'tagline': 'What should we eat today?',
      'chooseLanguage': 'Choose your language',
      'continueLabel': 'Continue',
      'login': 'Login',
      'email': 'Email',
      'password': 'Password',
      'signIn': 'Sign In',
      'createAccount': 'Create Account',
      'haveAccount': 'Have an account? Sign in',
      'noAccount': 'No account yet? Sign up',
      'signInGoogle': 'Sign in with Google',
      'devMode': 'Firebase not connected. Dev mode available.',
      'devContinue': 'Continue (Dev Mode)',
      'authError': 'Sign in failed. Check email and password.',
      'onbTitle': 'Let’s learn your taste',
      'onbDiet': 'Your diet type?',
      'onbHalal': 'Halal preference?',
      'onbAllergies': 'Any allergies?',
      'onbBudget': 'Usual meal budget (RM)',
      'onbCuisine': 'Favorite cuisines?',
      'onbSpicy': 'Your spice level?',
      'onbMealTimes': 'Usual meal times?',
      'next': 'Next',
      'back': 'Back',
      'finish': 'Done!',
      'dietNone': 'Everything',
      'dietVegetarian': 'Vegetarian',
      'dietVegan': 'Vegan',
      'dietPescatarian': 'Pescatarian',
      'halalYes': 'Halal only',
      'halalAny': 'No preference',
      'greetingMorning': 'Good morning',
      'greetingAfternoon': 'Good afternoon',
      'greetingEvening': 'Good evening',
      'greetingNight': 'Good night',
      'searchHint': 'Search food or places...',
      'yourArea': 'Around your location',
      'moodTitle': 'Your mood today?',
      'moodPedas': 'Spicy',
      'moodJimat': 'Budget',
      'moodLapar': 'Hungry',
      'moodSurprise': 'Surprise',
      'moodCafe': 'Cafe Chill',
      'moodHujan': 'Rainy Day',
      'moodSupper': 'Supper',
      'moodHighRating': 'High Rating',
      'moodNearby': 'Nearby Only',
      'moodHealthy': 'Healthy Mode',
      'aiPickTitle': 'AI pick for you',
      'matchLabel': 'match',
      'spinNow': 'Spin Now',
      'categories': 'Categories',
      'nearbyTitle': 'Near you',
      'aiInsight': 'MakanMana learns from your choices',
      'navHome': 'Home',
      'navExplore': 'Explore',
      'navHistory': 'History',
      'navProfile': 'Profile',
      'letsEatHere': 'Let’s eat here',
      'notFeeling': 'Not feeling this',
      'viewDetails': 'View details',
      'whyPicked': 'Why MakanMana picked this',
      'withinBudget': 'Within your usual budget',
      'nearLocation': 'Near your current location',
      'fitsMood': 'Fits your mood',
      'highRating': 'Highly rated & well loved',
      'openNow': 'Open now',
      'closedNow': 'Closed',
      'rejectTitle': 'Why not this one?',
      'rejectTooFar': 'Too far',
      'rejectTooPricey': 'Too pricey',
      'rejectNotMood': 'Not my mood',
      'rejectAteRecently': 'Ate this recently',
      'rejectOther': 'Other',
      'rejectThanks': 'Noted! MakanMana will learn from this.',
      'accepted': 'Nice! Your taste is recorded.',
      'historyTitle': 'Meal History',
      'historyEmpty':
          'No meal records yet.\nSpin and accept a suggestion to start!',
      'weeklySummary': 'This week’s summary',
      'profileTitle': 'Profile',
      'tasteProfile': 'Taste Profile',
      'foodMemory': 'Food Memory',
      'dietBudget': 'Diet & Budget',
      'languageLabel': 'Language',
      'appStyle': 'App Style',
      'planLabel': 'Plan',
      'privacyLabel': 'Privacy',
      'helpLabel': 'Help',
      'settingsLabel': 'Settings',
      'logout': 'Log Out',
      'paywallTitle': 'Upgrade MakanMana',
      'planFree': 'Free',
      'planPlus': 'Plus',
      'planPro': 'Pro',
      'perMonth': '/month',
      'currentPlan': 'Current plan',
      'upgradeNow': 'Upgrade now',
      'mockNotice': 'Real purchases will be enabled later.',
      'spinThemeTitle': 'Spin Theme',
      'themeMagicPlate': 'Magic Plate',
      'themeRodaMisteri': 'Roda Misteri',
      'themeShuffleCard': 'Shuffle Card',
      'themeNearbyRadar': 'Nearby Radar',
      'lockedPlus': 'Needs Plus',
      'comingSoon': 'Coming soon!',
      'openMap': 'Open Maps',
      'share': 'Share',
      'save': 'Save',
      'quickInfo': 'Quick info',
      'whyFits': 'Why this fits you',
      'mapPlaceholder': 'Map coming soon',
      'spinning': 'Picking one for you...',
      'proBadge': 'PRO',
      'plusBadge': 'PLUS',
      'previewNotice': 'This is a preview. Unlock full with an upgrade.',
      'spinToday': 'Spins today',
      'spinLimitReached':
          'Free spins used up for today! Upgrade to Plus for unlimited spins.',
      'statMeals': 'Meals',
      'statSpend': 'Spend',
      'statPlaces': 'Places',
      'noResults': 'No results found',
      'feedTitle': 'Makan Feed',
      'feedAteAt': 'ate at',
      'feedEmpty': 'No posts yet. Be the first — spin and jom makan!',
      'justNow': 'just now',
      'minAgo': 'min ago',
      'hourAgo': 'hr ago',
      'dayAgo': 'd ago',
      'composeHint': 'What are you eating today?',
      'postAction': 'Post',
      'feedTab': 'Feed',
      'groupsTab': 'Groups',
      'camera': 'Camera',
      'gallery': 'Gallery',
      'createGroup': 'Create Group',
      'groupName': 'Group name',
      'join': 'Join',
      'leaveGroup': 'Leave group',
      'deletePost': 'Delete this post?',
      'cancelAction': 'Cancel',
      'deleteAction': 'Delete',
      'postSent': 'Posted.',
      'postFailed': 'Could not post. Check your internet and try again.',
      'adminTitle': 'Admin Review',
      'approveAction': 'Approve',
      'rejectAction': 'Reject',
      'noPending': 'No reviews awaiting moderation.',
      'editProfileTitle': 'Edit Profile',
      'displayNameLabel': 'Display name',
      'displayNameHint': 'Your name',
      'usernameLabel': 'Username',
      'usernameHint': 'your_username',
      'saveAction': 'Save',
      'profileSaved': 'Profile updated!',
      'usernameTaken': 'Username already taken. Try another.',
      'favoritesTitle': 'Favorites',
      'favoritesEmpty':
          'No favorites yet. Tap 🔖 on any restaurant to save it!',
      'favoriteAdded': 'Saved to Favorites!',
      'editTaste': 'Edit taste',
      'memoryIntro': 'MakanMana has learned from',
      'faq1Q': 'How does MakanMana pick restaurants for me?',
      'faq1A':
          'We consider location, budget, mood, taste, meal history and your ratings — the more you use it, the smarter it gets.',
      'faq2Q': 'What is the difference between Free, Plus and Pro?',
      'faq2A':
          'Free: 3 spins/day & basics. Plus: unlimited spins, all moods & themes, favorites. Pro: everything + Weekly Report, AI Coach, Diet Goal, Meal Plan, Calorie Scan, Group Decision.',
      'faq3Q': 'How do I rate a restaurant?',
      'faq3A':
          'From History (after eating via the app), or Check-in for 5 minutes at the restaurant, or "Ordered delivery?" (admin reviewed).',
      'faq4Q': 'Is my data safe?',
      'faq4A':
          'Yes. Your personal data is only accessible by your own account. The feed only shows the name & photo you choose.',
      'faq5Q': 'How do I cancel my subscription?',
      'faq5A':
          'Via Google Play > Subscriptions. Your plan stays active until the renewal date.',
      'scanIntro': 'Snap your food — AI will analyse the calories.',
      'scanning': 'AI is analysing your food...',
      'scanFailed': 'Analysis failed. Check your internet and try again.',
      'groupIntro':
          'Create a voting session, share the code to your group chat, everyone votes — results live. No more "anything la"!',
      'createSession': 'Create Voting Session',
      'joinSession': 'Join With Code',
      'sessionNotFound': 'Session not found. Check the code.',
      'sessionCode': 'SESSION CODE',
      'shareCode': 'Share',
      'votesLabel': 'votes so far',
      'voteTitle': 'Vote Makan',
      'voteHint': 'Tap an option to vote. Change anytime.',
      'orLabel': 'OR',
      'commentsTitle': 'Comments',
      'commentHint': 'Write a comment...',
      'noComments': 'No comments yet. Start the conversation!',
      'proHubTitle': 'Pro Tools',
      'proHubTeaser':
          'All AI Food Coach tools live here. Upgrade to Pro to unlock!',
      'lockedPro': 'Pro feature —upgrade to unlock.',
      'soonBadge': 'COMING SOON',
      'proReportTitle': 'Weekly Report',
      'proReportDesc': '7-day analysis: meals, spend, health, patterns.',
      'proCoachTitle': 'AI Food Coach',
      'proCoachDesc': 'Personal tips from your real eating patterns.',
      'proGoalTitle': 'Diet Goal',
      'proGoalDesc': 'Your goal reshapes every suggestion.',
      'proPlanTitle': 'Meal Plan',
      'proPlanDesc': '3-day meal plan from places near you.',
      'proScanTitle': 'Calorie Scan',
      'proScanDesc': 'Snap your food, get calorie estimates.',
      'proGroupTitle': 'Group Decision',
      'proGroupDesc': 'Group food voting without the drama.',
      'healthyLabel': 'Healthy',
      'varietyLabel': 'Variety',
      'satisfactionLabel': 'Satisfaction',
      'favoritePlaceLabel': 'Favorite spot',
      'topCuisinesLabel': 'Most frequent cuisines',
      'coachIntro':
          'Hey! I analysed your eating patterns this week. Here is what I found:',
      'coachNoData': 'Not enough data yet. Spin and makan first!',
      'goalIntro':
          'Pick your goal — every MakanMana suggestion will automatically support it.',
      'goalSihat': 'Healthy',
      'goalSihatDesc': 'Prioritise healthy, balanced options.',
      'goalJimat': 'Budget',
      'goalJimatDesc': 'Prioritise wallet-friendly places.',
      'goalSeimbang': 'Balanced',
      'goalSeimbangDesc': 'A mix of healthy, tasty and affordable.',
      'goalSaved': 'Diet Goal saved! Next suggestions will follow.',
      'regeneratePlan': 'Regenerate',
      'slotBreakfast': 'Breakfast',
      'slotLunch': 'Lunch',
      'slotDinner': 'Dinner',
      'dayToday': 'Today',
      'dayTomorrow': 'Tomorrow',
      'dayAfter': 'Day after',
      'confirmPurchase': 'Upgrade to',
      'planUpdated': 'Plan updated.',
      'downgradeFree': 'Switch to Free',
      'unlockWithPlus': 'Unlock with Plus',
      'unlockWithPro': 'Unlock with Pro',
      'rateTitle': 'Rate Restaurant',
      'rateShort': 'Rate',
      'rateAction': 'Rate now',
      'reviewHint': 'Share your experience... (optional)',
      'submitReview': 'Submit Rating',
      'shareToFeed': 'Share to Makan Feed',
      'reviewSent': 'Rating submitted. Thank you!',
      'reviewPending': 'Rating submitted — pending admin review',
      'reviewNotEligible':
          'Not eligible yet — make sure you have been at the restaurant for 5 minutes.',
      'deliveryPendingNote':
          'Delivery ratings are reviewed before being shown.',
      'checkinAction': 'Check-in',
      'checkinDone': 'Checked in! You can rate after 5 minutes here.',
      'rateWaitPrefix': 'Rate in',
      'communityRatingLabel': 'MakanMana Community',
      'reviewsTitle': 'Community reviews',
      'noReviews': 'No reviews yet. Be the first!',
      'deliveryRate': 'Ordered delivery?',
      'howWasMeal': 'How was your meal at',
      'fitCoachTitle': 'Fit Coach',
      'fitCoachTeaser': 'Daily score, workouts and healthier menu picks.',
      'fitSetupPrompt': 'Complete your Fit profile to start.',
      'fitWorkoutDone': 'Workout done',
      'fitWorkoutPending': 'Workout pending',
      'fitStepsUnit': 'steps',
      'fitLockedTitle': 'Fit Coach is a Pro feature',
      'fitLockedBody':
          'This preview shows the score, workout and menu coaching unlocked with Pro.',
      'fitUpgradeCta': 'Upgrade to Pro',
      'fitLogThis': 'Log this',
      'fitLogged': 'logged',
      'fitLogMealTitle': 'Log meal',
      'fitQuickLog': 'Quick Log',
      'fitManualLog': 'Manual',
      'fitMealName': 'Meal name',
      'fitSaveLog': 'Save log',
      'fitFbDone': 'Done',
      'fitFbEasy': 'Too easy',
      'fitFbHard': 'Too hard',
      'fitFbNoTime': 'No time',
      'fitFbPain': 'Pain',
      'fitFbTitle': 'How was the workout?',
      'fitPainWarning':
          'Workout recorded. If pain continues, please consult a qualified professional.',
      'fitFbThanks': 'Feedback recorded.',
      'fitSetupTitle': 'Set up Fit Coach',
      'fitSetupBody':
          'Add your body basics, goal and training style so MakanMana can calculate safer targets.',
      'fitBodyBasics': 'Body basics',
      'fitHeight': 'Height',
      'fitWeight': 'Weight',
      'fitAge': 'Age',
      'fitGender': 'Gender',
      'fitMale': 'Male',
      'fitFemale': 'Female',
      'fitGoalTitle': 'Fit goal',
      'fitGoalHealthy': 'Healthy lifestyle',
      'fitGoalFatLoss': 'Fat loss',
      'fitGoalLean': 'Lean body',
      'fitGoalRecomp': 'Body recomp',
      'fitGoalMuscle': 'Muscle gain',
      'fitGoalSport': 'Sport performance',
      'fitLevel': 'Level',
      'fitLevelBeginner': 'Beginner',
      'fitLevelIntermediate': 'Intermediate',
      'fitLevelAdvanced': 'Advanced',
      'fitLevelAthlete': 'Athlete',
      'fitTrainingPref': 'Training',
      'fitDaysPerWeek': 'Training days per week',
      'fitSessionDuration': 'Session duration',
      'fitTargets': 'Daily targets',
      'fitBudgetMin': 'Min budget',
      'fitBudgetMax': 'Max budget',
      'fitStepTarget': 'Step target',
      'fitSaveProfile': 'Save Fit profile',
      'fitStartSetup': 'Start setup',
      'fitEditProfile': 'Edit Fit profile',
      'fitTodayTitle': 'Fit Today',
      'fitNutritionTargets': 'Nutrition targets',
      'fitWater': 'Water',
      'fitLogWater': 'Log water',
      'fitLogSteps': 'Log steps',
      'fitLogWeight': 'Log weight',
      'fitWorkoutToday': 'Today workout',
      'fitChangeMood': 'Change mood',
      'fitFinishWorkout': 'Finish workout',
      'fitMenuSuggestions': 'Menu picks for today',
      'fitMonitorTitle': 'Fit Monitor',
      'fitWeeklyScore': 'Weekly Fit Score',
      'fitStepsTrend': 'Steps trend',
      'fitCaloriesTrend': 'Calories trend',
      'fitBodyTrend': 'Body trend',
      'fitBodyTrendEmpty': 'Not enough body entries for a chart yet.',
      'fitWeeklyReport': 'Weekly report',
      'fitRecentWorkouts': 'Recent workouts',
      'fitNoWorkoutYet': 'No workouts recorded yet.',
      'fitSampleReport':
          'This week looks consistent. Keep protein steady and add a few more steps.',
      'fitSampleRecProtein': 'Add protein at breakfast to support recovery.',
      'fitSampleRecSteps': 'Walk 10 minutes after lunch.',
      'fitSportMoodTitle': 'Sport Mood',
      'fitSportMoodIntro':
          'Pick today training style. MakanMana will tune your workout and food focus.',
      'historyTabMeals': 'Meals',
      'historyTabFitness': 'Fitness',
      'historyTabMonitor': 'Monitor',
      'historyTabReports': 'Reports',
      'fitTodayLogs': 'Today\'s logs',
      'fitNoLogsToday': 'No logs yet today. Start with your first meal.',
      'fitOpenMonitor': 'Open full Monitor',
      'fitReportTitle': 'Weekly Food & Fitness Report',
      'fitReportTeaser':
          'Every Sunday, your coach summarises training, steps, protein and eating patterns.',
      'fitTrainingDone': 'Training done',
      'fitAvgSteps': 'Avg steps',
      'fitAvgCalories': 'Avg calories',
      'fitProteinHit': 'Protein hit rate',
      'fitViewFullReport': 'View full report',
      'fitWeekStats': 'This week\'s stats',
      'fitHealthyMeals': 'Balanced meals',
      'fitHeavyMeals': 'Heavy meals',
      'fitSugaryDrinks': 'Sugary drinks',
      'fitNextWeek': 'Next week focus',
      'fitNoDataYet': 'Not enough data yet. Log meals & workouts to begin.',
      'fitWearable': 'Wearable Connection',
      'fitWearableSoon':
          'Coming soon: sync steps, workouts, heart rate and sleep from your smartwatch.',
      'fitWearableView': 'View devices',
      'fitHealthPermTitle': 'Health Permissions',
      'fitPermSteps': 'Steps',
      'fitPermWorkout': 'Workouts',
      'fitPermCalories': 'Calories burned',
      'fitPermDistance': 'Distance',
      'fitPermHeart': 'Heart rate',
      'fitPermSleep': 'Sleep',
      'fitPermNote':
          'You are in full control of your health data. Turn off any permission at any time and the related data stops syncing.',
      'fitLogScan': 'Log to Fit Coach',
      'fitStreakDays': 'day streak',
      'noGroups': 'No groups yet. Create your first makan group!',
    },
    'zh': {
      // V4 Tong-Tong Bill
      'ttBillNew': '新账单',
      'ttListIntro': '分摊聚餐账单。记录谁吃了什么、谁付了、谁还没付 — 没有纠纷。',
      'ttNoBills': '还没有 Tong-Tong 账单',
      'ttEmptyDesc': '创建第一个账单，分摊嘛嘛档、咖啡馆聚会或团体晚餐。',
      'ttMakeBill': '创建账单',
      'ttBillFallback': '餐饮账单',
      'ttPeople': '人',
      'ttUnpaidSuffix': '未付',
      'ttAllDone': '全部结清',
      'ttStatusCancelled': '已取消',
      'ttAddParticipant': '添加参与者',
      'ttFriendName': '朋友姓名',
      'ttItemName': '项目名称',
      'ttWhoEats': '谁吃了？（留空 = 所有人）',
      'ttNeedTotal2': '需要总额 + 至少 2 名参与者',
      'ttPlaceEat': '用餐地点',
      'ttTotalBill': '账单总额 (RM)',
      'ttSplitWay': '分账方式',
      'ttSplitByItem': '按项目',
      'ttSplitCustom': '自定义',
      'ttParticipantsLabel': '参与者',
      'ttPayFirstLower': '先付',
      'ttAddItemHint': '添加项目 + 标记谁吃了。',
      'ttCalcMake': '计算并创建',
      'ttNotFound': '找不到账单',
      'ttBillShort': '账单',
      'ttTotalWord': '总额',
      'ttWhoPaysWho': '谁付给谁',
      'ttShareWhatsapp': '分享到 WhatsApp',
      'ttPaid': '已付',
      'ttPending': '待确认',
      'ttWaived': '已豁免',
      'ttUnpaid': '未付',
      'ttPayFirst': '先付',
      'ttOwes': '欠',
      'ttNoDebt': '无欠款',
      'ttMarkPaid': '标记已付',
      'taxSearch': '搜索...',
      'taxSelected': '已选',
      // V4 Meal Wallet
      'walletBudgetTip': '预算设置',
      'walletLogMeal': '记录用餐',
      'walletTotalToday': '今日餐饮总额',
      'walletThisWeek': '本周',
      'walletThisMonth': '本月',
      'walletBudgetSample':
          '预算教练：甜饮占本周消费的 18%。剩余预算 RM58 — '
              '接下来 4 餐尽量每餐控制在 RM14 以下。',
      'walletRemaining': '剩余预算',
      'walletToday': '今天',
      'walletWeek': '本周',
      'walletMonth': '本月',
      'walletLogCount': '本月记录',
      'walletDrinkSpend': '饮料消费',
      'walletAvgMeal': '每餐平均',
      'walletTopPlace': '最常去的地点',
      'walletRecentLog': '最近记录',
      'walletNoLog': '还没有记录。点击「记录用餐」开始。',
      'walletMealFallback': '用餐',
      'walletLogFallback': '用餐记录',
      'walletDelete': '删除',
      'walletBudgetLimit': '预算上限 (RM)',
      'walletDaily': '每日',
      'walletWeekly': '每周',
      'walletMonthly': '每月',
      'walletBudgetStyle': '预算风格',
      'walletModeRelaxed': '轻松',
      'walletModeBalanced': '平衡',
      'walletModeStrict': '严格',
      'walletBudgetSaved': '预算已保存',
      'walletSaveBudget': '保存预算',
      'walletPlaceOptional': '地点 / 店铺（可选）',
      'walletTotalRequired': '餐饮总额 (RM) *',
      'walletItemOptional': '项目（可选）',
      'walletItemHint': '例：鸡饭 RM9 • 冰茶 RM2.50。总额自动计算。',
      'walletAddItem': '添加项目',
      'walletItemNameHint': '例：鸡饭 / 冰茶',
      'walletPriceHint': '价格 (RM)',
      'itemFood': '食物',
      'itemDrink': '饮料',
      'itemDessert': '甜点',
      'itemAddon': '附加',
      'itemService': '服务/税',
      'itemDelivery': '外送',
      'walletAdd': '添加',
      'walletItem': '项目',
      'walletDetails': '详情',
      'walletPhotoTitle': '食物与收据照片',
      'walletPhotoUpsell': '升级 Plus 以保存食物与收据照片。',
      'walletReceipt': '收据',
      'walletNoteOptional': '备注（可选）',
      'walletSaving': '保存中...',
      'walletSaveToWallet': '保存到 Meal Wallet',
      'walletRecorded': '已记录到 Meal Wallet',
      // V4 Social + Group Hub
      'feedForYou': '为你推荐',
      'feedFollowing': '关注中',
      'feedNearby': '附近',
      'feedTrending': '热门',
      'followingEmpty': '关注他人以查看他们的动态',
      'nearbyEmpty': '附近还没有动态',
      'trendingEmpty': '暂无热门内容',
      'foodProfileTitle': '美食档案',
      'myFoodProfile': '我的美食档案',
      'editFoodProfile': '编辑美食档案',
      'publicPostsTitle': '公开动态',
      'noPublicPosts': '还没有公开动态',
      'follow': '关注',
      'following': '已关注',
      'statPosts': '动态',
      'statFollowers': '粉丝',
      'statFollowing': '关注',
      'statReviews': '评价',
      'emptyFollowList': '这里还没有人',
      'mute': '静音',
      'unmute': '取消静音',
      'block': '屏蔽',
      'unblock': '取消屏蔽',
      'report': '举报',
      'reportSent': '举报已发送，谢谢。',
      'bioLabel': '简介',
      'bioHint': '介绍一下你的美食口味...',
      'favFoodLabel': '最爱食物',
      'favCuisineLabel': '最爱菜系',
      'foodMoodLabel': '美食心情',
      'dietPrefLabel': '饮食偏好',
      'budgetRangeLabel': '预算范围',
      'showDietPublic': '在档案显示饮食',
      'showBudgetPublic': '在档案显示预算',
      'optionalPrivacyNote': '可选信息 — 仅在你愿意时分享。',
      'privateNote': '位置和健康状态始终私密。',
      'chooseVisibility': '谁可以看到？',
      'visPublic': '公开',
      'visPublicDesc': '任何人都可看到',
      'visFollowers': '仅粉丝',
      'visFollowersDesc': '只有你的粉丝可看到',
      'visGroup': '仅群组',
      'visGroupDesc': '只有群组成员',
      'visPrivate': '私密',
      'visPrivateDesc': '只有你可看到',
      'visUnlisted': '不公开列出',
      'visUnlistedDesc': '仅通过链接',
      'shareAction': '分享',
      'sharedOk': '已分享！',
      'shareToGroup': '分享到群组',
      'shareCardSuggestion': 'AI 推荐',
      'shareCardBudget': '预算洞察',
      'shareCardGroupResult': '群组结果',
      'shareCardPoll': '投票',
      'shareCardWallet': '消费分享',
      'myActivityTitle': '我的活动',
      'mealWalletTitle': 'Meal Wallet',
      'tongTongTitle': 'Tong-Tong 分账',
      'myGroups': '我的群组',
      'discoverGroups': '发现群组',
      'membersLabel': '成员',
      'joinGroup': '加入群组',
      'groupTabFeed': '动态',
      'groupTabPolls': '投票',
      'groupTabBills': '账单',
      'groupTabMembers': '成员',
      'groupSettings': '群组设置',
      'groupInfo': '群组信息',
      'groupDesc': '群组简介',
      'groupStatusTitle': '成员状态',
      'pinnedAnnouncement': '置顶公告',
      'pinAnnouncement': '置顶公告',
      'announcementHint': '写群组公告...',
      'savedOk': '已保存',
      'roleOwner': '群主',
      'roleAdmin': '管理员',
      'roleMember': '成员',
      'roleViewer': '旁观者',
      'removeMember': '移除成员',
      'ownerCantLeave': '群主无法离开群组。',
      'createPoll': '创建投票',
      'pollQuestionHint': '投票问题...',
      'pollType': '投票类型',
      'pollOptions': '投票选项',
      'pollOption': '选项',
      'addOption': '添加选项',
      'pollClosed': '已关闭',
      'noPolls': '还没有投票',
      'pollRestaurant': '餐厅',
      'pollCuisine': '菜系',
      'pollTime': '时间',
      'pollBudget': '预算',
      'pollMenu': '菜单',
      'pollLocation': '地点',
      'pollHealth': '健康',
      'shareStatus': '分享状态',
      'shareStatusDesc': '让大家知道你的用餐心情。',
      'hungerLevel': '饥饿程度',
      'allergyWarning': '过敏警告',
      'locationArea': '所在区域',
      'shareFitnessGoal': '分享健身目标',
      'fitnessPrivateNote': '默认私密。',
      'fitnessGoalLabel': '健身目标',
      'statusMoodHint': '例：想吃辣',
      'statusCuisineHint': '例：Mamak',
      'statusAllergyHint': '例：花生过敏',
      'statusAreaHint': '例：Bangi',
      'statusFitnessHint': '例：增肌',
      'newBill': '新账单',
      'noBills': '还没有账单',
      'billActive': '进行中',
      'billSettled': '已结清',
      'billPlace': '地点名称',
      'billTotal': '账单总额',
      'splitMethod': '分账方式',
      'splitEqual': '平均分',
      'splitSponsor': '请客',
      'whoJoins': '谁参加？',
      'payerLabel': '付款人',
      'setPayer': '设为付款人',
      'createBill': '创建账单',
      'fillBillFields': '请填写地点、金额和成员。',
      'appName': 'MakanMana',
      'tagline': '今天吃什么？',
      'chooseLanguage': '选择你的语言',
      'continueLabel': '继续',
      'login': '登录',
      'email': '电子邮件',
      'password': '密码',
      'signIn': '登录',
      'createAccount': '注册账户',
      'haveAccount': '已有账户？登录',
      'noAccount': '还没有账户？注册',
      'signInGoogle': '使用 Google 登录',
      'devMode': 'Firebase 尚未连接。可用开发模式。',
      'devContinue': '继续（开发模式）',
      'authError': '登录失败。请检查邮箱和密码。',
      'onbTitle': '让我们了解你的口味',
      'onbDiet': '你的饮食类型？',
      'onbHalal': '清真偏好？',
      'onbAllergies': '有过敏吗？',
      'onbBudget': '平常用餐预算 (RM)',
      'onbCuisine': '喜欢的菜系？',
      'onbSpicy': '你的辣度？',
      'onbMealTimes': '平常用餐时间？',
      'next': '下一步',
      'back': '返回',
      'finish': '完成！',
      'dietNone': '不限',
      'dietVegetarian': '素食',
      'dietVegan': '纯素',
      'dietPescatarian': '鱼素',
      'halalYes': '只要清真',
      'halalAny': '无所谓',
      'greetingMorning': '早上好',
      'greetingAfternoon': '中午好',
      'greetingEvening': '下午好',
      'greetingNight': '晚上好',
      'searchHint': '搜索食物或地点...',
      'yourArea': '你附近',
      'moodTitle': '今天的心情？',
      'moodPedas': '辣',
      'moodJimat': '省钱',
      'moodLapar': '很饿',
      'moodSurprise': '惊喜',
      'moodCafe': '咖啡馆',
      'moodHujan': '下雨天',
      'moodSupper': '宵夜',
      'moodHighRating': '高评分',
      'moodNearby': '只要附近',
      'moodHealthy': '健康模式',
      'aiPickTitle': 'AI 为你推荐',
      'matchLabel': '匹配',
      'spinNow': '开始转',
      'categories': '分类',
      'nearbyTitle': '你附近',
      'aiInsight': 'MakanMana 从你的选择中学习',
      'navHome': '主页',
      'navExplore': '探索',
      'navHistory': '历史',
      'navProfile': '我的',
      'letsEatHere': '就吃这家',
      'notFeeling': '不太想吃',
      'viewDetails': '查看详情',
      'whyPicked': '为什么推荐这家',
      'withinBudget': '在你平常的预算内',
      'nearLocation': '靠近你现在的位置',
      'fitsMood': '符合你的心情',
      'highRating': '高评分，人气旺',
      'openNow': '营业中',
      'closedNow': '已打烊',
      'rejectTitle': '为什么不想吃？',
      'rejectTooFar': '太远了',
      'rejectTooPricey': '太贵了',
      'rejectNotMood': '不是这个心情',
      'rejectAteRecently': '最近刚吃过',
      'rejectOther': '其他',
      'rejectThanks': '记下了！MakanMana 会学习。',
      'accepted': '好的！已记录你的口味。',
      'historyTitle': '用餐历史',
      'historyEmpty': '还没有用餐记录。\n转一下并接受推荐开始吧！',
      'weeklySummary': '本周总结',
      'profileTitle': '我的',
      'tasteProfile': '口味档案',
      'foodMemory': 'Food Memory',
      'dietBudget': '饮食与预算',
      'languageLabel': '语言',
      'appStyle': '应用风格',
      'planLabel': '套餐',
      'privacyLabel': '隐私',
      'helpLabel': '帮助',
      'settingsLabel': '设置',
      'logout': '退出登录',
      'paywallTitle': '升级 MakanMana',
      'planFree': 'Free',
      'planPlus': 'Plus',
      'planPro': 'Pro',
      'perMonth': '/月',
      'currentPlan': '当前套餐',
      'upgradeNow': '立即升级',
      'mockNotice': '真实购买稍后开放。',
      'spinThemeTitle': '转盘主题',
      'themeMagicPlate': 'Magic Plate',
      'themeRodaMisteri': 'Roda Misteri',
      'themeShuffleCard': 'Shuffle Card',
      'themeNearbyRadar': 'Nearby Radar',
      'lockedPlus': '需要 Plus',
      'comingSoon': '即将推出！',
      'openMap': '打开地图',
      'share': '分享',
      'save': '收藏',
      'quickInfo': '简要信息',
      'whyFits': '为什么适合你',
      'mapPlaceholder': '地图即将推出',
      'spinning': '正在为你挑选...',
      'proBadge': 'PRO',
      'plusBadge': 'PLUS',
      'previewNotice': '这是预览。升级解锁完整功能。',
      'spinToday': '今日转盘',
      'spinLimitReached': '今天的免费转盘用完了！升级 Plus 无限转。',
      'statMeals': '用餐',
      'statSpend': '花费',
      'statPlaces': '地点',
      'noResults': '没有找到结果',
      'feedTitle': '美食动态',
      'feedAteAt': '吃了',
      'feedEmpty': '还没有动态。快来转一转，做第一个发帖的人！',
      'justNow': '刚刚',
      'minAgo': '分钟前',
      'hourAgo': '小时前',
      'dayAgo': '天前',
      'composeHint': '今天吃了什么？',
      'postAction': '发布',
      'feedTab': '动态',
      'groupsTab': '群组',
      'camera': '相机',
      'gallery': '相册',
      'createGroup': '创建群组',
      'groupName': '群组名称',
      'join': '加入',
      'leaveGroup': '退出群组',
      'deletePost': '删除这条帖子？',
      'cancelAction': '取消',
      'deleteAction': '删除',
      'postSent': '已发布！🎉',
      'postFailed': '发布失败。请检查网络后重试。',
      'adminTitle': '管理员审核',
      'approveAction': '批准',
      'rejectAction': '拒绝',
      'noPending': '没有待审核的评价。',
      'editProfileTitle': '编辑资料',
      'displayNameLabel': '显示名称',
      'displayNameHint': '你的名字',
      'usernameLabel': '用户名',
      'usernameHint': 'your_username',
      'saveAction': '保存',
      'profileSaved': '资料已更新！✨',
      'usernameTaken': '用户名已被占用，换一个吧。',
      'favoritesTitle': '收藏',
      'favoritesEmpty': '还没有收藏。在任意餐厅点 🔖 保存！',
      'favoriteAdded': '已收藏！🔖',
      'editTaste': '修改口味',
      'memoryIntro': 'MakanMana 已学习了',
      'faq1Q': 'MakanMana 如何为我挑选餐厅？',
      'faq1A': '我们综合位置、预算、心情、口味、用餐历史和评分 — 越用越准。',
      'faq2Q': 'Free、Plus 和 Pro 有什么区别？',
      'faq2A':
          'Free：每天3次转盘和基础功能。Plus：无限转盘、所有心情和主题、收藏。Pro：全部+每周报告、AI教练、饮食目标、用餐计划、卡路里扫描、群组决定。',
      'faq3Q': '如何给餐厅评分？',
      'faq3A': '从历史记录（通过app用餐后）、或在餐厅签到5分钟、或选择"点了外卖？"（管理员审核）。',
      'faq4Q': '我的数据安全吗？',
      'faq4A': '安全。个人数据只有你自己的账户可以访问。动态只显示你选择的名字和头像。',
      'faq5Q': '如何取消订阅？',
      'faq5A': '通过 Google Play > 订阅。套餐将保持有效直到续订日期。',
      'scanIntro': '拍下你的食物 — AI 将分析卡路里。',
      'scanning': 'AI 正在分析你的食物...',
      'scanFailed': '分析失败。请检查网络后重试。',
      'groupIntro': '创建投票，分享代码到群聊，大家投票 — 实时出结果。不再有"随便啦"！',
      'createSession': '创建投票',
      'joinSession': '用代码加入',
      'sessionNotFound': '找不到会话，请检查代码。',
      'sessionCode': '会话代码',
      'shareCode': '分享',
      'votesLabel': '票',
      'voteTitle': '投票选餐',
      'voteHint': '点击选项投票，随时可以更改。',
      'orLabel': '或',
      'commentsTitle': '评论',
      'commentHint': '写评论...',
      'noComments': '还没有评论，来开启对话！',
      'proHubTitle': 'Pro 工具',
      'proHubTeaser': '所有AI美食教练工具都在这里。升级Pro解锁全部！',
      'lockedPro': 'Pro 功能 👑 — 升级解锁。',
      'soonBadge': '即将推出',
      'proReportTitle': '每周报告',
      'proReportDesc': '7天分析：用餐、花费、健康、习惯。',
      'proCoachTitle': 'AI 美食教练',
      'proCoachDesc': '基于你真实饮食习惯的个性化建议。',
      'proGoalTitle': '饮食目标',
      'proGoalDesc': '你的目标会改变每个推荐。',
      'proPlanTitle': '用餐计划',
      'proPlanDesc': '附近餐厅的3天用餐计划。',
      'proScanTitle': '卡路里扫描',
      'proScanDesc': '拍照即可估算卡路里。',
      'proGroupTitle': '群组决定',
      'proGroupDesc': '多人投票选餐厅，不再纠结。',
      'healthyLabel': '健康',
      'varietyLabel': '多样性',
      'satisfactionLabel': '满意度',
      'favoritePlaceLabel': '最爱地点',
      'topCuisinesLabel': '最常吃的菜系',
      'coachIntro': '嗨！我分析了你这周的饮食习惯，这是我的发现：',
      'coachNoData': '数据还不够。先去转一转吃一吃！',
      'goalIntro': '选择你的目标 — 每个推荐都会自动支持它。',
      'goalSihat': '健康',
      'goalSihatDesc': '优先健康均衡的选择。',
      'goalJimat': '省钱',
      'goalJimatDesc': '优先经济实惠的地点。',
      'goalSeimbang': '均衡',
      'goalSeimbangDesc': '健康、美味、实惠兼顾。',
      'goalSaved': '饮食目标已保存！🎯',
      'regeneratePlan': '重新生成',
      'slotBreakfast': '早餐',
      'slotLunch': '午餐',
      'slotDinner': '晚餐',
      'dayToday': '今天',
      'dayTomorrow': '明天',
      'dayAfter': '后天',
      'confirmPurchase': '升级到',
      'planUpdated': '套餐已更新！🎉',
      'downgradeFree': '切换到免费版',
      'unlockWithPlus': '用 Plus 解锁 ⭐',
      'unlockWithPro': '用 Pro 解锁 👑',
      'rateTitle': '评分',
      'rateShort': '评分',
      'rateAction': '立即评分',
      'reviewHint': '分享你的体验...（可选）',
      'submitReview': '提交评分',
      'shareToFeed': '分享到美食动态',
      'reviewSent': '评分已提交！⭐ 谢谢！',
      'reviewPending': '评分已提交 — 等待管理员审核',
      'reviewNotEligible': '暂不符合条件 — 请确保已在店内停留5分钟。',
      'deliveryPendingNote': '外卖评分将先经审核后才显示。',
      'checkinAction': '签到',
      'checkinDone': '签到成功！在此停留5分钟后即可评分。📍',
      'rateWaitPrefix': '可评分倒计时',
      'communityRatingLabel': 'MakanMana社区',
      'reviewsTitle': '社区评价',
      'noReviews': '还没有评价，来做第一个！',
      'deliveryRate': '点了外卖？',
      'howWasMeal': '这顿饭怎么样：',
      'fitCoachTitle': 'Fit Coach',
      'fitCoachTeaser': 'Daily score, workouts and healthier menu picks.',
      'fitSetupPrompt': 'Complete your Fit profile to start.',
      'fitWorkoutDone': 'Workout done',
      'fitWorkoutPending': 'Workout pending',
      'fitStepsUnit': 'steps',
      'fitLockedTitle': 'Fit Coach is a Pro feature',
      'fitLockedBody':
          'This preview shows the score, workout and menu coaching unlocked with Pro.',
      'fitUpgradeCta': 'Upgrade to Pro',
      'fitLogThis': 'Log this',
      'fitLogged': 'logged',
      'fitLogMealTitle': 'Log meal',
      'fitQuickLog': 'Quick Log',
      'fitManualLog': 'Manual',
      'fitMealName': 'Meal name',
      'fitSaveLog': 'Save log',
      'fitFbDone': 'Done',
      'fitFbEasy': 'Too easy',
      'fitFbHard': 'Too hard',
      'fitFbNoTime': 'No time',
      'fitFbPain': 'Pain',
      'fitFbTitle': 'How was the workout?',
      'fitPainWarning':
          'Workout recorded. If pain continues, please consult a qualified professional.',
      'fitFbThanks': 'Feedback recorded.',
      'fitSetupTitle': 'Set up Fit Coach',
      'fitSetupBody':
          'Add your body basics, goal and training style so MakanMana can calculate safer targets.',
      'fitBodyBasics': 'Body basics',
      'fitHeight': 'Height',
      'fitWeight': 'Weight',
      'fitAge': 'Age',
      'fitGender': 'Gender',
      'fitMale': 'Male',
      'fitFemale': 'Female',
      'fitGoalTitle': 'Fit goal',
      'fitGoalHealthy': 'Healthy lifestyle',
      'fitGoalFatLoss': 'Fat loss',
      'fitGoalLean': 'Lean body',
      'fitGoalRecomp': 'Body recomp',
      'fitGoalMuscle': 'Muscle gain',
      'fitGoalSport': 'Sport performance',
      'fitLevel': 'Level',
      'fitLevelBeginner': 'Beginner',
      'fitLevelIntermediate': 'Intermediate',
      'fitLevelAdvanced': 'Advanced',
      'fitLevelAthlete': 'Athlete',
      'fitTrainingPref': 'Training',
      'fitDaysPerWeek': 'Training days per week',
      'fitSessionDuration': 'Session duration',
      'fitTargets': 'Daily targets',
      'fitBudgetMin': 'Min budget',
      'fitBudgetMax': 'Max budget',
      'fitStepTarget': 'Step target',
      'fitSaveProfile': 'Save Fit profile',
      'fitStartSetup': 'Start setup',
      'fitEditProfile': 'Edit Fit profile',
      'fitTodayTitle': 'Fit Today',
      'fitNutritionTargets': 'Nutrition targets',
      'fitWater': 'Water',
      'fitLogWater': 'Log water',
      'fitLogSteps': 'Log steps',
      'fitLogWeight': 'Log weight',
      'fitWorkoutToday': 'Today workout',
      'fitChangeMood': 'Change mood',
      'fitFinishWorkout': 'Finish workout',
      'fitMenuSuggestions': 'Menu picks for today',
      'fitMonitorTitle': 'Fit Monitor',
      'fitWeeklyScore': 'Weekly Fit Score',
      'fitStepsTrend': 'Steps trend',
      'fitCaloriesTrend': 'Calories trend',
      'fitBodyTrend': 'Body trend',
      'fitBodyTrendEmpty': 'Not enough body entries for a chart yet.',
      'fitWeeklyReport': 'Weekly report',
      'fitRecentWorkouts': 'Recent workouts',
      'fitNoWorkoutYet': 'No workouts recorded yet.',
      'fitSampleReport':
          'This week looks consistent. Keep protein steady and add a few more steps.',
      'fitSampleRecProtein': 'Add protein at breakfast to support recovery.',
      'fitSampleRecSteps': 'Walk 10 minutes after lunch.',
      'fitSportMoodTitle': 'Sport Mood',
      'fitSportMoodIntro':
          'Pick today training style. MakanMana will tune your workout and food focus.',
      'historyTabMeals': '餐饮',
      'historyTabFitness': '健身',
      'historyTabMonitor': '监测',
      'historyTabReports': '报告',
      'fitTodayLogs': '今日记录',
      'fitNoLogsToday': '今天还没有记录，从第一餐开始吧。',
      'fitOpenMonitor': '打开完整监测面板',
      'fitReportTitle': '每周饮食与健身报告',
      'fitReportTeaser': '每周日，教练会总结你的训练、步数、蛋白质和饮食习惯。',
      'fitTrainingDone': '完成训练',
      'fitAvgSteps': '平均步数',
      'fitAvgCalories': '平均卡路里',
      'fitProteinHit': '蛋白质达标率',
      'fitViewFullReport': '查看完整报告',
      'fitWeekStats': '本周数据',
      'fitHealthyMeals': '均衡餐',
      'fitHeavyMeals': '重口味餐',
      'fitSugaryDrinks': '含糖饮料',
      'fitNextWeek': '下周重点',
      'fitNoDataYet': '数据不足。记录餐饮和训练即可开始。',
      'fitWearable': '穿戴设备连接',
      'fitWearableSoon': '即将推出：从智能手表同步步数、训练、心率和睡眠。',
      'fitWearableView': '查看设备',
      'fitHealthPermTitle': '健康权限',
      'fitPermSteps': '步数',
      'fitPermWorkout': '训练',
      'fitPermCalories': '消耗卡路里',
      'fitPermDistance': '距离',
      'fitPermHeart': '心率',
      'fitPermSleep': '睡眠',
      'fitPermNote': '你完全掌控自己的健康数据。随时可关闭任何权限，相关数据将停止同步。',
      'fitLogScan': '记录到 Fit Coach',
      'fitStreakDays': '天连续',
      'noGroups': '还没有群组，来创建第一个美食群吧！',
    },
    'ta': {
      // V4 Tong-Tong Bill
      'ttBillNew': 'புதிய பில்',
      'ttListIntro':
          'குழு உணவு பிலை பகிருங்கள். யார் எதை சாப்பிட்டார், யார் கட்டினார், '
              'யார் இன்னும் இல்லை — சிக்கல் இல்லாமல்.',
      'ttNoBills': 'இன்னும் Tong-Tong பில் இல்லை',
      'ttEmptyDesc':
          'மாமாக், கஃபே அல்லது குழு இரவு உணவை பிரிக்க முதல் பிலை உருவாக்குங்கள்.',
      'ttMakeBill': 'பில் உருவாக்கு',
      'ttBillFallback': 'உணவு பில்',
      'ttPeople': 'பேர்',
      'ttUnpaidSuffix': 'கட்டவில்லை',
      'ttAllDone': 'அனைத்தும் தீர்ந்தது',
      'ttStatusCancelled': 'ரத்து',
      'ttAddParticipant': 'பங்கேற்பாளர் சேர்',
      'ttFriendName': 'நண்பர் பெயர்',
      'ttItemName': 'பொருள் பெயர்',
      'ttWhoEats': 'யார் சாப்பிட்டார்? (காலி = அனைவரும்)',
      'ttNeedTotal2': 'மொத்தம் + குறைந்தது 2 பங்கேற்பாளர்கள் தேவை',
      'ttPlaceEat': 'உணவு இடம்',
      'ttTotalBill': 'மொத்த பில் (RM)',
      'ttSplitWay': 'பிரிக்கும் முறை',
      'ttSplitByItem': 'பொருள் வாரியாக',
      'ttSplitCustom': 'தனிப்பயன்',
      'ttParticipantsLabel': 'பங்கேற்பாளர்கள்',
      'ttPayFirstLower': 'முதலில் கட்டுகிறார்',
      'ttAddItemHint': 'பொருட்கள் சேர் + யார் சாப்பிட்டார் குறி.',
      'ttCalcMake': 'கணக்கிட்டு உருவாக்கு',
      'ttNotFound': 'பில் கிடைக்கவில்லை',
      'ttBillShort': 'பில்',
      'ttTotalWord': 'மொத்தம்',
      'ttWhoPaysWho': 'யார் யாருக்கு கட்டுகிறார்',
      'ttShareWhatsapp': 'WhatsApp-இல் பகிர்',
      'ttPaid': 'கட்டிவிட்டார்',
      'ttPending': 'உறுதி நிலுவையில்',
      'ttWaived': 'விலக்கு',
      'ttUnpaid': 'கட்டவில்லை',
      'ttPayFirst': 'முதலில் கட்டுகிறார்',
      'ttOwes': 'கடன்',
      'ttNoDebt': 'கடன் இல்லை',
      'ttMarkPaid': 'கட்டியதாக குறி',
      'taxSearch': 'தேடு...',
      'taxSelected': 'தேர்ந்தெடுக்கப்பட்டது',
      // V4 Meal Wallet
      'walletBudgetTip': 'பட்ஜெட் அமைப்பு',
      'walletLogMeal': 'உணவு பதிவு',
      'walletTotalToday': 'இன்றைய உணவு மொத்தம்',
      'walletThisWeek': 'இந்த வாரம்',
      'walletThisMonth': 'இந்த மாதம்',
      'walletBudgetSample':
          'பட்ஜெட் பயிற்சியாளர்: இனிப்பு பானங்கள் இந்த வார செலவில் 18%. '
              'மீதம் RM58 — அடுத்த 4 உணவுகளுக்கு RM14-க்கு கீழ் இலக்கு.',
      'walletRemaining': 'மீதி பட்ஜெட்',
      'walletToday': 'இன்று',
      'walletWeek': 'வாரம்',
      'walletMonth': 'மாதம்',
      'walletLogCount': 'இந்த மாத பதிவுகள்',
      'walletDrinkSpend': 'பானச் செலவு',
      'walletAvgMeal': 'சராசரி / உணவு',
      'walletTopPlace': 'அடிக்கடி செல்லும் இடம்',
      'walletRecentLog': 'சமீபத்திய பதிவுகள்',
      'walletNoLog': 'இன்னும் பதிவு இல்லை. "உணவு பதிவு" தட்டவும்.',
      'walletMealFallback': 'உணவு',
      'walletLogFallback': 'உணவு பதிவு',
      'walletDelete': 'நீக்கு',
      'walletBudgetLimit': 'பட்ஜெட் வரம்பு (RM)',
      'walletDaily': 'தினசரி',
      'walletWeekly': 'வாராந்திர',
      'walletMonthly': 'மாதாந்திர',
      'walletBudgetStyle': 'பட்ஜெட் பாணி',
      'walletModeRelaxed': 'நிதானம்',
      'walletModeBalanced': 'சமநிலை',
      'walletModeStrict': 'கண்டிப்பு',
      'walletBudgetSaved': 'பட்ஜெட் சேமிக்கப்பட்டது',
      'walletSaveBudget': 'பட்ஜெட் சேமி',
      'walletPlaceOptional': 'இடம் / கடை (விருப்பம்)',
      'walletTotalRequired': 'உணவு மொத்தம் (RM) *',
      'walletItemOptional': 'பொருட்கள் (விருப்பம்)',
      'walletItemHint':
          'எ.கா. சிக்கன் ரைஸ் RM9 • ஐஸ் டீ RM2.50. மொத்தம் தானாக கணக்கிடப்படும்.',
      'walletAddItem': 'பொருள் சேர்',
      'walletItemNameHint': 'எ.கா. சிக்கன் ரைஸ் / ஐஸ் டீ',
      'walletPriceHint': 'விலை (RM)',
      'itemFood': 'உணவு',
      'itemDrink': 'பானம்',
      'itemDessert': 'இனிப்பு',
      'itemAddon': 'கூடுதல்',
      'itemService': 'சேவை/வரி',
      'itemDelivery': 'டெலிவரி',
      'walletAdd': 'சேர்',
      'walletItem': 'பொருள்',
      'walletDetails': 'விவரங்கள்',
      'walletPhotoTitle': 'உணவு & ரசீது படங்கள்',
      'walletPhotoUpsell': 'உணவு & ரசீது படங்களை சேமிக்க Plus-க்கு மேம்படுத்து.',
      'walletReceipt': 'ரசீது',
      'walletNoteOptional': 'குறிப்பு (விருப்பம்)',
      'walletSaving': 'சேமிக்கிறது...',
      'walletSaveToWallet': 'Meal Wallet-இல் சேமி',
      'walletRecorded': 'Meal Wallet-இல் பதிவு செய்யப்பட்டது',
      // V4 Social + Group Hub
      'feedForYou': 'உங்களுக்காக',
      'feedFollowing': 'பின்தொடர்பவை',
      'feedNearby': 'அருகில்',
      'feedTrending': 'பிரபலம்',
      'followingEmpty': 'இடுகைகளை காண மக்களை பின்தொடருங்கள்',
      'nearbyEmpty': 'அருகில் இடுகைகள் இல்லை',
      'trendingEmpty': 'இன்னும் பிரபலம் எதுவும் இல்லை',
      'foodProfileTitle': 'உணவு சுயவிவரம்',
      'myFoodProfile': 'என் உணவு சுயவிவரம்',
      'editFoodProfile': 'உணவு சுயவிவரம் திருத்து',
      'publicPostsTitle': 'பொது இடுகைகள்',
      'noPublicPosts': 'பொது இடுகைகள் இல்லை',
      'follow': 'பின்தொடர்',
      'following': 'பின்தொடர்கிறீர்கள்',
      'statPosts': 'இடுகைகள்',
      'statFollowers': 'பின்தொடர்பவர்கள்',
      'statFollowing': 'பின்தொடர்கிறது',
      'statReviews': 'மதிப்புரைகள்',
      'emptyFollowList': 'இங்கே இன்னும் யாரும் இல்லை',
      'mute': 'முடக்கு',
      'unmute': 'முடக்கம் நீக்கு',
      'block': 'தடு',
      'unblock': 'தடையை நீக்கு',
      'report': 'புகார்',
      'reportSent': 'புகார் அனுப்பப்பட்டது. நன்றி.',
      'bioLabel': 'சுயவிவரம்',
      'bioHint': 'உங்கள் உணவு ரசனையை பகிருங்கள்...',
      'favFoodLabel': 'பிடித்த உணவு',
      'favCuisineLabel': 'பிடித்த உணவு வகை',
      'foodMoodLabel': 'உணவு மனநிலை',
      'dietPrefLabel': 'உணவு விருப்பம்',
      'budgetRangeLabel': 'பட்ஜெட் வரம்பு',
      'showDietPublic': 'சுயவிவரத்தில் உணவை காட்டு',
      'showBudgetPublic': 'சுயவிவரத்தில் பட்ஜெட்டை காட்டு',
      'optionalPrivacyNote': 'விருப்ப தகவல் — விரும்பினால் மட்டும் பகிரவும்.',
      'privateNote': 'இருப்பிடம் & உடல்நலம் எப்போதும் தனிப்பட்டது.',
      'chooseVisibility': 'யார் பார்க்கலாம்?',
      'visPublic': 'பொது',
      'visPublicDesc': 'யார் வேண்டுமானாலும் பார்க்கலாம்',
      'visFollowers': 'பின்தொடர்பவர்கள் மட்டும்',
      'visFollowersDesc': 'உங்கள் பின்தொடர்பவர்கள் மட்டுமே',
      'visGroup': 'குழு மட்டும்',
      'visGroupDesc': 'குழு உறுப்பினர்கள் மட்டும்',
      'visPrivate': 'தனிப்பட்ட',
      'visPrivateDesc': 'நீங்கள் மட்டுமே பார்க்கலாம்',
      'visUnlisted': 'பட்டியலிடப்படாத',
      'visUnlistedDesc': 'இணைப்பு வழியாக மட்டும்',
      'shareAction': 'பகிர்',
      'sharedOk': 'பகிரப்பட்டது!',
      'shareToGroup': 'குழுவிற்கு பகிர்',
      'shareCardSuggestion': 'AI பரிந்துரை',
      'shareCardBudget': 'பட்ஜெட் நுண்ணறிவு',
      'shareCardGroupResult': 'குழு முடிவு',
      'shareCardPoll': 'வாக்கெடுப்பு',
      'shareCardWallet': 'செலவு பகிர்வு',
      'myActivityTitle': 'என் செயல்பாடு',
      'mealWalletTitle': 'Meal Wallet',
      'tongTongTitle': 'Tong-Tong Bill',
      'myGroups': 'என் குழுக்கள்',
      'discoverGroups': 'குழுக்களை கண்டறி',
      'membersLabel': 'உறுப்பினர்கள்',
      'joinGroup': 'குழுவில் சேர்',
      'groupTabFeed': 'ஃபீட்',
      'groupTabPolls': 'வாக்கெடுப்பு',
      'groupTabBills': 'பில்கள்',
      'groupTabMembers': 'உறுப்பினர்கள்',
      'groupSettings': 'குழு அமைப்புகள்',
      'groupInfo': 'குழு தகவல்',
      'groupDesc': 'குழு விளக்கம்',
      'groupStatusTitle': 'உறுப்பினர் நிலை',
      'pinnedAnnouncement': 'பொருத்தப்பட்ட அறிவிப்பு',
      'pinAnnouncement': 'அறிவிப்பை பொருத்து',
      'announcementHint': 'குழு அறிவிப்பு எழுதுக...',
      'savedOk': 'சேமிக்கப்பட்டது',
      'roleOwner': 'உரிமையாளர்',
      'roleAdmin': 'நிர்வாகி',
      'roleMember': 'உறுப்பினர்',
      'roleViewer': 'பார்வையாளர்',
      'removeMember': 'உறுப்பினரை நீக்கு',
      'ownerCantLeave': 'உரிமையாளர் குழுவை விட்டு வெளியேற முடியாது.',
      'createPoll': 'வாக்கெடுப்பு உருவாக்கு',
      'pollQuestionHint': 'வாக்கெடுப்பு கேள்வி...',
      'pollType': 'வாக்கெடுப்பு வகை',
      'pollOptions': 'வாக்கெடுப்பு விருப்பங்கள்',
      'pollOption': 'விருப்பம்',
      'addOption': 'விருப்பம் சேர்',
      'pollClosed': 'மூடப்பட்டது',
      'noPolls': 'இன்னும் வாக்கெடுப்பு இல்லை',
      'pollRestaurant': 'உணவகம்',
      'pollCuisine': 'உணவு வகை',
      'pollTime': 'நேரம்',
      'pollBudget': 'பட்ஜெட்',
      'pollMenu': 'மெனு',
      'pollLocation': 'இருப்பிடம்',
      'pollHealth': 'ஆரோக்கியம்',
      'shareStatus': 'நிலையை பகிர்',
      'shareStatusDesc': 'உங்கள் உணவு மனநிலையை குழுவிற்கு தெரியப்படுத்துங்கள்.',
      'hungerLevel': 'பசி நிலை',
      'allergyWarning': 'ஒவ்வாமை எச்சரிக்கை',
      'locationArea': 'இருப்பிட பகுதி',
      'shareFitnessGoal': 'உடற்பயிற்சி இலக்கை பகிர்',
      'fitnessPrivateNote': 'இயல்பாக தனிப்பட்டது.',
      'fitnessGoalLabel': 'உடற்பயிற்சி இலக்கு',
      'statusMoodHint': 'எ.கா. காரம் வேண்டும்',
      'statusCuisineHint': 'எ.கா. மாமாக்',
      'statusAllergyHint': 'எ.கா. நட்டு ஒவ்வாமை',
      'statusAreaHint': 'எ.கா. பங்கி',
      'statusFitnessHint': 'எ.கா. பல்க்கிங்',
      'newBill': 'புதிய பில்',
      'noBills': 'இன்னும் பில் இல்லை',
      'billActive': 'செயலில்',
      'billSettled': 'தீர்ந்தது',
      'billPlace': 'இட பெயர்',
      'billTotal': 'மொத்த பில்',
      'splitMethod': 'பிரிக்கும் முறை',
      'splitEqual': 'சமமாக பிரி',
      'splitSponsor': 'உபசரிப்பு',
      'whoJoins': 'யார் சேர்கிறார்கள்?',
      'payerLabel': 'செலுத்துபவர்',
      'setPayer': 'செலுத்துபவராக்கு',
      'createBill': 'பில் உருவாக்கு',
      'fillBillFields': 'இடம், மொத்தம் & உறுப்பினர்களை நிரப்பவும்.',
      'appName': 'MakanMana',
      'tagline': 'இன்று என்ன சாப்பிடலாம்?',
      'chooseLanguage': 'உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்',
      'continueLabel': 'தொடரவும்',
      'login': 'உள்நுழைய',
      'email': 'மின்னஞ்சல்',
      'password': 'கடவுச்சொல்',
      'signIn': 'உள்நுழைய',
      'createAccount': 'கணக்கு உருவாக்க',
      'haveAccount': 'கணக்கு உள்ளதா? உள்நுழைய',
      'noAccount': 'கணக்கு இல்லையா? பதிவு செய்ய',
      'signInGoogle': 'Google மூலம் உள்நுழைய',
      'devMode': 'Firebase இணைக்கப்படவில்லை. Dev mode கிடைக்கிறது.',
      'devContinue': 'தொடரவும் (Dev Mode)',
      'authError': 'உள்நுழைவு தோல்வி. மின்னஞ்சல்/கடவுச்சொல் சரிபார்க்கவும்.',
      'onbTitle': 'உங்கள் சுவையை அறிவோம்',
      'onbDiet': 'உங்கள் உணவு வகை?',
      'onbHalal': 'ஹலால் விருப்பம்?',
      'onbAllergies': 'ஒவ்வாமை உள்ளதா?',
      'onbBudget': 'வழக்கமான உணவு பட்ஜெட் (RM)',
      'onbCuisine': 'பிடித்த சமையல்?',
      'onbSpicy': 'காரம் அளவு?',
      'onbMealTimes': 'வழக்கமான உணவு நேரம்?',
      'next': 'அடுத்து',
      'back': 'பின்',
      'finish': 'முடிந்தது!',
      'dietNone': 'எல்லாம்',
      'dietVegetarian': 'சைவம்',
      'dietVegan': 'வீகன்',
      'dietPescatarian': 'மீன் சைவம்',
      'halalYes': 'ஹலால் மட்டும்',
      'halalAny': 'எதுவும் சரி',
      'greetingMorning': 'காலை வணக்கம்',
      'greetingAfternoon': 'மதிய வணக்கம்',
      'greetingEvening': 'மாலை வணக்கம்',
      'greetingNight': 'இரவு வணக்கம்',
      'searchHint': 'உணவு அல்லது இடம் தேடவும்...',
      'yourArea': 'உங்கள் அருகில்',
      'moodTitle': 'இன்றைய மனநிலை?',
      'moodPedas': 'காரம்',
      'moodJimat': 'சிக்கனம்',
      'moodLapar': 'பசி',
      'moodSurprise': 'சர்ப்ரைஸ்',
      'moodCafe': 'கஃபே சில்',
      'moodHujan': 'மழை நாள்',
      'moodSupper': 'இரவு உணவு',
      'moodHighRating': 'உயர் மதிப்பீடு',
      'moodNearby': 'அருகில் மட்டும்',
      'moodHealthy': 'ஆரோக்கியம்',
      'aiPickTitle': 'AI உங்களுக்காக தேர்வு',
      'matchLabel': 'பொருத்தம்',
      'spinNow': 'இப்போது சுழற்று',
      'categories': 'வகைகள்',
      'nearbyTitle': 'உங்கள் அருகில்',
      'aiInsight': 'MakanMana உங்கள் தேர்வுகளில் இருந்து கற்கிறது',
      'navHome': 'முகப்பு',
      'navExplore': 'ஆராய',
      'navHistory': 'வரலாறு',
      'navProfile': 'சுயவிவரம்',
      'letsEatHere': 'இங்கே சாப்பிடலாம்',
      'notFeeling': 'வேண்டாம்',
      'viewDetails': 'விவரம் பார்க்க',
      'whyPicked': 'ஏன் இதை தேர்ந்தது',
      'withinBudget': 'உங்கள் வழக்கமான பட்ஜெட்டில்',
      'nearLocation': 'உங்கள் இருப்பிடத்திற்கு அருகில்',
      'fitsMood': 'உங்கள் மனநிலைக்கு பொருத்தம்',
      'highRating': 'உயர் மதிப்பீடு & பிரபலமானது',
      'openNow': 'இப்போது திறந்துள்ளது',
      'closedNow': 'மூடப்பட்டது',
      'rejectTitle': 'ஏன் வேண்டாம்?',
      'rejectTooFar': 'மிக தூரம்',
      'rejectTooPricey': 'மிக விலை',
      'rejectNotMood': 'இந்த மனநிலை இல்லை',
      'rejectAteRecently': 'சமீபத்தில் சாப்பிட்டேன்',
      'rejectOther': 'மற்றவை',
      'rejectThanks': 'சரி! MakanMana இதிலிருந்து கற்கும்.',
      'accepted': 'சூப்பர்! உங்கள் சுவை பதிவானது.',
      'historyTitle': 'உணவு வரலாறு',
      'historyEmpty': 'இன்னும் பதிவுகள் இல்லை.\nசுழற்றி பரிந்துரையை ஏற்கவும்!',
      'weeklySummary': 'இந்த வார சுருக்கம்',
      'profileTitle': 'சுயவிவரம்',
      'tasteProfile': 'சுவை விவரம்',
      'foodMemory': 'Food Memory',
      'dietBudget': 'உணவு & பட்ஜெட்',
      'languageLabel': 'மொழி',
      'appStyle': 'App Style',
      'planLabel': 'திட்டம்',
      'privacyLabel': 'தனியுரிமை',
      'helpLabel': 'உதவி',
      'settingsLabel': 'அமைப்புகள்',
      'logout': 'வெளியேறு',
      'paywallTitle': 'MakanMana மேம்படுத்த',
      'planFree': 'Free',
      'planPlus': 'Plus',
      'planPro': 'Pro',
      'perMonth': '/மாதம்',
      'currentPlan': 'தற்போதைய திட்டம்',
      'upgradeNow': 'இப்போது மேம்படுத்து',
      'mockNotice': 'உண்மையான கொள்முதல் பின்னர் இயக்கப்படும்.',
      'spinThemeTitle': 'Spin Theme',
      'themeMagicPlate': 'Magic Plate',
      'themeRodaMisteri': 'Roda Misteri',
      'themeShuffleCard': 'Shuffle Card',
      'themeNearbyRadar': 'Nearby Radar',
      'lockedPlus': 'Plus தேவை',
      'comingSoon': 'விரைவில்!',
      'openMap': 'வரைபடம் திற',
      'share': 'பகிர்',
      'save': 'சேமி',
      'quickInfo': 'விரைவு தகவல்',
      'whyFits': 'ஏன் உங்களுக்கு பொருத்தம்',
      'mapPlaceholder': 'வரைபடம் விரைவில்',
      'spinning': 'உங்களுக்காக தேர்கிறது...',
      'proBadge': 'PRO',
      'plusBadge': 'PLUS',
      'previewNotice': 'இது முன்னோட்டம். மேம்படுத்தி முழுமையாக திறக்கவும்.',
      'spinToday': 'இன்றைய சுழற்சி',
      'spinLimitReached':
          'இன்றைய இலவச சுழற்சி முடிந்தது! வரம்பில்லா சுழற்சிக்கு Plus மேம்படுத்தவும்.',
      'statMeals': 'உணவு',
      'statSpend': 'செலவு',
      'statPlaces': 'இடங்கள்',
      'noResults': 'முடிவுகள் இல்லை',
      'feedTitle': 'உணவு ஃபீட்',
      'feedAteAt': 'இல் சாப்பிட்டார்',
      'feedEmpty':
          'இன்னும் பதிவுகள் இல்லை. முதலில் நீங்கள் — சுழற்றி சாப்பிடுங்கள்!',
      'justNow': 'இப்போதுதான்',
      'minAgo': 'நிமிடம் முன்',
      'hourAgo': 'மணி முன்',
      'dayAgo': 'நாள் முன்',
      'composeHint': 'இன்று என்ன சாப்பிடுகிறீர்கள்?',
      'postAction': 'பதிவிடு',
      'feedTab': 'ஃபீட்',
      'groupsTab': 'குழுக்கள்',
      'camera': 'கேமரா',
      'gallery': 'கேலரி',
      'createGroup': 'குழு உருவாக்கு',
      'groupName': 'குழு பெயர்',
      'join': 'சேர்',
      'leaveGroup': 'குழுவிலிருந்து வெளியேறு',
      'deletePost': 'இந்த பதிவை நீக்கவா?',
      'cancelAction': 'ரத்து',
      'deleteAction': 'நீக்கு',
      'postSent': 'பதிவிடப்பட்டது! 🎉',
      'postFailed':
          'பதிவிட முடியவில்லை. இணைய இணைப்பை சரிபார்த்து மீண்டும் முயற்சிக்கவும்.',
      'adminTitle': 'நிர்வாக சரிபார்ப்பு',
      'approveAction': 'அனுமதி',
      'rejectAction': 'நிராகரி',
      'noPending': 'சரிபார்ப்புக்கு எதுவும் இல்லை.',
      'editProfileTitle': 'சுயவிவரம் திருத்து',
      'displayNameLabel': 'காட்சி பெயர்',
      'displayNameHint': 'உங்கள் பெயர்',
      'usernameLabel': 'பயனர்பெயர்',
      'usernameHint': 'your_username',
      'saveAction': 'சேமி',
      'profileSaved': 'சுயவிவரம் புதுப்பிக்கப்பட்டது!',
      'usernameTaken': 'இந்த பயனர்பெயர் எடுக்கப்பட்டது. வேறு முயற்சிக்கவும்.',
      'favoritesTitle': 'பிடித்தவை',
      'favoritesEmpty': 'இன்னும் இல்லை. எந்த கடையிலும் 🔖 அழுத்தி சேமிக்கவும்!',
      'favoriteAdded': 'பிடித்தவையில் சேமிக்கப்பட்டது!',
      'editTaste': 'சுவை மாற்று',
      'memoryIntro': 'MakanMana கற்றுக்கொண்டது:',
      'faq1Q': 'MakanMana எப்படி கடைகளை தேர்வு செய்கிறது?',
      'faq1A':
          'இடம், பட்ஜெட், மனநிலை, சுவை, உணவு வரலாறு மற்றும் மதிப்பீடுகளை கருத்தில் கொள்கிறோம்.',
      'faq2Q': 'Free, Plus, Pro வேறுபாடு என்ன?',
      'faq2A':
          'Free: நாளுக்கு 3 சுழற்சி. Plus: வரம்பற்ற சுழற்சி, எல்லா மனநிலை & தீம், பிடித்தவை. Pro: அனைத்தும் + வார அறிக்கை, AI பயிற்சியாளர், உணவு இலக்கு, உணவு திட்டம், கலோரி ஸ்கேன், குழு முடிவு.',
      'faq3Q': 'கடையை எப்படி மதிப்பிடுவது?',
      'faq3A':
          'வரலாற்றிலிருந்து, அல்லது கடையில் 5 நிமிட செக்-இன், அல்லது டெலிவரி விருப்பம் (நிர்வாக சரிபார்ப்பு).',
      'faq4Q': 'என் தரவு பாதுகாப்பானதா?',
      'faq4A': 'ஆம். தனிப்பட்ட தரவு உங்கள் கணக்கால் மட்டுமே அணுக முடியும்.',
      'faq5Q': 'சந்தாவை எப்படி ரத்து செய்வது?',
      'faq5A': 'Google Play > Subscriptions வழியாக.',
      'scanIntro': 'உணவை படமெடுங்கள் — AI கலோரிகளை பகுப்பாய்வு செய்யும்.',
      'scanning': 'AI உங்கள் உணவை பகுப்பாய்வு செய்கிறது...',
      'scanFailed': 'பகுப்பாய்வு தோல்வி. மீண்டும் முயற்சிக்கவும்.',
      'groupIntro':
          'வாக்கெடுப்பு உருவாக்கி, குறியீட்டை பகிர்ந்து, அனைவரும் வாக்களிக்கவும் — முடிவு நேரலையில்!',
      'createSession': 'வாக்கெடுப்பு உருவாக்கு',
      'joinSession': 'குறியீட்டுடன் சேர்',
      'sessionNotFound': 'அமர்வு கிடைக்கவில்லை. குறியீட்டை சரிபார்க்கவும்.',
      'sessionCode': 'அமர்வு குறியீடு',
      'shareCode': 'பகிர்',
      'votesLabel': 'வாக்குகள்',
      'voteTitle': 'உணவு வாக்கெடுப்பு',
      'voteHint': 'வாக்களிக்க தட்டவும். எப்போது வேண்டுமானாலும் மாற்றலாம்.',
      'orLabel': 'அல்லது',
      'commentsTitle': 'கருத்துகள்',
      'commentHint': 'கருத்து எழுதுங்கள்...',
      'noComments': 'இன்னும் கருத்துகள் இல்லை. தொடங்குங்கள்!',
      'proHubTitle': 'Pro கருவிகள்',
      'proHubTeaser':
          'எல்லா AI உணவு பயிற்சி கருவிகளும் இங்கே. Pro-க்கு மேம்படுத்துங்கள்!',
      'lockedPro': 'Pro அம்சம் 👑 — திறக்க மேம்படுத்தவும்.',
      'soonBadge': 'விரைவில்',
      'proReportTitle': 'வார அறிக்கை',
      'proReportDesc': '7 நாள் பகுப்பாய்வு: உணவு, செலவு, ஆரோக்கியம்.',
      'proCoachTitle': 'AI உணவு பயிற்சியாளர்',
      'proCoachDesc': 'உங்கள் உண்மையான உணவு பழக்கத்திலிருந்து குறிப்புகள்.',
      'proGoalTitle': 'உணவு இலக்கு',
      'proGoalDesc': 'உங்கள் இலக்கு ஒவ்வொரு பரிந்துரையையும் மாற்றும்.',
      'proPlanTitle': 'உணவு திட்டம்',
      'proPlanDesc': 'அருகிலுள்ள இடங்களிலிருந்து 3 நாள் திட்டம்.',
      'proScanTitle': 'கலோரி ஸ்கேன்',
      'proScanDesc': 'உணவை படமெடுத்து கலோரி மதிப்பீடு பெறுங்கள்.',
      'proGroupTitle': 'குழு முடிவு',
      'proGroupDesc': 'குழுவாக உணவு வாக்கெடுப்பு.',
      'healthyLabel': 'ஆரோக்கியம்',
      'varietyLabel': 'வகைகள்',
      'satisfactionLabel': 'திருப்தி',
      'favoritePlaceLabel': 'பிடித்த இடம்',
      'topCuisinesLabel': 'அடிக்கடி உண்ணும் உணவுவகை',
      'coachIntro':
          'வணக்கம்! இந்த வாரம் உங்கள் உணவு பழக்கத்தை பகுப்பாய்வு செய்தேன்:',
      'coachNoData': 'இன்னும் போதிய தரவு இல்லை. முதலில் சுழற்றி சாப்பிடுங்கள்!',
      'goalIntro':
          'உங்கள் இலக்கை தேர்வுசெய்யவும் — பரிந்துரைகள் அதை ஆதரிக்கும்.',
      'goalSihat': 'ஆரோக்கியம்',
      'goalSihatDesc': 'ஆரோக்கியமான சீரான தேர்வுகளுக்கு முன்னுரிமை.',
      'goalJimat': 'சிக்கனம்',
      'goalJimatDesc': 'பட்ஜெட் நட்பு இடங்களுக்கு முன்னுரிமை.',
      'goalSeimbang': 'சமநிலை',
      'goalSeimbangDesc': 'ஆரோக்கியம், சுவை, விலை — கலவை.',
      'goalSaved': 'உணவு இலக்கு சேமிக்கப்பட்டது!',
      'regeneratePlan': 'மீண்டும் உருவாக்கு',
      'slotBreakfast': 'காலை உணவு',
      'slotLunch': 'மதிய உணவு',
      'slotDinner': 'இரவு உணவு',
      'dayToday': 'இன்று',
      'dayTomorrow': 'நாளை',
      'dayAfter': 'நாளை மறுநாள்',
      'confirmPurchase': 'மேம்படுத்து:',
      'planUpdated': 'திட்டம் புதுப்பிக்கப்பட்டது! 🎉',
      'downgradeFree': 'Free-க்கு மாறு',
      'unlockWithPlus': 'Plus மூலம் திற ⭐',
      'unlockWithPro': 'Pro மூலம் திற 👑',
      'rateTitle': 'மதிப்பீடு',
      'rateShort': 'மதிப்பிடு',
      'rateAction': 'மதிப்பிடு',
      'reviewHint': 'உங்கள் அனுபவத்தை பகிரவும்... (விருப்பம்)',
      'submitReview': 'மதிப்பீடு அனுப்பு',
      'shareToFeed': 'உணவு ஃபீடில் பகிர்',
      'reviewSent': 'மதிப்பீடு அனுப்பப்பட்டது! ⭐ நன்றி!',
      'reviewPending': 'மதிப்பீடு அனுப்பப்பட்டது — நிர்வாக சரிபார்ப்பில்',
      'reviewNotEligible':
          'இன்னும் தகுதி இல்லை — கடையில் 5 நிமிடம் இருந்ததை உறுதிப்படுத்தவும்.',
      'deliveryPendingNote':
          'டெலிவரி மதிப்பீடுகள் சரிபார்க்கப்பட்ட பின் காட்டப்படும்.',
      'checkinAction': 'செக்-இன்',
      'checkinDone': 'செக்-இன் வெற்றி! இங்கு 5 நிமிடம் கழித்து மதிப்பிடலாம்.',
      'rateWaitPrefix': 'மதிப்பீடு இன்னும்',
      'communityRatingLabel': 'MakanMana சமூகம்',
      'reviewsTitle': 'சமூக விமர்சனங்கள்',
      'noReviews': 'இன்னும் விமர்சனங்கள் இல்லை. முதலில் நீங்கள்!',
      'deliveryRate': 'டெலிவரி ஆர்டர்?',
      'howWasMeal': 'உணவு எப்படி இருந்தது:',
      'fitCoachTitle': 'Fit Coach',
      'fitCoachTeaser': 'Daily score, workouts and healthier menu picks.',
      'fitSetupPrompt': 'Complete your Fit profile to start.',
      'fitWorkoutDone': 'Workout done',
      'fitWorkoutPending': 'Workout pending',
      'fitStepsUnit': 'steps',
      'fitLockedTitle': 'Fit Coach is a Pro feature',
      'fitLockedBody':
          'This preview shows the score, workout and menu coaching unlocked with Pro.',
      'fitUpgradeCta': 'Upgrade to Pro',
      'fitLogThis': 'Log this',
      'fitLogged': 'logged',
      'fitLogMealTitle': 'Log meal',
      'fitQuickLog': 'Quick Log',
      'fitManualLog': 'Manual',
      'fitMealName': 'Meal name',
      'fitSaveLog': 'Save log',
      'fitFbDone': 'Done',
      'fitFbEasy': 'Too easy',
      'fitFbHard': 'Too hard',
      'fitFbNoTime': 'No time',
      'fitFbPain': 'Pain',
      'fitFbTitle': 'How was the workout?',
      'fitPainWarning':
          'Workout recorded. If pain continues, please consult a qualified professional.',
      'fitFbThanks': 'Feedback recorded.',
      'fitSetupTitle': 'Set up Fit Coach',
      'fitSetupBody':
          'Add your body basics, goal and training style so MakanMana can calculate safer targets.',
      'fitBodyBasics': 'Body basics',
      'fitHeight': 'Height',
      'fitWeight': 'Weight',
      'fitAge': 'Age',
      'fitGender': 'Gender',
      'fitMale': 'Male',
      'fitFemale': 'Female',
      'fitGoalTitle': 'Fit goal',
      'fitGoalHealthy': 'Healthy lifestyle',
      'fitGoalFatLoss': 'Fat loss',
      'fitGoalLean': 'Lean body',
      'fitGoalRecomp': 'Body recomp',
      'fitGoalMuscle': 'Muscle gain',
      'fitGoalSport': 'Sport performance',
      'fitLevel': 'Level',
      'fitLevelBeginner': 'Beginner',
      'fitLevelIntermediate': 'Intermediate',
      'fitLevelAdvanced': 'Advanced',
      'fitLevelAthlete': 'Athlete',
      'fitTrainingPref': 'Training',
      'fitDaysPerWeek': 'Training days per week',
      'fitSessionDuration': 'Session duration',
      'fitTargets': 'Daily targets',
      'fitBudgetMin': 'Min budget',
      'fitBudgetMax': 'Max budget',
      'fitStepTarget': 'Step target',
      'fitSaveProfile': 'Save Fit profile',
      'fitStartSetup': 'Start setup',
      'fitEditProfile': 'Edit Fit profile',
      'fitTodayTitle': 'Fit Today',
      'fitNutritionTargets': 'Nutrition targets',
      'fitWater': 'Water',
      'fitLogWater': 'Log water',
      'fitLogSteps': 'Log steps',
      'fitLogWeight': 'Log weight',
      'fitWorkoutToday': 'Today workout',
      'fitChangeMood': 'Change mood',
      'fitFinishWorkout': 'Finish workout',
      'fitMenuSuggestions': 'Menu picks for today',
      'fitMonitorTitle': 'Fit Monitor',
      'fitWeeklyScore': 'Weekly Fit Score',
      'fitStepsTrend': 'Steps trend',
      'fitCaloriesTrend': 'Calories trend',
      'fitBodyTrend': 'Body trend',
      'fitBodyTrendEmpty': 'Not enough body entries for a chart yet.',
      'fitWeeklyReport': 'Weekly report',
      'fitRecentWorkouts': 'Recent workouts',
      'fitNoWorkoutYet': 'No workouts recorded yet.',
      'fitSampleReport':
          'This week looks consistent. Keep protein steady and add a few more steps.',
      'fitSampleRecProtein': 'Add protein at breakfast to support recovery.',
      'fitSampleRecSteps': 'Walk 10 minutes after lunch.',
      'fitSportMoodTitle': 'Sport Mood',
      'fitSportMoodIntro':
          'Pick today training style. MakanMana will tune your workout and food focus.',
      'historyTabMeals': 'உணவு',
      'historyTabFitness': 'உடற்பயிற்சி',
      'historyTabMonitor': 'மானிட்டர்',
      'historyTabReports': 'அறிக்கைகள்',
      'fitTodayLogs': 'இன்றைய பதிவுகள்',
      'fitNoLogsToday': 'இன்று பதிவுகள் இல்லை. முதல் உணவில் தொடங்குங்கள்.',
      'fitOpenMonitor': 'முழு மானிட்டரைத் திறக்க',
      'fitReportTitle': 'வாராந்திர உணவு & உடற்பயிற்சி அறிக்கை',
      'fitReportTeaser':
          'ஒவ்வொரு ஞாயிறும் உங்கள் பயிற்சி, அடிகள், புரதம் மற்றும் உணவு முறையை coach சுருக்கமாகத் தருவார்.',
      'fitTrainingDone': 'பயிற்சி முடிந்தது',
      'fitAvgSteps': 'சராசரி அடிகள்',
      'fitAvgCalories': 'சராசரி கலோரி',
      'fitProteinHit': 'புரத இலக்கு விகிதம்',
      'fitViewFullReport': 'முழு அறிக்கையைப் பார்க்க',
      'fitWeekStats': 'இந்த வார புள்ளிவிவரம்',
      'fitHealthyMeals': 'சமச்சீர் உணவுகள்',
      'fitHeavyMeals': 'கன உணவுகள்',
      'fitSugaryDrinks': 'இனிப்பு பானங்கள்',
      'fitNextWeek': 'அடுத்த வார கவனம்',
      'fitNoDataYet':
          'போதுமான தரவு இல்லை. உணவு & பயிற்சியைப் பதிவு செய்யுங்கள்.',
      'fitWearable': 'Wearable இணைப்பு',
      'fitWearableSoon':
          'விரைவில்: உங்கள் ஸ்மார்ட்வாட்சிலிருந்து அடிகள், பயிற்சி, இதயத் துடிப்பு, தூக்கம் sync.',
      'fitWearableView': 'சாதனங்களைப் பார்க்க',
      'fitHealthPermTitle': 'சுகாதார அனுமதிகள்',
      'fitPermSteps': 'அடிகள்',
      'fitPermWorkout': 'பயிற்சிகள்',
      'fitPermCalories': 'எரிந்த கலோரி',
      'fitPermDistance': 'தூரம்',
      'fitPermHeart': 'இதயத் துடிப்பு',
      'fitPermSleep': 'தூக்கம்',
      'fitPermNote':
          'உங்கள் சுகாதாரத் தரவு முழுவதும் உங்கள் கட்டுப்பாட்டில். எப்போது வேண்டுமானாலும் அனுமதியை அணைக்கலாம்; தொடர்புடைய தரவு sync ஆகாது.',
      'fitLogScan': 'Fit Coach-இல் பதிவு',
      'fitStreakDays': 'நாள் streak',
      'noGroups': 'இன்னும் குழுக்கள் இல்லை. முதல் குழுவை உருவாக்குங்கள்!',
    },
  };
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) =>
      ['ms', 'en', 'zh', 'ta'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async =>
      AppLocalizations(locale);

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
