/// PART 1 Phase 1.11 — kunci l10n pembetulan/laporan kedai (ms/en/zh/ta).
/// Disebar ke dalam AppLocalizations (pola sama seperti place card strings).
/// ID kanonikal disimpan di backend; ini HANYA label paparan.
library;

const Map<String, String> kCorrectionStringsMs = {
  // Titik masuk
  'reportIncorrectInformation': 'Laporkan maklumat tidak tepat',
  'suggestAnEdit': 'Cadangkan suntingan',
  'reportThisPlace': 'Laporkan kedai ini',
  'reportImage': 'Laporkan gambar',
  'reportUnsafeInformation': 'Laporkan maklumat tidak selamat',
  'reportClosed': 'Laporkan kedai tutup',
  'reportMoved': 'Laporkan kedai berpindah',
  'reportDuplicate': 'Laporkan kedai berulang',
  // Kategori
  'reportWrongName': 'Nama tidak tepat',
  'reportWrongAddress': 'Alamat tidak tepat',
  'reportWrongLocation': 'Lokasi tidak tepat',
  'reportWrongPhone': 'Nombor telefon tidak tepat',
  'reportWrongWebsite': 'Laman web tidak tepat',
  'reportWrongHours': 'Waktu operasi tidak tepat',
  'reportWrongPrice': 'Harga tidak tepat',
  'reportClosedCategory': 'Kedai sudah tutup',
  'reportTemporarilyClosed': 'Tutup sementara',
  'reportWrongCuisine': 'Jenis masakan tidak tepat',
  'reportWrongPlaceType': 'Jenis tempat tidak tepat',
  'reportWrongHalalStatus': 'Status halal tidak tepat',
  'reportUnsafeHalalClaim': 'Dakwaan halal tidak selamat',
  'reportWrongAllergenInfo': 'Maklumat alergen tidak tepat',
  'reportUnsafeAllergenClaim': 'Dakwaan alergen tidak selamat',
  'reportWrongDietaryInfo': 'Maklumat diet tidak tepat',
  'reportWrongImage': 'Gambar tidak tepat',
  'reportInappropriateImage': 'Gambar tidak sesuai',
  'reportSpamPlace': 'Kedai spam atau palsu',
  'reportOther': 'Lain-lain',
  // Borang
  'reportCurrentValue': 'Nilai semasa',
  'reportProposedValue': 'Nilai dicadangkan',
  'reportAddEvidence': 'Tambah bukti',
  'reportEvidenceOptional': 'Bukti (pilihan)',
  'reportEvidenceRequired': 'Bukti diperlukan',
  'reportDescription': 'Penerangan',
  'reportReviewSubmission': 'Semak laporan',
  'reportSubmit': 'Hantar laporan',
  'reportSubmitted': 'Laporan dihantar',
  'reportTrackingId': 'ID penjejakan',
  'reportChooseType': 'Pilih jenis laporan',
  'reportChooseCategory': 'Pilih kategori',
  'reportChooseField': 'Pilih medan',
  'reportNext': 'Seterusnya',
  'reportBack': 'Kembali',
  'reportCancel': 'Batal',
  'reportWithdraw': 'Tarik balik',
  'reportResubmit': 'Hantar semula dengan bukti',
  'reportEvidenceNote': 'Nota bukti',
  'reportObservedDate': 'Tarikh diperhati',
  // Status
  'reportStatusDraft': 'Draf',
  'reportStatusSubmitted': 'Dihantar',
  'reportStatusValidationFailed': 'Perlu dibetulkan',
  'reportStatusQueued': 'Dalam baris gilir',
  'reportStatusUnderReview': 'Sedang disemak',
  'reportStatusNeedsMoreEvidence': 'Perlu bukti tambahan',
  'reportStatusDuplicate': 'Laporan berulang',
  'reportStatusAccepted': 'Diterima untuk semakan',
  'reportStatusRejected': 'Tidak diterima',
  'reportStatusWithdrawn': 'Ditarik balik',
  'reportStatusResolved': 'Selesai',
  'reportStatusSuperseded': 'Digantikan laporan baharu',
  // Privasi & mod
  'reportPrivacyNotice': 'Notis privasi',
  'reportIdentityNotShown': 'Identiti anda tidak dipaparkan kepada umum.',
  'reportNoProductionData': 'Tiada data produksi ditulis.',
  'reportSampleMode': 'Mod contoh/mock',
  'reportProposalNotVerified':
      'Cadangan anda akan disemak. Ia bukan fakta yang disahkan.',
  'reportSafetyNotice':
      'Laporan keselamatan disemak secara manual. Ia tidak mengubah status halal atau alergen secara automatik.',
  // Sejarah
  'reportMySubmissions': 'Laporan saya',
  'reportHistoryEmpty': 'Anda belum menghantar sebarang laporan.',
  'reportTimeline': 'Garis masa status',
  'reportLoading': 'Sedang memuat laporan',
  'reportError': 'Laporan tidak dapat dimuat',
  'reportRetry': 'Cuba lagi',
  'reportOffline': 'Anda di luar talian. Laporan akan dihantar kemudian.',
  // Ralat pengesahan
  'reportErrorPlaceMissing': 'Kedai tidak dikenal pasti.',
  'reportErrorSnapshotMissing': 'Paparan asal tidak dapat direkodkan.',
  'reportErrorProposedValueRequired': 'Sila isi nilai yang dicadangkan.',
  'reportErrorEmptyCorrection': 'Sila isi sekurang-kurangnya satu perubahan.',
  'reportErrorDescriptionShort': 'Penerangan terlalu pendek.',
  'reportErrorDescriptionLong': 'Penerangan terlalu panjang.',
  'reportErrorTooMuchEvidence': 'Terlalu banyak bukti dilampirkan.',
  'reportErrorEvidenceRequired': 'Kategori ini memerlukan bukti.',
  'reportErrorObservationDateRequired': 'Sila nyatakan tarikh anda memerhati.',
  'reportErrorDuplicateTargetRequired': 'Sila pilih kedai berulang.',
  'reportErrorInvalidPhone': 'Format nombor telefon tidak sah.',
  'reportErrorInvalidWebsite': 'Pautan laman web tidak sah.',
  'reportErrorInvalidCoordinates': 'Koordinat tidak sah.',
  'reportErrorEvidenceConfidence': 'Keyakinan bukti tidak sah.',
  'reportErrorInvalidEvidenceUrl': 'Pautan bukti tidak sah.',
};

const Map<String, String> kCorrectionStringsEn = {
  'reportIncorrectInformation': 'Report incorrect information',
  'suggestAnEdit': 'Suggest an edit',
  'reportThisPlace': 'Report this place',
  'reportImage': 'Report image',
  'reportUnsafeInformation': 'Report unsafe information',
  'reportClosed': 'Report closed',
  'reportMoved': 'Report moved',
  'reportDuplicate': 'Report duplicate place',
  'reportWrongName': 'Wrong name',
  'reportWrongAddress': 'Wrong address',
  'reportWrongLocation': 'Wrong location',
  'reportWrongPhone': 'Wrong phone',
  'reportWrongWebsite': 'Wrong website',
  'reportWrongHours': 'Wrong hours',
  'reportWrongPrice': 'Wrong price',
  'reportClosedCategory': 'Permanently closed',
  'reportTemporarilyClosed': 'Temporarily closed',
  'reportWrongCuisine': 'Wrong cuisine',
  'reportWrongPlaceType': 'Wrong place type',
  'reportWrongHalalStatus': 'Wrong halal status',
  'reportUnsafeHalalClaim': 'Unsafe halal claim',
  'reportWrongAllergenInfo': 'Wrong allergen information',
  'reportUnsafeAllergenClaim': 'Unsafe allergen claim',
  'reportWrongDietaryInfo': 'Wrong dietary information',
  'reportWrongImage': 'Wrong image',
  'reportInappropriateImage': 'Inappropriate image',
  'reportSpamPlace': 'Spam or fake place',
  'reportOther': 'Other',
  'reportCurrentValue': 'Current value',
  'reportProposedValue': 'Proposed value',
  'reportAddEvidence': 'Add evidence',
  'reportEvidenceOptional': 'Evidence (optional)',
  'reportEvidenceRequired': 'Evidence required',
  'reportDescription': 'Description',
  'reportReviewSubmission': 'Review submission',
  'reportSubmit': 'Submit report',
  'reportSubmitted': 'Report submitted',
  'reportTrackingId': 'Tracking ID',
  'reportChooseType': 'Choose report type',
  'reportChooseCategory': 'Choose category',
  'reportChooseField': 'Choose field',
  'reportNext': 'Next',
  'reportBack': 'Back',
  'reportCancel': 'Cancel',
  'reportWithdraw': 'Withdraw',
  'reportResubmit': 'Resubmit with evidence',
  'reportEvidenceNote': 'Evidence note',
  'reportObservedDate': 'Date observed',
  'reportStatusDraft': 'Draft',
  'reportStatusSubmitted': 'Submitted',
  'reportStatusValidationFailed': 'Needs correction',
  'reportStatusQueued': 'Queued',
  'reportStatusUnderReview': 'Under review',
  'reportStatusNeedsMoreEvidence': 'More evidence needed',
  'reportStatusDuplicate': 'Duplicate report',
  'reportStatusAccepted': 'Accepted for review',
  'reportStatusRejected': 'Rejected',
  'reportStatusWithdrawn': 'Withdrawn',
  'reportStatusResolved': 'Resolved',
  'reportStatusSuperseded': 'Superseded by newer report',
  'reportPrivacyNotice': 'Privacy notice',
  'reportIdentityNotShown': 'Your identity is not shown publicly.',
  'reportNoProductionData': 'No production data written.',
  'reportSampleMode': 'Sample/mock mode',
  'reportProposalNotVerified':
      'Your suggestion will be reviewed. It is not a verified fact.',
  'reportSafetyNotice':
      'Safety reports are reviewed manually. They never change halal or allergen status automatically.',
  'reportMySubmissions': 'My reports',
  'reportHistoryEmpty': 'You have not submitted any reports yet.',
  'reportTimeline': 'Status timeline',
  'reportLoading': 'Loading reports',
  'reportError': 'Reports could not be loaded',
  'reportRetry': 'Try again',
  'reportOffline': 'You are offline. The report will be sent later.',
  'reportErrorPlaceMissing': 'The place could not be identified.',
  'reportErrorSnapshotMissing': 'The original view could not be recorded.',
  'reportErrorProposedValueRequired': 'Please enter the proposed value.',
  'reportErrorEmptyCorrection': 'Please provide at least one change.',
  'reportErrorDescriptionShort': 'Description is too short.',
  'reportErrorDescriptionLong': 'Description is too long.',
  'reportErrorTooMuchEvidence': 'Too many evidence items attached.',
  'reportErrorEvidenceRequired': 'This category requires evidence.',
  'reportErrorObservationDateRequired':
      'Please give the date you observed this.',
  'reportErrorDuplicateTargetRequired': 'Please choose the duplicate place.',
  'reportErrorInvalidPhone': 'Phone number format is invalid.',
  'reportErrorInvalidWebsite': 'Website link is invalid.',
  'reportErrorInvalidCoordinates': 'Coordinates are invalid.',
  'reportErrorEvidenceConfidence': 'Evidence confidence is invalid.',
  'reportErrorInvalidEvidenceUrl': 'Evidence link is invalid.',
};

const Map<String, String> kCorrectionStringsZh = {
  'reportIncorrectInformation': '报告信息有误',
  'suggestAnEdit': '建议修改',
  'reportThisPlace': '举报此店',
  'reportImage': '举报图片',
  'reportUnsafeInformation': '举报不安全信息',
  'reportClosed': '报告已停业',
  'reportMoved': '报告已搬迁',
  'reportDuplicate': '报告重复店铺',
  'reportWrongName': '名称有误',
  'reportWrongAddress': '地址有误',
  'reportWrongLocation': '位置有误',
  'reportWrongPhone': '电话有误',
  'reportWrongWebsite': '网站有误',
  'reportWrongHours': '营业时间有误',
  'reportWrongPrice': '价格有误',
  'reportClosedCategory': '永久停业',
  'reportTemporarilyClosed': '暂停营业',
  'reportWrongCuisine': '菜系有误',
  'reportWrongPlaceType': '店铺类型有误',
  'reportWrongHalalStatus': '清真状态有误',
  'reportUnsafeHalalClaim': '不安全的清真声明',
  'reportWrongAllergenInfo': '过敏原信息有误',
  'reportUnsafeAllergenClaim': '不安全的过敏原声明',
  'reportWrongDietaryInfo': '饮食信息有误',
  'reportWrongImage': '图片有误',
  'reportInappropriateImage': '不当图片',
  'reportSpamPlace': '垃圾或虚假店铺',
  'reportOther': '其他',
  'reportCurrentValue': '当前值',
  'reportProposedValue': '建议值',
  'reportAddEvidence': '添加证据',
  'reportEvidenceOptional': '证据（可选）',
  'reportEvidenceRequired': '需要证据',
  'reportDescription': '说明',
  'reportReviewSubmission': '检查提交内容',
  'reportSubmit': '提交报告',
  'reportSubmitted': '报告已提交',
  'reportTrackingId': '追踪编号',
  'reportChooseType': '选择报告类型',
  'reportChooseCategory': '选择类别',
  'reportChooseField': '选择字段',
  'reportNext': '下一步',
  'reportBack': '返回',
  'reportCancel': '取消',
  'reportWithdraw': '撤回',
  'reportResubmit': '补充证据后重新提交',
  'reportEvidenceNote': '证据备注',
  'reportObservedDate': '观察日期',
  'reportStatusDraft': '草稿',
  'reportStatusSubmitted': '已提交',
  'reportStatusValidationFailed': '需要修正',
  'reportStatusQueued': '排队中',
  'reportStatusUnderReview': '审核中',
  'reportStatusNeedsMoreEvidence': '需要更多证据',
  'reportStatusDuplicate': '重复报告',
  'reportStatusAccepted': '已接受待审',
  'reportStatusRejected': '未被接受',
  'reportStatusWithdrawn': '已撤回',
  'reportStatusResolved': '已解决',
  'reportStatusSuperseded': '已被新报告取代',
  'reportPrivacyNotice': '隐私声明',
  'reportIdentityNotShown': '您的身份不会公开显示。',
  'reportNoProductionData': '不会写入生产数据。',
  'reportSampleMode': '示例/模拟模式',
  'reportProposalNotVerified': '您的建议将经过审核，并非已证实的事实。',
  'reportSafetyNotice': '安全报告由人工审核，不会自动更改清真或过敏原状态。',
  'reportMySubmissions': '我的报告',
  'reportHistoryEmpty': '您还没有提交任何报告。',
  'reportTimeline': '状态时间线',
  'reportLoading': '正在加载报告',
  'reportError': '无法加载报告',
  'reportRetry': '重试',
  'reportOffline': '您已离线，报告稍后发送。',
  'reportErrorPlaceMissing': '无法识别该店铺。',
  'reportErrorSnapshotMissing': '无法记录原始显示内容。',
  'reportErrorProposedValueRequired': '请填写建议值。',
  'reportErrorEmptyCorrection': '请至少提供一项修改。',
  'reportErrorDescriptionShort': '说明太短。',
  'reportErrorDescriptionLong': '说明太长。',
  'reportErrorTooMuchEvidence': '附加的证据过多。',
  'reportErrorEvidenceRequired': '此类别需要证据。',
  'reportErrorObservationDateRequired': '请提供您观察到的日期。',
  'reportErrorDuplicateTargetRequired': '请选择重复的店铺。',
  'reportErrorInvalidPhone': '电话号码格式无效。',
  'reportErrorInvalidWebsite': '网站链接无效。',
  'reportErrorInvalidCoordinates': '坐标无效。',
  'reportErrorEvidenceConfidence': '证据置信度无效。',
  'reportErrorInvalidEvidenceUrl': '证据链接无效。',
};

const Map<String, String> kCorrectionStringsTa = {
  'reportIncorrectInformation': 'தவறான தகவலைப் புகாரளி',
  'suggestAnEdit': 'திருத்தத்தை பரிந்துரை',
  'reportThisPlace': 'இந்த இடத்தைப் புகாரளி',
  'reportImage': 'படத்தைப் புகாரளி',
  'reportUnsafeInformation': 'பாதுகாப்பற்ற தகவலைப் புகாரளி',
  'reportClosed': 'மூடப்பட்டதைப் புகாரளி',
  'reportMoved': 'இடம் மாறியதைப் புகாரளி',
  'reportDuplicate': 'நகல் இடத்தைப் புகாரளி',
  'reportWrongName': 'தவறான பெயர்',
  'reportWrongAddress': 'தவறான முகவரி',
  'reportWrongLocation': 'தவறான இருப்பிடம்',
  'reportWrongPhone': 'தவறான தொலைபேசி',
  'reportWrongWebsite': 'தவறான இணையதளம்',
  'reportWrongHours': 'தவறான நேரம்',
  'reportWrongPrice': 'தவறான விலை',
  'reportClosedCategory': 'நிரந்தரமாக மூடப்பட்டது',
  'reportTemporarilyClosed': 'தற்காலிகமாக மூடப்பட்டது',
  'reportWrongCuisine': 'தவறான உணவு வகை',
  'reportWrongPlaceType': 'தவறான இட வகை',
  'reportWrongHalalStatus': 'தவறான ஹலால் நிலை',
  'reportUnsafeHalalClaim': 'பாதுகாப்பற்ற ஹலால் கூற்று',
  'reportWrongAllergenInfo': 'தவறான ஒவ்வாமை தகவல்',
  'reportUnsafeAllergenClaim': 'பாதுகாப்பற்ற ஒவ்வாமை கூற்று',
  'reportWrongDietaryInfo': 'தவறான உணவுமுறை தகவல்',
  'reportWrongImage': 'தவறான படம்',
  'reportInappropriateImage': 'பொருத்தமற்ற படம்',
  'reportSpamPlace': 'ஸ்பேம் அல்லது போலி இடம்',
  'reportOther': 'மற்றவை',
  'reportCurrentValue': 'தற்போதைய மதிப்பு',
  'reportProposedValue': 'பரிந்துரைக்கப்பட்ட மதிப்பு',
  'reportAddEvidence': 'ஆதாரம் சேர்',
  'reportEvidenceOptional': 'ஆதாரம் (விருப்பம்)',
  'reportEvidenceRequired': 'ஆதாரம் தேவை',
  'reportDescription': 'விவரம்',
  'reportReviewSubmission': 'சமர்ப்பிப்பை சரிபார்',
  'reportSubmit': 'புகாரை சமர்ப்பி',
  'reportSubmitted': 'புகார் சமர்ப்பிக்கப்பட்டது',
  'reportTrackingId': 'கண்காணிப்பு எண்',
  'reportChooseType': 'புகார் வகையைத் தேர்ந்தெடு',
  'reportChooseCategory': 'வகையைத் தேர்ந்தெடு',
  'reportChooseField': 'புலத்தைத் தேர்ந்தெடு',
  'reportNext': 'அடுத்து',
  'reportBack': 'பின்',
  'reportCancel': 'ரத்து',
  'reportWithdraw': 'திரும்பப் பெறு',
  'reportResubmit': 'ஆதாரத்துடன் மீண்டும் சமர்ப்பி',
  'reportEvidenceNote': 'ஆதாரக் குறிப்பு',
  'reportObservedDate': 'கவனித்த தேதி',
  'reportStatusDraft': 'வரைவு',
  'reportStatusSubmitted': 'சமர்ப்பிக்கப்பட்டது',
  'reportStatusValidationFailed': 'திருத்தம் தேவை',
  'reportStatusQueued': 'வரிசையில்',
  'reportStatusUnderReview': 'பரிசீலனையில்',
  'reportStatusNeedsMoreEvidence': 'கூடுதல் ஆதாரம் தேவை',
  'reportStatusDuplicate': 'நகல் புகார்',
  'reportStatusAccepted': 'பரிசீலனைக்கு ஏற்கப்பட்டது',
  'reportStatusRejected': 'ஏற்கப்படவில்லை',
  'reportStatusWithdrawn': 'திரும்பப் பெறப்பட்டது',
  'reportStatusResolved': 'தீர்க்கப்பட்டது',
  'reportStatusSuperseded': 'புதிய புகாரால் மாற்றப்பட்டது',
  'reportPrivacyNotice': 'தனியுரிமை அறிவிப்பு',
  'reportIdentityNotShown': 'உங்கள் அடையாளம் பொதுவில் காட்டப்படாது.',
  'reportNoProductionData': 'உற்பத்தித் தரவு எழுதப்படாது.',
  'reportSampleMode': 'மாதிரி/போலி முறை',
  'reportProposalNotVerified':
      'உங்கள் பரிந்துரை பரிசீலிக்கப்படும். இது சரிபார்க்கப்பட்ட உண்மை அல்ல.',
  'reportSafetyNotice':
      'பாதுகாப்புப் புகார்கள் கைமுறையாகப் பரிசீலிக்கப்படும். ஹலால் அல்லது ஒவ்வாமை நிலையை தானாக மாற்றாது.',
  'reportMySubmissions': 'எனது புகார்கள்',
  'reportHistoryEmpty': 'நீங்கள் இதுவரை புகார் சமர்ப்பிக்கவில்லை.',
  'reportTimeline': 'நிலை காலவரிசை',
  'reportLoading': 'புகார்கள் ஏற்றப்படுகின்றன',
  'reportError': 'புகார்களை ஏற்ற முடியவில்லை',
  'reportRetry': 'மீண்டும் முயற்சி',
  'reportOffline':
      'நீங்கள் ஆஃப்லைனில் உள்ளீர்கள். புகார் பின்னர் அனுப்பப்படும்.',
  'reportErrorPlaceMissing': 'இடத்தை அடையாளம் காண முடியவில்லை.',
  'reportErrorSnapshotMissing': 'அசல் காட்சியைப் பதிவு செய்ய முடியவில்லை.',
  'reportErrorProposedValueRequired': 'பரிந்துரைக்கப்பட்ட மதிப்பை உள்ளிடவும்.',
  'reportErrorEmptyCorrection': 'குறைந்தது ஒரு மாற்றத்தையாவது வழங்கவும்.',
  'reportErrorDescriptionShort': 'விவரம் மிகக் குறுகியது.',
  'reportErrorDescriptionLong': 'விவரம் மிக நீளமானது.',
  'reportErrorTooMuchEvidence': 'மிக அதிக ஆதாரங்கள் இணைக்கப்பட்டுள்ளன.',
  'reportErrorEvidenceRequired': 'இந்த வகைக்கு ஆதாரம் தேவை.',
  'reportErrorObservationDateRequired': 'நீங்கள் கவனித்த தேதியைத் தரவும்.',
  'reportErrorDuplicateTargetRequired': 'நகல் இடத்தைத் தேர்ந்தெடுக்கவும்.',
  'reportErrorInvalidPhone': 'தொலைபேசி எண் வடிவம் தவறானது.',
  'reportErrorInvalidWebsite': 'இணையதள இணைப்பு தவறானது.',
  'reportErrorInvalidCoordinates': 'ஆயத்தொலைவுகள் தவறானவை.',
  'reportErrorEvidenceConfidence': 'ஆதார நம்பகத்தன்மை தவறானது.',
  'reportErrorInvalidEvidenceUrl': 'ஆதார இணைப்பு தவறானது.',
};
