/// PART 1 Phase 1.9 — kunci l10n kad kedai kanonikal (ms/en/zh/ta).
/// Disebar ke dalam AppLocalizations (pola sama seperti sport strings).
/// ID kanonikal disimpan di backend; ini HANYA label paparan.
library;

const Map<String, String> kPlaceCardStringsMs = {
  'accept': 'Terima',
  'reject': 'Tolak',
  'priceUnavailable': 'Harga belum diketahui',
  'estimatedPrice': 'Anggaran',
  'priceRecheck': 'Harga perlu disemak',
  'priceBand': 'Julat harga',
  'hoursUnknown': 'Waktu operasi belum disahkan',
  'hoursExpired': 'Status buka perlu disemak',
  'tempClosed': 'Tutup sementara',
  'permClosed': 'Tidak lagi beroperasi',
  'statusUnknown': 'Status belum disahkan',
  'notEnoughReviews': 'Belum cukup ulasan',
  'ratingUnavailable': 'Tiada penilaian',
  'cachedApprovedLabel': 'Data cache diluluskan',
  'warnAllergyConflict': 'Mungkin mengandungi alahan; semak dengan kedai',
  'warnAllergyUnknown': 'Data alahan tidak lengkap',
  'warnPossibleNonHalal': 'Status halal belum disahkan',
  'warnPriceUnknown': 'Harga belum diketahui',
  'halalCertified': 'Halal disahkan',
  'halalMerchantClaim': 'Dilaporkan halal oleh merchant',
  'halalCommunityReport': 'Dilaporkan halal oleh komuniti',
  'halalUnknown': 'Status halal belum disahkan',
  'halalRecheck': 'Bukti halal perlu disemak',
  'placePhotoSemantic': 'Gambar tempat makan',
  'cardErrorTitle': 'Gagal memuat kad',
  'loadingLabel': 'Sedang memuat',
};

const Map<String, String> kPlaceCardStringsEn = {
  'accept': 'Accept',
  'reject': 'Reject',
  'priceUnavailable': 'Price unavailable',
  'estimatedPrice': 'Estimated',
  'priceRecheck': 'Price needs recheck',
  'priceBand': 'Price band',
  'hoursUnknown': 'Hours not verified',
  'hoursExpired': 'Open status needs recheck',
  'tempClosed': 'Temporarily closed',
  'permClosed': 'Permanently closed',
  'statusUnknown': 'Status not verified',
  'notEnoughReviews': 'Not enough reviews',
  'ratingUnavailable': 'No rating',
  'cachedApprovedLabel': 'Cached approved data',
  'warnAllergyConflict': 'May contain allergen; check with the shop',
  'warnAllergyUnknown': 'Allergen data incomplete',
  'warnPossibleNonHalal': 'Halal status not verified',
  'warnPriceUnknown': 'Price unavailable',
  'halalCertified': 'Halal certified',
  'halalMerchantClaim': 'Halal claimed by merchant',
  'halalCommunityReport': 'Halal reported by community',
  'halalUnknown': 'Halal status not verified',
  'halalRecheck': 'Halal evidence needs recheck',
  'placePhotoSemantic': 'Restaurant photo',
  'cardErrorTitle': 'Failed to load card',
  'loadingLabel': 'Loading',
};

const Map<String, String> kPlaceCardStringsZh = {
  'accept': '接受',
  'reject': '拒绝',
  'priceUnavailable': '价格未知',
  'estimatedPrice': '预估',
  'priceRecheck': '价格需要核实',
  'priceBand': '价格区间',
  'hoursUnknown': '营业时间未确认',
  'hoursExpired': '营业状态需核实',
  'tempClosed': '暂时休业',
  'permClosed': '已永久停业',
  'statusUnknown': '状态未确认',
  'notEnoughReviews': '评价不足',
  'ratingUnavailable': '暂无评分',
  'cachedApprovedLabel': '已核准缓存数据',
  'warnAllergyConflict': '可能含过敏原；请咨询店家',
  'warnAllergyUnknown': '过敏原数据不完整',
  'warnPossibleNonHalal': '清真状态未确认',
  'warnPriceUnknown': '价格未知',
  'halalCertified': '清真认证',
  'halalMerchantClaim': '商家声称清真',
  'halalCommunityReport': '社区报告清真',
  'halalUnknown': '清真状态未确认',
  'halalRecheck': '清真证据需核实',
  'placePhotoSemantic': '餐厅照片',
  'cardErrorTitle': '卡片加载失败',
  'loadingLabel': '加载中',
};

const Map<String, String> kPlaceCardStringsTa = {
  'accept': 'ஏற்கவும்',
  'reject': 'நிராகரி',
  'priceUnavailable': 'விலை தெரியவில்லை',
  'estimatedPrice': 'மதிப்பீடு',
  'priceRecheck': 'விலையை மீள்சரிபார்க்கவும்',
  'priceBand': 'விலை வரம்பு',
  'hoursUnknown': 'நேரம் உறுதிப்படுத்தப்படவில்லை',
  'hoursExpired': 'திறப்பு நிலையை மீள்சரிபார்க்கவும்',
  'tempClosed': 'தற்காலிகமாக மூடப்பட்டது',
  'permClosed': 'நிரந்தரமாக மூடப்பட்டது',
  'statusUnknown': 'நிலை உறுதிப்படுத்தப்படவில்லை',
  'notEnoughReviews': 'போதிய மதிப்புரைகள் இல்லை',
  'ratingUnavailable': 'மதிப்பீடு இல்லை',
  'cachedApprovedLabel': 'சேமிக்கப்பட்ட அங்கீகரிக்கப்பட்ட தரவு',
  'warnAllergyConflict': 'ஒவ்வாமை இருக்கலாம்; கடையில் சரிபார்க்கவும்',
  'warnAllergyUnknown': 'ஒவ்வாமை தரவு முழுமையடையவில்லை',
  'warnPossibleNonHalal': 'ஹலால் நிலை உறுதிப்படுத்தப்படவில்லை',
  'warnPriceUnknown': 'விலை தெரியவில்லை',
  'halalCertified': 'ஹலால் சான்று',
  'halalMerchantClaim': 'வணிகர் ஹலால் எனக் கூறுகிறார்',
  'halalCommunityReport': 'சமூகம் ஹலால் எனப் புகாரளித்தது',
  'halalUnknown': 'ஹலால் நிலை உறுதிப்படுத்தப்படவில்லை',
  'halalRecheck': 'ஹலால் சான்று மீள்சரிபார்க்க வேண்டும்',
  'placePhotoSemantic': 'உணவகப் படம்',
  'cardErrorTitle': 'அட்டையை ஏற்ற முடியவில்லை',
  'loadingLabel': 'ஏற்றுகிறது',
};
