/// WAVE 4 — Commercial Tools l10n (ms/en/zh/ta).
///
/// Same spread pattern as sport/place-card/restaurant-detail strings, so the
/// existing key-parity and no-empty-value gates cover these automatically.
library;

const Map<String, String> kPromotionStringsMs = {
  // Merchant surface
  'promoSectionTitle': 'Promosi & Tawaran',
  'promoSectionSubtitle':
      'Tawaran anda dipapar pada halaman kedai apabila ia aktif dan masih dalam tempoh.',
  'promoEmpty': 'Belum ada promosi.',
  'promoEmptyHint': 'Cipta tawaran pertama anda untuk dipapar kepada pelanggan.',
  'promoCreate': 'Cipta promosi',
  'promoSave': 'Simpan',
  'promoCancel': 'Batal',
  'promoTitleLabel': 'Tajuk tawaran *',
  'promoDescriptionLabel': 'Keterangan ringkas',
  'promoTermsLabel': 'Terma & syarat',
  'promoOfferLabelLabel': 'Nilai dipapar (cth. RM5 off)',
  'promoMinSpendLabel': 'Perbelanjaan minimum (RM)',
  'promoOfferTypeLabel': 'Jenis tawaran',
  'promoStartsLabel': 'Mula',
  'promoEndsLabel': 'Tamat',
  'promoEligibilityLabel': 'Kelayakan',
  'promoEligibilityAll': 'Semua pengguna',
  'promoEligibilityPlan': 'Pelan tertentu',
  'promoPickDate': 'Pilih tarikh',
  'promoLoadError': 'Gagal memuat promosi.',
  'promoSaveError': 'Gagal menyimpan promosi.',
  'promoSaved': 'Promosi disimpan.',
  'promoStatusChanged': 'Status promosi dikemas kini.',
  'promoSelectRestaurant': 'Pilih kedai untuk urus promosi.',
  // Status
  'promoStatusDraft': 'Draf',
  'promoStatusScheduled': 'Dijadualkan',
  'promoStatusActive': 'Aktif',
  'promoStatusPaused': 'Dijeda',
  'promoStatusExpired': 'Tamat',
  'promoStatusArchived': 'Diarkib',
  // Actions
  'promoActionPublish': 'Terbitkan',
  'promoActionSchedule': 'Jadualkan',
  'promoActionPause': 'Jeda',
  'promoActionResume': 'Sambung semula',
  'promoActionArchive': 'Arkib',
  // Offer types
  'promoTypePercentOff': 'Diskaun peratus',
  'promoTypeAmountOff': 'Diskaun jumlah',
  'promoTypeBundle': 'Set / kombo',
  'promoTypeFreeItem': 'Item percuma',
  'promoTypeOther': 'Lain-lain',
  // Public surface
  'promoPublicTitle': 'Tawaran kedai',
  'promoPublicUntil': 'Sehingga',
  'promoPublicMinSpend': 'Min. perbelanjaan',
  'promoPublicTerms': 'Terma',
};

const Map<String, String> kPromotionStringsEn = {
  'promoSectionTitle': 'Promotions & Offers',
  'promoSectionSubtitle':
      'Your offers appear on the restaurant page while they are active and still in date.',
  'promoEmpty': 'No promotions yet.',
  'promoEmptyHint': 'Create your first offer to show it to customers.',
  'promoCreate': 'Create promotion',
  'promoSave': 'Save',
  'promoCancel': 'Cancel',
  'promoTitleLabel': 'Offer title *',
  'promoDescriptionLabel': 'Short description',
  'promoTermsLabel': 'Terms & conditions',
  'promoOfferLabelLabel': 'Displayed value (e.g. RM5 off)',
  'promoMinSpendLabel': 'Minimum spend (RM)',
  'promoOfferTypeLabel': 'Offer type',
  'promoStartsLabel': 'Starts',
  'promoEndsLabel': 'Ends',
  'promoEligibilityLabel': 'Eligibility',
  'promoEligibilityAll': 'Everyone',
  'promoEligibilityPlan': 'Specific plans',
  'promoPickDate': 'Pick a date',
  'promoLoadError': 'Couldn’t load promotions.',
  'promoSaveError': 'Couldn’t save the promotion.',
  'promoSaved': 'Promotion saved.',
  'promoStatusChanged': 'Promotion status updated.',
  'promoSelectRestaurant': 'Choose a restaurant to manage promotions.',
  'promoStatusDraft': 'Draft',
  'promoStatusScheduled': 'Scheduled',
  'promoStatusActive': 'Active',
  'promoStatusPaused': 'Paused',
  'promoStatusExpired': 'Expired',
  'promoStatusArchived': 'Archived',
  'promoActionPublish': 'Publish',
  'promoActionSchedule': 'Schedule',
  'promoActionPause': 'Pause',
  'promoActionResume': 'Resume',
  'promoActionArchive': 'Archive',
  'promoTypePercentOff': 'Percentage off',
  'promoTypeAmountOff': 'Amount off',
  'promoTypeBundle': 'Bundle / combo',
  'promoTypeFreeItem': 'Free item',
  'promoTypeOther': 'Other',
  'promoPublicTitle': 'Restaurant offers',
  'promoPublicUntil': 'Until',
  'promoPublicMinSpend': 'Min. spend',
  'promoPublicTerms': 'Terms',
};

const Map<String, String> kPromotionStringsZh = {
  'promoSectionTitle': '促销与优惠',
  'promoSectionSubtitle': '优惠在有效期内且状态为启用时，会显示在餐厅页面。',
  'promoEmpty': '还没有促销。',
  'promoEmptyHint': '创建第一个优惠，让顾客看到。',
  'promoCreate': '创建促销',
  'promoSave': '保存',
  'promoCancel': '取消',
  'promoTitleLabel': '优惠标题 *',
  'promoDescriptionLabel': '简短说明',
  'promoTermsLabel': '条款与条件',
  'promoOfferLabelLabel': '显示金额（例如 RM5 off）',
  'promoMinSpendLabel': '最低消费（RM）',
  'promoOfferTypeLabel': '优惠类型',
  'promoStartsLabel': '开始',
  'promoEndsLabel': '结束',
  'promoEligibilityLabel': '适用对象',
  'promoEligibilityAll': '所有用户',
  'promoEligibilityPlan': '指定方案',
  'promoPickDate': '选择日期',
  'promoLoadError': '无法加载促销。',
  'promoSaveError': '无法保存促销。',
  'promoSaved': '促销已保存。',
  'promoStatusChanged': '促销状态已更新。',
  'promoSelectRestaurant': '选择餐厅以管理促销。',
  'promoStatusDraft': '草稿',
  'promoStatusScheduled': '已排程',
  'promoStatusActive': '启用中',
  'promoStatusPaused': '已暂停',
  'promoStatusExpired': '已结束',
  'promoStatusArchived': '已封存',
  'promoActionPublish': '发布',
  'promoActionSchedule': '排程',
  'promoActionPause': '暂停',
  'promoActionResume': '恢复',
  'promoActionArchive': '封存',
  'promoTypePercentOff': '百分比折扣',
  'promoTypeAmountOff': '金额折扣',
  'promoTypeBundle': '套餐',
  'promoTypeFreeItem': '免费赠品',
  'promoTypeOther': '其他',
  'promoPublicTitle': '餐厅优惠',
  'promoPublicUntil': '截至',
  'promoPublicMinSpend': '最低消费',
  'promoPublicTerms': '条款',
};

const Map<String, String> kPromotionStringsTa = {
  'promoSectionTitle': 'விளம்பரங்கள் & சலுகைகள்',
  'promoSectionSubtitle':
      'உங்கள் சலுகைகள் செயலில் இருக்கும் காலத்தில் உணவகப் பக்கத்தில் தோன்றும்.',
  'promoEmpty': 'இன்னும் சலுகைகள் இல்லை.',
  'promoEmptyHint': 'வாடிக்கையாளர்களுக்குக் காட்ட முதல் சலுகையை உருவாக்குங்கள்.',
  'promoCreate': 'சலுகையை உருவாக்கு',
  'promoSave': 'சேமி',
  'promoCancel': 'ரத்து',
  'promoTitleLabel': 'சலுகைத் தலைப்பு *',
  'promoDescriptionLabel': 'சுருக்கமான விவரம்',
  'promoTermsLabel': 'விதிமுறைகள்',
  'promoOfferLabelLabel': 'காட்டப்படும் மதிப்பு (எ.கா. RM5 off)',
  'promoMinSpendLabel': 'குறைந்தபட்ச செலவு (RM)',
  'promoOfferTypeLabel': 'சலுகை வகை',
  'promoStartsLabel': 'தொடக்கம்',
  'promoEndsLabel': 'முடிவு',
  'promoEligibilityLabel': 'தகுதி',
  'promoEligibilityAll': 'அனைவரும்',
  'promoEligibilityPlan': 'குறிப்பிட்ட திட்டங்கள்',
  'promoPickDate': 'தேதியைத் தேர்வுசெய்',
  'promoLoadError': 'சலுகைகளை ஏற்ற முடியவில்லை.',
  'promoSaveError': 'சலுகையைச் சேமிக்க முடியவில்லை.',
  'promoSaved': 'சலுகை சேமிக்கப்பட்டது.',
  'promoStatusChanged': 'சலுகை நிலை புதுப்பிக்கப்பட்டது.',
  'promoSelectRestaurant': 'சலுகைகளை நிர்வகிக்க உணவகத்தைத் தேர்வுசெய்.',
  'promoStatusDraft': 'வரைவு',
  'promoStatusScheduled': 'திட்டமிடப்பட்டது',
  'promoStatusActive': 'செயலில்',
  'promoStatusPaused': 'இடைநிறுத்தம்',
  'promoStatusExpired': 'முடிந்தது',
  'promoStatusArchived': 'காப்பகம்',
  'promoActionPublish': 'வெளியிடு',
  'promoActionSchedule': 'திட்டமிடு',
  'promoActionPause': 'இடைநிறுத்து',
  'promoActionResume': 'தொடர்',
  'promoActionArchive': 'காப்பகப்படுத்து',
  'promoTypePercentOff': 'சதவீதக் கழிவு',
  'promoTypeAmountOff': 'தொகைக் கழிவு',
  'promoTypeBundle': 'தொகுப்பு',
  'promoTypeFreeItem': 'இலவசப் பொருள்',
  'promoTypeOther': 'மற்றவை',
  'promoPublicTitle': 'உணவக சலுகைகள்',
  'promoPublicUntil': 'வரை',
  'promoPublicMinSpend': 'குறைந்தபட்ச செலவு',
  'promoPublicTerms': 'விதிமுறைகள்',
};
