/// PART 1 Phase 1.10 — kunci l10n Butiran Kedai kanonikal (ms/en/zh/ta).
/// Disebar ke dalam AppLocalizations (pola sama seperti sport/place-card strings).
/// Kunci Phase 1.9 (priceUnavailable, hoursUnknown, halal*, dsb.) DIGUNA SEMULA.
library;

const Map<String, String> kRestaurantDetailStringsMs = {
  'restaurantDetails': 'Butiran kedai',
  'movedLabel': 'Telah berpindah',
  'movedWarning': 'Kedai ini mungkin telah berpindah lokasi',
  'todayHours': 'Waktu hari ini',
  'weeklyHours': 'Jadual mingguan',
  'hoursTitle': 'Waktu operasi',
  'ratingReviewsTitle': 'Penilaian & ulasan',
  'priceTitle': 'Harga',
  'cuisineTypeTitle': 'Masakan & jenis',
  'dishHighlights': 'Hidangan pilihan',
  'servicesLabel': 'Perkhidmatan',
  'ambienceLabel': 'Suasana',
  'halalInfo': 'Maklumat halal',
  'dietaryInfo': 'Maklumat pemakanan',
  'allergenInfo': 'Maklumat alahan',
  'allergenCaution': 'Data alahan tidak lengkap — sahkan dengan kedai',
  'dietVerified': 'Disahkan',
  'dietReported': 'Dilaporkan',
  'dietInferred': 'Disimpulkan',
  'contactLabel': 'Hubungan',
  'contactUnavailable': 'Tiada maklumat hubungan',
  'callAction': 'Telefon',
  'websiteAction': 'Laman web',
  'logMealAction': 'Log makan',
  'verificationTitle': 'Pengesahan',
  'sourceInformation': 'Maklumat sumber',
  'provenanceTitle': 'Asal data',
  'freshnessTitle': 'Kesegaran data',
  'freshnessStale': 'Data mungkin lapuk',
  'freshnessExpired': 'Data perlu disemak semula',
  'lastUpdated': 'Kemas kini terakhir',
  'lastVerified': 'Sah terakhir',
  'communityReportedLabel': 'Dilaporkan komuniti',
  'showMore': 'Lihat lagi',
  'showLess': 'Lihat kurang',
  'sampleDataLabel': 'Data contoh',
  'sampleActionBlocked': 'Tindakan langsung dimatikan untuk data contoh',
  'noInfoAvailable': 'Tiada maklumat tersedia',
  'detailNotFound': 'Kedai tidak dijumpai',
  'missingPlaceId': 'ID kedai tiada',
  'galleryCountLabel': 'gambar',
  'reviewsSummaryTitle': 'Ringkasan ulasan',
};

const Map<String, String> kRestaurantDetailStringsEn = {
  'restaurantDetails': 'Restaurant details',
  'movedLabel': 'Moved',
  'movedWarning': 'This venue may have moved location',
  'todayHours': "Today's hours",
  'weeklyHours': 'Weekly schedule',
  'hoursTitle': 'Opening hours',
  'ratingReviewsTitle': 'Rating & reviews',
  'priceTitle': 'Price',
  'cuisineTypeTitle': 'Cuisine & type',
  'dishHighlights': 'Dish highlights',
  'servicesLabel': 'Services',
  'ambienceLabel': 'Ambience',
  'halalInfo': 'Halal information',
  'dietaryInfo': 'Dietary information',
  'allergenInfo': 'Allergen information',
  'allergenCaution': 'Allergen data incomplete — confirm with the shop',
  'dietVerified': 'Verified',
  'dietReported': 'Reported',
  'dietInferred': 'Inferred',
  'contactLabel': 'Contact',
  'contactUnavailable': 'No contact information',
  'callAction': 'Call',
  'websiteAction': 'Website',
  'logMealAction': 'Log meal',
  'verificationTitle': 'Verification',
  'sourceInformation': 'Source information',
  'provenanceTitle': 'Data source',
  'freshnessTitle': 'Data freshness',
  'freshnessStale': 'Data may be outdated',
  'freshnessExpired': 'Data needs rechecking',
  'lastUpdated': 'Last updated',
  'lastVerified': 'Last verified',
  'communityReportedLabel': 'Community-reported',
  'showMore': 'Show more',
  'showLess': 'Show less',
  'sampleDataLabel': 'Sample data',
  'sampleActionBlocked': 'Live actions disabled for sample data',
  'noInfoAvailable': 'No information available',
  'detailNotFound': 'Restaurant not found',
  'missingPlaceId': 'Missing place ID',
  'galleryCountLabel': 'photos',
  'reviewsSummaryTitle': 'Reviews summary',
};

const Map<String, String> kRestaurantDetailStringsZh = {
  'restaurantDetails': '餐厅详情',
  'movedLabel': '已迁移',
  'movedWarning': '该店可能已迁址',
  'todayHours': '今日营业时间',
  'weeklyHours': '每周时间表',
  'hoursTitle': '营业时间',
  'ratingReviewsTitle': '评分与评价',
  'priceTitle': '价格',
  'cuisineTypeTitle': '菜系与类型',
  'dishHighlights': '招牌菜',
  'servicesLabel': '服务',
  'ambienceLabel': '氛围',
  'halalInfo': '清真信息',
  'dietaryInfo': '饮食信息',
  'allergenInfo': '过敏原信息',
  'allergenCaution': '过敏原数据不完整 — 请向店家确认',
  'dietVerified': '已核实',
  'dietReported': '已报告',
  'dietInferred': '推断',
  'contactLabel': '联系方式',
  'contactUnavailable': '无联系方式',
  'callAction': '致电',
  'websiteAction': '网站',
  'logMealAction': '记录用餐',
  'verificationTitle': '验证',
  'sourceInformation': '来源信息',
  'provenanceTitle': '数据来源',
  'freshnessTitle': '数据新鲜度',
  'freshnessStale': '数据可能过时',
  'freshnessExpired': '数据需要重新核实',
  'lastUpdated': '最后更新',
  'lastVerified': '最后核实',
  'communityReportedLabel': '社区报告',
  'showMore': '显示更多',
  'showLess': '显示更少',
  'sampleDataLabel': '示例数据',
  'sampleActionBlocked': '示例数据已禁用实时操作',
  'noInfoAvailable': '暂无信息',
  'detailNotFound': '未找到餐厅',
  'missingPlaceId': '缺少地点 ID',
  'galleryCountLabel': '张照片',
  'reviewsSummaryTitle': '评价摘要',
};

const Map<String, String> kRestaurantDetailStringsTa = {
  'restaurantDetails': 'உணவக விவரங்கள்',
  'movedLabel': 'இடம் மாறியது',
  'movedWarning': 'இந்த இடம் மாறியிருக்கலாம்',
  'todayHours': 'இன்றைய நேரம்',
  'weeklyHours': 'வாராந்திர அட்டவணை',
  'hoursTitle': 'திறக்கும் நேரம்',
  'ratingReviewsTitle': 'மதிப்பீடு & விமர்சனங்கள்',
  'priceTitle': 'விலை',
  'cuisineTypeTitle': 'உணவு வகை & வகை',
  'dishHighlights': 'சிறப்பு உணவுகள்',
  'servicesLabel': 'சேவைகள்',
  'ambienceLabel': 'சூழல்',
  'halalInfo': 'ஹலால் தகவல்',
  'dietaryInfo': 'உணவுமுறை தகவல்',
  'allergenInfo': 'ஒவ்வாமை தகவல்',
  'allergenCaution': 'ஒவ்வாமை தரவு முழுமையடையவில்லை — கடையில் உறுதி செய்யவும்',
  'dietVerified': 'உறுதிப்படுத்தப்பட்டது',
  'dietReported': 'தெரிவிக்கப்பட்டது',
  'dietInferred': 'ஊகிக்கப்பட்டது',
  'contactLabel': 'தொடர்பு',
  'contactUnavailable': 'தொடர்பு தகவல் இல்லை',
  'callAction': 'அழை',
  'websiteAction': 'இணையதளம்',
  'logMealAction': 'உணவைப் பதிவு செய்',
  'verificationTitle': 'சரிபார்ப்பு',
  'sourceInformation': 'மூல தகவல்',
  'provenanceTitle': 'தரவு மூலம்',
  'freshnessTitle': 'தரவு புத்தம்',
  'freshnessStale': 'தரவு பழையதாக இருக்கலாம்',
  'freshnessExpired': 'தரவை மீண்டும் சரிபார்க்க வேண்டும்',
  'lastUpdated': 'கடைசியாக புதுப்பிக்கப்பட்டது',
  'lastVerified': 'கடைசியாக சரிபார்க்கப்பட்டது',
  'communityReportedLabel': 'சமூகம் தெரிவித்தது',
  'showMore': 'மேலும் காட்டு',
  'showLess': 'குறைவாகக் காட்டு',
  'sampleDataLabel': 'மாதிரி தரவு',
  'sampleActionBlocked': 'மாதிரி தரவுக்கு நேரடி செயல்கள் முடக்கப்பட்டன',
  'noInfoAvailable': 'தகவல் இல்லை',
  'detailNotFound': 'உணவகம் கிடைக்கவில்லை',
  'missingPlaceId': 'இட ID இல்லை',
  'galleryCountLabel': 'படங்கள்',
  'reviewsSummaryTitle': 'விமர்சன சுருக்கம்',
};
