/// PART 1 Phase 1.10 — kunci l10n Butiran Kedai kanonikal (ms/en/zh/ta).
/// Disebar ke dalam AppLocalizations (pola sama seperti sport/place-card strings).
/// Kunci Phase 1.9 (priceUnavailable, hoursUnknown, halal*, dsb.) DIGUNA SEMULA.
library;

const Map<String, String> kRestaurantDetailStringsMs = {
  // WAVE 3D Gate 2 — restaurant engagement (follow, menu comments,
  // official restaurant identity).
  'restaurantFollow': 'Ikut',
  'restaurantFollowing': 'Diikuti',
  'restaurantFollowers': 'pengikut',
  'restaurantEngagementTitle': 'Komuniti kedai',
  'menuCommentsTitle': 'Komen menu',
  'menuCommentsEmpty': 'Belum ada komen. Jadi yang pertama.',
  'menuCommentAdd': 'Tulis komen anda',
  'menuCommentSend': 'Hantar komen',
  'menuCommentFailed': 'Komen gagal dihantar. Cuba lagi.',
  'menuCommentOpen': 'Komen',
  'officialReplyBadge': 'Rasmi',
  'restaurantOfficialBadge': 'Kedai rasmi',
  'restaurantDetails': 'Butiran kedai',
  'movedLabel': 'Telah berpindah',
  'movedWarning': 'Kedai ini mungkin telah berpindah lokasi',
  'todayHours': 'Waktu hari ini',
  'weeklyHours': 'Jadual mingguan',
  'hoursTitle': 'Waktu operasi',
  'dayMonday': 'Isnin',
  'dayTuesday': 'Selasa',
  'dayWednesday': 'Rabu',
  'dayThursday': 'Khamis',
  'dayFriday': 'Jumaat',
  'daySaturday': 'Sabtu',
  'daySunday': 'Ahad',
  'closedAllDay': 'Tutup',
  'open24Hours': '24 jam',
  'breakLabel': 'Rehat',
  'menuTitle': 'Menu',
  'foodMenu': 'Makanan',
  'drinkMenu': 'Minuman',
  'menuUnavailable': 'Tidak tersedia',
  'ratingReviewsTitle': 'Penilaian & ulasan',
  'priceTitle': 'Harga',
  'cuisineTypeTitle': 'Masakan & jenis',
  'dishHighlights': 'Hidangan pilihan',
  'servicesLabel': 'Perkhidmatan',
  'ambienceLabel': 'Suasana',
  'halalInfo': 'Maklumat halal',
  'dietaryInfo': 'Maklumat pemakanan',
  'allergenInfo': 'Maklumat alahan',
  'allergenCaution': 'Data alahan tidak lengkap — sahkan dengan kedai',
  'dietVerified': 'Disahkan',
  'dietReported': 'Dilaporkan',
  'dietInferred': 'Disimpulkan',
  'contactLabel': 'Hubungan',
  'contactUnavailable': 'Tiada maklumat hubungan',
  'callAction': 'Telefon',
  'websiteAction': 'Laman web',
  'logMealAction': 'Log makan',
  'verificationTitle': 'Pengesahan',
  'sourceInformation': 'Maklumat sumber',
  'provenanceTitle': 'Asal data',
  'freshnessTitle': 'Kesegaran data',
  'freshnessStale': 'Data mungkin lapuk',
  'freshnessExpired': 'Data perlu disemak semula',
  'lastUpdated': 'Kemas kini terakhir',
  'lastVerified': 'Sah terakhir',
  'communityReportedLabel': 'Dilaporkan komuniti',
  'showMore': 'Lihat lagi',
  'showLess': 'Lihat kurang',
  'sampleDataLabel': 'Data contoh',
  'sampleActionBlocked': 'Tindakan langsung dimatikan untuk data contoh',
  'noInfoAvailable': 'Tiada maklumat tersedia',
  'detailNotFound': 'Kedai tidak dijumpai',
  'missingPlaceId': 'ID kedai tiada',
  'galleryCountLabel': 'gambar',
  'reviewsSummaryTitle': 'Ringkasan ulasan',
};

const Map<String, String> kRestaurantDetailStringsEn = {
  // WAVE 3D Gate 2 — restaurant engagement (follow, menu comments,
  // official restaurant identity).
  'restaurantFollow': 'Follow',
  'restaurantFollowing': 'Following',
  'restaurantFollowers': 'followers',
  'restaurantEngagementTitle': 'Restaurant community',
  'menuCommentsTitle': 'Menu comments',
  'menuCommentsEmpty': 'No comments yet. Be the first.',
  'menuCommentAdd': 'Write your comment',
  'menuCommentSend': 'Send comment',
  'menuCommentFailed': 'Comment could not be sent. Try again.',
  'menuCommentOpen': 'Comments',
  'officialReplyBadge': 'Official',
  'restaurantOfficialBadge': 'Official restaurant',
  'restaurantDetails': 'Restaurant details',
  'movedLabel': 'Moved',
  'movedWarning': 'This venue may have moved location',
  'todayHours': "Today's hours",
  'weeklyHours': 'Weekly schedule',
  'hoursTitle': 'Opening hours',
  'dayMonday': 'Monday',
  'dayTuesday': 'Tuesday',
  'dayWednesday': 'Wednesday',
  'dayThursday': 'Thursday',
  'dayFriday': 'Friday',
  'daySaturday': 'Saturday',
  'daySunday': 'Sunday',
  'closedAllDay': 'Closed',
  'open24Hours': '24 hours',
  'breakLabel': 'Break',
  'menuTitle': 'Menu',
  'foodMenu': 'Food',
  'drinkMenu': 'Drinks',
  'menuUnavailable': 'Unavailable',
  'ratingReviewsTitle': 'Rating & reviews',
  'priceTitle': 'Price',
  'cuisineTypeTitle': 'Cuisine & type',
  'dishHighlights': 'Dish highlights',
  'servicesLabel': 'Services',
  'ambienceLabel': 'Ambience',
  'halalInfo': 'Halal information',
  'dietaryInfo': 'Dietary information',
  'allergenInfo': 'Allergen information',
  'allergenCaution': 'Allergen data incomplete — confirm with the shop',
  'dietVerified': 'Verified',
  'dietReported': 'Reported',
  'dietInferred': 'Inferred',
  'contactLabel': 'Contact',
  'contactUnavailable': 'No contact information',
  'callAction': 'Call',
  'websiteAction': 'Website',
  'logMealAction': 'Log meal',
  'verificationTitle': 'Verification',
  'sourceInformation': 'Source information',
  'provenanceTitle': 'Data source',
  'freshnessTitle': 'Data freshness',
  'freshnessStale': 'Data may be outdated',
  'freshnessExpired': 'Data needs rechecking',
  'lastUpdated': 'Last updated',
  'lastVerified': 'Last verified',
  'communityReportedLabel': 'Community-reported',
  'showMore': 'Show more',
  'showLess': 'Show less',
  'sampleDataLabel': 'Sample data',
  'sampleActionBlocked': 'Live actions disabled for sample data',
  'noInfoAvailable': 'No information available',
  'detailNotFound': 'Restaurant not found',
  'missingPlaceId': 'Missing place ID',
  'galleryCountLabel': 'photos',
  'reviewsSummaryTitle': 'Reviews summary',
};

const Map<String, String> kRestaurantDetailStringsZh = {
  // WAVE 3D Gate 2 — restaurant engagement (follow, menu comments,
  // official restaurant identity).
  'restaurantFollow': '关注',
  'restaurantFollowing': '已关注',
  'restaurantFollowers': '位关注者',
  'restaurantEngagementTitle': '餐厅社群',
  'menuCommentsTitle': '菜单评论',
  'menuCommentsEmpty': '还没有评论。来做第一个吧。',
  'menuCommentAdd': '写下你的评论',
  'menuCommentSend': '发送评论',
  'menuCommentFailed': '评论发送失败。请再试一次。',
  'menuCommentOpen': '评论',
  'officialReplyBadge': '官方',
  'restaurantOfficialBadge': '官方餐厅',
  'restaurantDetails': '餐厅详情',
  'movedLabel': '已迁移',
  'movedWarning': '该店可能已迁址',
  'todayHours': '今日营业时间',
  'weeklyHours': '每周时间表',
  'hoursTitle': '营业时间',
  'dayMonday': '星期一',
  'dayTuesday': '星期二',
  'dayWednesday': '星期三',
  'dayThursday': '星期四',
  'dayFriday': '星期五',
  'daySaturday': '星期六',
  'daySunday': '星期日',
  'closedAllDay': '休息',
  'open24Hours': '24小时',
  'breakLabel': '休息时段',
  'menuTitle': '菜单',
  'foodMenu': '食物',
  'drinkMenu': '饮料',
  'menuUnavailable': '暂不可用',
  'ratingReviewsTitle': '评分与评价',
  'priceTitle': '价格',
  'cuisineTypeTitle': '菜系与类型',
  'dishHighlights': '招牌菜',
  'servicesLabel': '服务',
  'ambienceLabel': '氛围',
  'halalInfo': '清真信息',
  'dietaryInfo': '饮食信息',
  'allergenInfo': '过敏原信息',
  'allergenCaution': '过敏原数据不完整 — 请向店家确认',
  'dietVerified': '已核实',
  'dietReported': '已报告',
  'dietInferred': '推断',
  'contactLabel': '联系方式',
  'contactUnavailable': '无联系方式',
  'callAction': '致电',
  'websiteAction': '网站',
  'logMealAction': '记录用餐',
  'verificationTitle': '验证',
  'sourceInformation': '来源信息',
  'provenanceTitle': '数据来源',
  'freshnessTitle': '数据新鲜度',
  'freshnessStale': '数据可能过时',
  'freshnessExpired': '数据需要重新核实',
  'lastUpdated': '最后更新',
  'lastVerified': '最后核实',
  'communityReportedLabel': '社区报告',
  'showMore': '显示更多',
  'showLess': '显示更少',
  'sampleDataLabel': '示例数据',
  'sampleActionBlocked': '示例数据已禁用实时操作',
  'noInfoAvailable': '暂无信息',
  'detailNotFound': '未找到餐厅',
  'missingPlaceId': '缺少地点 ID',
  'galleryCountLabel': '张照片',
  'reviewsSummaryTitle': '评价摘要',
};

const Map<String, String> kRestaurantDetailStringsTa = {
  // WAVE 3D Gate 2 — restaurant engagement (follow, menu comments,
  // official restaurant identity).
  'restaurantFollow': 'பின்தொடர்',
  'restaurantFollowing': 'பின்தொடர்கிறீர்கள்',
  'restaurantFollowers': 'பின்தொடர்பவர்கள்',
  'restaurantEngagementTitle': 'உணவகச் சமூகம்',
  'menuCommentsTitle': 'மெனு கருத்துகள்',
  'menuCommentsEmpty': 'இதுவரை கருத்துகள் இல்லை. முதலில் நீங்கள் எழுதுங்கள்.',
  'menuCommentAdd': 'உங்கள் கருத்தை எழுதுங்கள்',
  'menuCommentSend': 'கருத்தை அனுப்பு',
  'menuCommentFailed': 'கருத்தை அனுப்ப முடியவில்லை. மீண்டும் முயற்சிக்கவும்.',
  'menuCommentOpen': 'கருத்துகள்',
  'officialReplyBadge': 'அதிகாரப்பூர்வ',
  'restaurantOfficialBadge': 'அதிகாரப்பூர்வ உணவகம்',
  'restaurantDetails': 'உணவக விவரங்கள்',
  'movedLabel': 'இடம் மாறியது',
  'movedWarning': 'இந்த இடம் மாறியிருக்கலாம்',
  'todayHours': 'இன்றைய நேரம்',
  'weeklyHours': 'வாராந்திர அட்டவணை',
  'hoursTitle': 'திறக்கும் நேரம்',
  'dayMonday': 'திங்கள்',
  'dayTuesday': 'செவ்வாய்',
  'dayWednesday': 'புதன்',
  'dayThursday': 'வியாழன்',
  'dayFriday': 'வெள்ளி',
  'daySaturday': 'சனி',
  'daySunday': 'ஞாயிறு',
  'closedAllDay': 'மூடப்பட்டது',
  'open24Hours': '24 மணி நேரம்',
  'breakLabel': 'இடைவேளை',
  'menuTitle': 'மெனு',
  'foodMenu': 'உணவு',
  'drinkMenu': 'பானங்கள்',
  'menuUnavailable': 'கிடைக்கவில்லை',
  'ratingReviewsTitle': 'மதிப்பீடு & விமர்சனங்கள்',
  'priceTitle': 'விலை',
  'cuisineTypeTitle': 'உணவு வகை & வகை',
  'dishHighlights': 'சிறப்பு உணவுகள்',
  'servicesLabel': 'சேவைகள்',
  'ambienceLabel': 'சூழல்',
  'halalInfo': 'ஹலால் தகவல்',
  'dietaryInfo': 'உணவுமுறை தகவல்',
  'allergenInfo': 'ஒவ்வாமை தகவல்',
  'allergenCaution': 'ஒவ்வாமை தரவு முழுமையடையவில்லை — கடையில் உறுதி செய்யவும்',
  'dietVerified': 'உறுதிப்படுத்தப்பட்டது',
  'dietReported': 'தெரிவிக்கப்பட்டது',
  'dietInferred': 'ஊகிக்கப்பட்டது',
  'contactLabel': 'தொடர்பு',
  'contactUnavailable': 'தொடர்பு தகவல் இல்லை',
  'callAction': 'அழை',
  'websiteAction': 'இணையதளம்',
  'logMealAction': 'உணவைப் பதிவு செய்',
  'verificationTitle': 'சரிபார்ப்பு',
  'sourceInformation': 'மூல தகவல்',
  'provenanceTitle': 'தரவு மூலம்',
  'freshnessTitle': 'தரவு புத்தம்',
  'freshnessStale': 'தரவு பழையதாக இருக்கலாம்',
  'freshnessExpired': 'தரவை மீண்டும் சரிபார்க்க வேண்டும்',
  'lastUpdated': 'கடைசியாக புதுப்பிக்கப்பட்டது',
  'lastVerified': 'கடைசியாக சரிபார்க்கப்பட்டது',
  'communityReportedLabel': 'சமூகம் தெரிவித்தது',
  'showMore': 'மேலும் காட்டு',
  'showLess': 'குறைவாகக் காட்டு',
  'sampleDataLabel': 'மாதிரி தரவு',
  'sampleActionBlocked': 'மாதிரி தரவுக்கு நேரடி செயல்கள் முடக்கப்பட்டன',
  'noInfoAvailable': 'தகவல் இல்லை',
  'detailNotFound': 'உணவகம் கிடைக்கவில்லை',
  'missingPlaceId': 'இட ID இல்லை',
  'galleryCountLabel': 'படங்கள்',
  'reviewsSummaryTitle': 'விமர்சன சுருக்கம்',
};
